### ISSUE TITLE
Improve self-contained-ness of project

### ISSUE THREAD

**Issue by janoside** [janoside/btc-rpc-explorer#101]
To quote @shesek from discussion on #89:

1. This means the explorer will work without dependencies on internet resources and internet access, which makes this more portable and easier to run behind LANs and firewalls.

2. This also has privacy benefits, especially because of the `Referrer` header which leaks the urls of viewed pages (including the txid/blockhash the user was browsing) to the CDN providers.

3. This also has security benefits, because external `<script>` tags with no `integrity` attribute (or all `<script>` tags on browsers that don't support `integrity`) can be modified by the CDN provider to return a different JavaScript code, which would execute inside the btc-rpc-explorer origin sandbox (with access to localStorage, cookies, ability to send XHR requests, etc). From what I can tell, there's currently one `<script>` tag with no `integrity`, which also points to a plain http url with no tls encryption.

---

- [x] Internalize CDN-served frontend resources (jQuery, Bootstrap, fonts, highlight.js, popper.js, tether.js, FontAwesome)
- [x] Internalize mining pool identification configs, with scripted support for re-downloading

**Comment by shesek** [comment]
This is awesome! Thank you very much :)
