### ISSUE TITLE
Error loading recent blocks: TypeError: cache.get(...).then(...).catch(...).finally is not a function

### ISSUE THREAD

**Issue by d3spwn** [janoside/btc-rpc-explorer#108]
I've recently upgraded from version 7a880784ee (2018-12-09) which is running just fine to the current version.

I get an error on startup:

```
Error loading recent blocks: TypeError: cache.get(...).then(...).catch(...).finally is not a function

Unable to get basic blockchain data

    If you just started your node, it may still be initializing.
    If your node is already initialized, check your RPC connection info.
```

Console output:

```
Loading env file: /home/btc-rpc-explorer/btc-rpc-explorer/.env
Loading RPC cookie file: /home/btc-rpc-explorer/.bitcoin/.cookie
Running RPC Explorer for Bitcoin
Connecting via RPC to node at 127.0.0.1:8332
Error 923grf20fge: TypeError: cache.get(...).then(...).catch(...).finally is not a function, error json: {}
```

However I'm pretty sure the RPC connection info is configured correctly:

```
# Bitcoin RPC Credentials (URI -OR- HOST/PORT/USER/PASS)
#BTCEXP_BITCOIND_URI=bitcoin://rpcusername:rpcpassword@127.0.0.1:8332
#BTCEXP_BITCOIND_HOST=localhost
#BTCEXP_BITCOIND_PORT=8332
#BTCEXP_BITCOIND_USER=rpcusername
#BTCEXP_BITCOIND_PASS=rpcpassword
BTCEXP_BITCOIND_COOKIE=/home/btc-rpc-explorer/.bitcoin/.cookie
```

```
btc-rpc-explorer@debian:~/btc-rpc-explorer$ bitcoin-cli -rpccookiefile=/home/btc-rpc-explorer/.bitcoin/.cookie getnetworkinfo
{
  "version": 170100,
  "subversion": "/Satoshi:0.17.1/",
  ...
```

**Comment by d3spwn** [comment]
I think I've tracked down the error to the line below. I'm not a JS programmer though. I don't know what's happening here.

https://github.com/janoside/btc-rpc-explorer/blob/4f2a93532f07b71d30e040ab3d600458ae90261c/app/api/coreApi.js#L129

**Comment by janoside** [comment]
Hey @d3spwn - Thanks for reporting this and doing some investigating. I think the issue has to do with the version of node.js you're running. I think my recent change - be9c3cc - should fix the problem for you by removing the code that requires a newer node.js. Please let me know if you're still seeing the errors. Hopefully this gets you up and running!
