### ISSUE TITLE
Unable to createrawtransaction using rpc browser/terminal

### ISSUE THREAD

**Issue by tmestdagh** [janoside/btc-rpc-explorer#110]
Unable to createrawtransaction using the rpc console or rpc terminal, while I am able to run same command through bitcoin-cli

**Environment:**
 - Bitcoin Core
/Satoshi:0.17.1/
 - NodeJS Version
8
 - Browser 
Chrome
 - Code Version 
master
- Mode
regtest

I am using the Dockerfile and have set the following env vars to true

BTCEXP_RPC_ALLOWALL
BTCEXP_DEMO

**Command**

`createrawtransaction [{"txid": "b873693b1ceacf42d37ddf13daa92dd89c9900d9c0846f3ec309c7a641fd5200", "vout": 0}] {"2N5r2sWX4QEF3BLoaN1xnCyPPzMs7bNp2H9": 10.0}`

**Result**

`[
    {
        "message": "createrawtransaction [{\"txid\":\"id\",\"vout\":n},...] [{\"address\":amount},{\"data\":\"hex\"},...] ( locktime ) ( replaceable )\n\nCreate a transaction spending the given inputs and creating new outputs.\nOutputs can be addresses or data.\nReturns hex-encoded raw transaction.\nNote that the transaction's inputs are not signed, and\nit is not stored in the wallet or transmitted to the network.\n\nArguments:\n1. \"inputs\"                (array, required) A json array of json objects\n     [\n       {\n         \"txid\":\"id\",      (string, required) The transaction id\n         \"vout\":n,         (numeric, required) The output number\n         \"sequence\":n      (numeric, optional) The sequence number\n       } \n       ,...\n     ]\n2. \"outputs\"               (array, required) a json array with outputs (key-value pairs)\n   [\n    {\n      \"address\": x.xxx,    (obj, optional) A key-value pair. The key (string) is the bitcoin address, the value (float or string) is the amount in BTC\n    },\n    {\n      \"data\": \"hex\"        (obj, optional) A key-value pair. The key must be \"data\", the value is hex encoded data\n    }\n    ,...                     More key-value pairs of the above form. For compatibility reasons, a dictionary, which holds the key-value pairs directly, is also\n                             accepted as second parameter.\n   ]\n3. locktime                  (numeric, optional, default=0) Raw locktime. Non-0 value also locktime-activates inputs\n4. replaceable               (boolean, optional, default=false) Marks this transaction as BIP125 replaceable.\n                             Allows this transaction to be replaced by a transaction with higher fees. If provided, it is an error if explicit sequence numbers are incompatible.\n\nResult:\n\"transaction\"              (string) hex string of the transaction\n\nExamples:\n> bitcoin-cli createrawtransaction \"[{\\\"txid\\\":\\\"myid\\\",\\\"vout\\\":0}]\" \"[{\\\"address\\\":0.01}]\"\n> bitcoin-cli createrawtransaction \"[{\\\"txid\\\":\\\"myid\\\",\\\"vout\\\":0}]\" \"[{\\\"data\\\":\\\"00010203\\\"}]\"\n> curl --user myusername --data-binary '{\"jsonrpc\": \"1.0\", \"id\":\"curltest\", \"method\": \"createrawtransaction\", \"params\": [\"[{\\\"txid\\\":\\\"myid\\\",\\\"vout\\\":0}]\", \"[{\\\"address\\\":0.01}]\"] }' -H 'content-type: text/plain;' http://127.0.0.1:8332/\n> curl --user myusername --data-binary '{\"jsonrpc\": \"1.0\", \"id\":\"curltest\", \"method\": \"createrawtransaction\", \"params\": [\"[{\\\"txid\\\":\\\"myid\\\",\\\"vout\\\":0}]\", \"[{\\\"data\\\":\\\"00010203\\\"}]\"] }' -H 'content-type: text/plain;' http://127.0.0.1:8332/\n",
        "code": -1,
        "name": "RpcError"
    }
]`

**Comment by janoside** [comment]
@tmestdagh Check out the recent changes and let me know if the issue is fixed for you.

**Comment by janoside** [comment]
Cleaning up old issues. If you're still having this problem using the latest code (3.4-beta or greater), feel free to reply.
