### ISSUE TITLE
server.ping far too frequent

### ISSUE THREAD

**Issue by kyuupichan** [janoside/btc-rpc-explorer#112]
Someone running your software is connected to my server.  It pings it every 10 seconds.

It is only necessary to ping once every 5 to 8 minutes.  And it's not necessary to ping at all if you have sent a different RPC call in that time.

Please reduce the frequency of these wasteful messages.

**Comment by zooooooooo** [comment]
Are talking about an ElectronX server?

**Comment by kyuupichan** [comment]
No, ElectrumX.  Why does it matter?

**Comment by janoside** [comment]
@kyuupichan Hi, I'm happy to try to help with this issue - I certainly don't want to contribute to bad-netizen behavior. However, this project has very little ElectrumX-specific code. There are no explicit pings. It interfaces with ElectrumX via the npm package [electrum-client](https://github.com/7kharov/node-electrum-client). Upon startup, if any ElectrumX servers are configured the app will connect via electrum-client, but has no further explicit management of the connection.

**Comment by kyuupichan** [comment]
I see; perhaps it's the wrong project then.  I'll open an issue there

**Comment by diegogurpegui** [comment]
I'm reviving this issue to ask if there are plans to adjust this behaviour of frequent ping.
I see now that the project has it's own package https://github.com/janoside/electrum-client
(I report it here since the other project has no ability to accept issues)

**Comment by janoside** [comment]
@diegogurpegui Thanks for reporting this. I agree, ping was too frequent. The electrum-client dependency has been updated so if you run `npm up` you should have 120sec ping period by default.
