### ISSUE TITLE
Settings menu cutoff

### ISSUE THREAD

**Issue by zooooooooo** [janoside/btc-rpc-explorer#113]
Could have sworn the whole layout was wrapped in a container but I just downloaded latest version and appears to be full width* so settings dropdown menu is cutoff. Need another class here "dropdown-menu-right" 
https://github.com/janoside/btc-rpc-explorer/blob/8e1688adea8ed7f5b74ea28946d98982d726d337/views/layout.pug#L51

**Comment by zooooooooo** [comment]
https://github.com/janoside/btc-rpc-explorer/blob/8e1688adea8ed7f5b74ea28946d98982d726d337/views/layout.pug#L82

Sorry, wrong dropdown see new link

**Comment by janoside** [comment]
@zooooooooo I agree that the menu should have `dropdown-menu-right` class added. However, I'm confused about you seeing the layout as full-width. I'm not seeing that locally. Can you give any more info about that while I work on a fix for this issue? Thanks.

**Comment by zooooooooo** [comment]
It was happening on XL screen size I believe, had something to do with responsive resizing. Right aligned menu fixes it. Thank you sir
