### ISSUE TITLE
Please provide instructions for windows installations

### ISSUE THREAD

**Issue by Relaxo143** [janoside/btc-rpc-explorer#114]
I was able to install previous version with just npm install and npm start, but since the new .env was introduced, things seem to be different. It'd be great if you could provide instructions for windows and maybe even include them in the readme file.

**Comment by zooooooooo** [comment]
Run npm install 

Rename ".env-sample" to ".env"

Remove # and set the following variables in .env
BTCEXP_BITCOIND_HOST=localhost
BTCEXP_BITCOIND_PORT=8332
BTCEXP_BITCOIND_USER=
BTCEXP_BITCOIND_PASS=

This should get you rolling

**Comment by Relaxo143** [comment]
> Run npm install
> 
> Rename ".env-sample" to ".env"
> 
> Remove # and set the following variables in .env
> BTCEXP_BITCOIND_HOST=localhost
> BTCEXP_BITCOIND_PORT=8332
> BTCEXP_BITCOIND_USER=
> BTCEXP_BITCOIND_PASS=
> 
> This should get you rolling

Thanks for the reply. I can't have a file with just ".env" so I renamed it to "env.env", however I get this error:`Running RPC Explorer for Bitcoin
Connecting via RPC to node at 127.0.0.1:8332
Error for RPC command 'getnetworkinfo': Error: no auth mechanism defined
Error 923grf20fge: Error: no auth mechanism defined, error json: {"cause":{},"isOperational":true}`

I specified the credentials in the .env fields are removed the #

**Comment by zooooooooo** [comment]
Are you sure your RPC user/pass are correct? I created a .bat file to launch the bitcoind server with RPC credentials. 

_StartBitcoind.bat:_
`@echo off

start "bitcoind" "C:\Program Files\Bitcoin\daemon\bitcoind.exe" -datadir=C:\**BitcoinCore** -txindex=1 -rpcuser=**USERNAME** -rpcpassword=**PASSWORD**`

**Comment by Relaxo143** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/42069389/55934255-ac4a8680-5c38-11e9-8ae9-445e2765b211.png)
I'm sure they are correct. I copied them from the .conf file itself.

**Comment by zooooooooo** [comment]
@Relaxo143 how about if you name it btc-rpc-explorer.env and drop it in the config folder

**Comment by d3spwn** [comment]
Have you tried installing it with [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10)?

**Comment by Relaxo143** [comment]
The .env isn't working for me for some reason so I just start it with btc-rpc-explorer and arguments. Thanks, everyone!
