### ISSUE TITLE
value display

### ISSUE THREAD

**Issue by zooooooooo** [janoside/btc-rpc-explorer#115]
Consider else condition here
https://github.com/janoside/btc-rpc-explorer/blob/098a988ea37b0e14518a6c221f886df948627fbf/views/includes/value-display.pug#L8

i.e.
else
	small #{parts[1]}

Without the following variables in .env, there is no unit displayed next to the quantities
BTCEXP_PRIVACY_MODE=false
BTCEXP_NO_RATES=false

**Comment by janoside** [comment]
@zooooooooo Let me know if that's fixed now. Thanks for catching this glaring bug!
