### ISSUE TITLE
97cfc76442fe717f2a3f0cc9c175f7561b661997

### ISSUE THREAD

**Issue by beer2521** [janoside/btc-rpc-explorer#116]
**Describe the bug**

**Environment (please complete the following information):**
 - Bitcoin Core / Node Version [e.g. 0.16.3]
 - NodeJS Version [e.g. 9.x]
 - Code Version / Commit [e.g. ab6cde8]

**To Reproduce**

**Screenshots or Log Output**
If applicable, add screenshots or log output to help explain your problem.

**Additional context**

**Comment by janoside** [comment]
Need more info.
