### ISSUE TITLE
Feature: Support blockchain.com API for addresses

### ISSUE THREAD

**Issue by janoside** [janoside/btc-rpc-explorer#118]

**Comment by fluidvoice** [comment]
Last time I checked blockchain.com does not support Segwit addresses and therefore neither Lightning, so why should we care?  Blockstream.info API seems the way to go: https://github.com/Blockstream/esplora/blob/master/API.md

**Comment by shesek** [comment]
Happy to try and help with the integration from the Esplora side. I'm thinking that a `GET /address/:address/txids` endpoint that returns just the txids without the full transaction representation might be more useful for btc-rpc-explorer, given that it already has transaction data locally?

**Comment by janoside** [comment]
@shesek That would be awesome. I'm working on some structure to support different address-detail-querying options. I'd love to plug a new esplora `/address/:address/txids` endpoint into that structure.

**Comment by janoside** [comment]
I don't know how technically possible it is, but ideally I'd love to have the ability to page through results to any point directly (using limit=X, offset=Y) to support the same paging UX that already exists in btc-rpc-explorer. It looks like this would be different than the paging style currently supported by `/address/:address/txs`. Support for desc+asc sorting would also be great, if possible.

**Comment by janoside** [comment]
Closing this issue since recent commit adds blockchain.com API support. New issue can be made to integrate esplora API.
