### ISSUE TITLE
Cannot read property 'vin' of undefined

### ISSUE THREAD

**Issue by qshuai** [janoside/btc-rpc-explorer#12]
I can not write pug code, but I encounter this problem. The problem is viewing some blocks is working well but others not.
```
/Users/scrapup/cpp/bti/btc-rpc-explorer/views/includes/block-content.pug:126 124| div(class="row") 125| div(class="col-md-6") > 126| h6 Input (#{tx.vin.length.toLocaleString()}) 127| if (result.txInputsByTransaction[tx.txid]) 128| - var totalInputValue = new Decimal(0); 129| table(class="table mb-0") Cannot read property 'vin' of undefined

TypeError: /Users/scrapup/cpp/bti/btc-rpc-explorer/views/includes/block-content.pug:126
    124| 						div(class="row")
    125| 							div(class="col-md-6")
  > 126| 								h6 Input (#{tx.vin.length.toLocaleString()})
    127| 								if (result.txInputsByTransaction[tx.txid])
    128| 									- var totalInputValue = new Decimal(0);
    129| 									table(class="table mb-0")

Cannot read property 'vin' of undefined
```

**Comment by janoside** [comment]
Thanks for reporting this. Please include a link to an example of a block that's causing this error.

**Comment by scrapup** [comment]
This is my test node(http://47.91.197.178/)   

There is a error when visit block 1,253,881(or other). But some block are ok.

**Comment by janoside** [comment]
@scrapup Great. I'm spinning up a testnet node right now and I'll investigate shortly.

**Comment by janoside** [comment]
@qshuai Have you modified block-content.pug? Have you modified any other code? I have a testnet instance of the app running and I'm not getting the same error for testnet block 1,253,881. Also, what version is your bitcoin node?

**Comment by qshuai** [comment]
@janoside I am so sorry. I encounter this problem because my blocks data are  damaged. It is ok now, thanks!

**Comment by janoside** [comment]
@qshuai No problem. Thanks for the update and glad you got it figured out!
