### ISSUE TITLE
Blockchair address offset

### ISSUE THREAD

**Issue by zooooooooo** [janoside/btc-rpc-explorer#120]
Ex: (http://localhost:3002/address/18VzvzxXpYNYXMEif1jALeZ3G8UTd9rLg8?sort=desc&limit=10&offset=10)

For some reason Page 2 onwards is showing "No transactions"

Found this:
https://github.com/janoside/btc-rpc-explorer/blob/a31c2fb43781b5de43ed91e3980ee11010a9c49f/app/api/blockchairAddressApi.js#L25

If this stays at 10:
`console.log("Math.min(responseObj.transactions.length, limit))",Math.min(responseObj.transactions.length, limit));`

Then the loop wouldn't increment upwards, so I added the offset:
for (var i = offset; i < Math.min(responseObj.transactions.length, limit)**+offset**; i++) {

**Comment by janoside** [comment]
Good catch. Looks like I was applying the offset twice - so it only worked when offset=0. Let me know if #ba1f446 doesn't fix for you.
