### ISSUE TITLE
Feature: Add support for viewing orphaned blocks / double-spend transactions.

### ISSUE THREAD

**Issue by ghost** [janoside/btc-rpc-explorer#124]

**Comment by janoside** [comment]
I like the idea. Happy to accept a PR for this if you're interested in working on it. As far as orphaned blocks go, the best way I see to get them is the RPC "getchaintips". Not sure how to identify double-spend transactions.

**Comment by janoside** [comment]
Closing this for now. Happy to reassess in the future if you're still interested.
