### ISSUE TITLE
Logging info & errors

### ISSUE THREAD

**Issue by sangaman** [janoside/btc-rpc-explorer#128]
It looks like in the current version of the explorer there is (almost) no logging output to the console or to any file that I can find. Is there any logging occurring somewhere that I'm missing or plans to add logging?

**Comment by janoside** [comment]
Sorry about that. Recently changed to “debug” for logging. Need to update the docs to indicate that for logging you should set DEBUG=* in you .env file.

**Comment by sangaman** [comment]
No worries, but I think some basic logging would be good by default. Like logging when the server has finished starting up and is listening for connections, or when there are unexpected errors like bitcoin rpc being unreachable or unhandled exceptions.

**Comment by sangaman** [comment]
Another thought, adding timestamps to the logs would be helpful. Sometimes it's hard to tell where the relevant logging from pulling up a particular page begins and ends without it.
