### ISSUE TITLE
Required same tool for bitcoin cash

### ISSUE THREAD

**Issue by pra021** [janoside/btc-rpc-explorer#13]
hi janoside,

I am looking tool for bitcoin cash

**Comment by janoside** [comment]
Hi, have you tried pointing this tool at your Bitcoin Cash node? I don't run a Bitcoin Cash node myself, but I'm curious what does/doesn't work the same way. I would've assumed that the RPC calls/results were the same and the tool *might* work, as is, with Bitcoin Cash. Please let me know what the results are if you try.

**Comment by janoside** [comment]
I'm not personally interested in this. If anyone is and is interested and willing to contribute something here, I'm game. Closing until then.
