### ISSUE TITLE
Can't explore blocks

### ISSUE THREAD

**Issue by kalibox** [janoside/btc-rpc-explorer#130]
Hi, I've recently installed btc rpc explorer and have txindex=1 enabled but I'm unable to explore blocks on my node. Please see output from the node status below:

Chain | main
-- | --
Version | 180000(/Satoshi:0.18.0/)
Protocol Version | 70015
Blockchain Size | 250.21 GB(pruned: false)
Connections | 31
Block Count | 577,049(headers: 577,049)
Difficulty | 6.705 x 1012
Status | Synchronized with network
Uptime | 12:01:25
Network Traffic | Total Download: 204.8 MB (avg 4.73 KB/s)Total Upload: 7.15 GB(avg 165.13 KB/s)
Warnings | None

Am I doing something wrong with the code base?

Thanks

**Comment by sangaman** [comment]
You can't pull up the blocks and see what transactions are in them? What error are you seeing? I don't think you need to configure an electrum server just to explore blocks, but to do things like lookup addresses and transactions I believe you need that in addition to bitcoind with txindex.

**Comment by kalibox** [comment]
Hi, thank you for the response and apologies for the delay in mine. It appears to be working OK now; had to give it a few hours before all blocks were indexed correctly. Works like a charm now! This can be closed. Thanks!
