### ISSUE TITLE
Donation buttons (btcpay) not working

### ISSUE THREAD

**Issue by CryptAxe** [janoside/btc-rpc-explorer#135]
I'm opening this issue for two different problems.

First of all, if I click on the "support development" button on https://btc.chaintools.io/
the donation module pops up, and the donation address can be displayed. However, the buttons to donate via btcpayserver do not work and display the following error:

```
error | "Warning: No wallet has been linked to your BTCPay Store. See the following link for more information on how to connect your store and wallet. (https://docs.btcpayserver.org/btcpay-basics/gettingstarted#connecting-btcpay-store-to-your-wallet)\n6/25/19 10:44:53 PM: Creation of invoice starting\n6/25/19 10:44:53 PM: BTC_USD: The rating rule is coinaverage(BTC_USD)\n6/25/19 10:44:53 PM: BTC_USD: The evaluated rating rule is 11590.9836088536\n6/25/19 10:44:53 PM: BTC (On-Chain): Payment method details creation took 0 milliseconds\n6/25/19 10:44:53 PM: BTC: Payment method unavailable (Full node not available)\n6/25/19 10:44:53 PM: BTC (Off-Chain): Payment method details creation took 14 milliseconds\n6/25/19 10:44:53 PM: BTC: Payment method unavailable (Full node not available)\n"
```

Second, on an instance that I'm running myself, when I click on the "support development" button nothing pops up at all. Perhaps because I'm just testing the program right now with npm start instead of inside of nginx with pm2 or something like that? I have basically zero experience with this kind of thing sorry.

Thanks!

**Comment by janoside** [comment]
Hi, thanks for this and sorry for the long delay. The donation button on the demo site is now working (for me...please let me know if it's still broken for you).

Concerning the button not responding when you run a local copy: do you see any errors in the browser console (usually available in a "Developer Tools" section of your browser)?

**Comment by janoside** [comment]
@CryptAxe Feel free to reply even though I'm closing the issue...I'm happy to keep helping if needed.
