### ISSUE TITLE
RPC Terminal / Browser login?

### ISSUE THREAD

**Issue by stacy-c** [janoside/btc-rpc-explorer#136]
**Describe the bug**
I'm sure this is just a simple setting in the config file that I need to enable, but I am not sure what to do. When I select "RPC Browser" or "RPC Terminal" from the Tools menu the page delivers the following error:

_RPC Terminal / Browser may not be accessed without logging-in. This restriction can be modified in your config.js file._

**Environment (please complete the following information):**
 - Bitcoin Core 0.17.1 / Node Launcher 6.0.1
 - NodeJS Version 11.9.0
 - Browser = Safari 12.1.1
 - Code Version / Commit = 16e387be89

**To Reproduce**
1. Click on Tools menu
2. Select "RPC Browser" or "RPC Terminal"
3. See error

**Comment by jamespharvey20** [comment]
I believe in your `btc-rpc-explorer.env` configuration, you need to set:

    BTCEXP_BASIC_AUTH_PASSWORD=yourpassword

See https://github.com/janoside/btc-rpc-explorer/blob/master/.env-sample

As that example configuration shows, you can enter any username because only the password is checked.

Also see https://github.com/janoside/btc-rpc-explorer#configuration for where you can place the `btc-rpc-explorer.env`.

**Comment by stacy-c** [comment]
So just uncomment this line below and put my RPC password in? I assume it will prompt me for the password when I navigate to the RPC Browser or Terminal?

> BTCEXP_BASIC_AUTH_PASSWORD=yourpassword

Also: is there a guide on how to update my version of the explorer?

Thank you!

**Comment by janoside** [comment]
For anyone else reading: That's right - set any password you wish for the `BTCEXP_BASIC_AUTH_PASSWORD` and the site will prompt you via a basic-authentication dialog. In the dialog, set any value for the username and then enter your configured password.

@stacy-c Sorry for the delay on your last question - did you figure out how to update? Updating method will depend on how you installed this tool in the first place (from source or via NPM).

**Comment by stacy-c** [comment]
Hi Dan,

Thanks for the reply — I have not upgraded as I’m not sure how to do it. I think I originally installed via NPM.

I now get the authentication prompt and I am able to use the RPC Browser and Terminal, so that is working well.

Sorry about my lack of technical expertise with some of this, I’m still learning.

Stacy


Stacy Conaway
CincoTec.com <http://www.cincotec.com/>
stacy@cincotec.com <mailto:stacy@cincotec.com>
281-352-7877

**Comment by janoside** [comment]
Glad that the RPC pages are working for you now. And no worries about lack of expertise/experience...we all start from the same place! To update this tool installed via npm, I believe that all you'll need to do is run the below command to update to the latest version:

`npm update -g btc-rpc-explorer`

Let me know how that goes if you try it.

**Comment by stacy-c** [comment]
I ran the update command and everything looks good.

Thank you for making this great app available Dan.

I made a BTC donation on July 4, I hope that helps and it appreciates well for you!

Best wishes,
Stacy


Stacy Conaway
CincoTec.com <http://www.cincotec.com/>
stacy@cincotec.com <mailto:stacy@cincotec.com>
281-352-7877

**Comment by janoside** [comment]
Great, glad that worked. Thank you very much for the donation! I'm glad this project has been valuable to you!
