### ISSUE TITLE
How to use IPv6  & IPv4 wildcards with BTCEXP_HOST in btc-rpc-explorer.env?

### ISSUE THREAD

**Issue by HamishMacEwan** [janoside/btc-rpc-explorer#139]
I've tried:

```
#BTCEXP_HOST=[::]
#BTCEXP_HOST=[0:0:0:0:0:0:0:0]
BTCEXP_HOST=0.0.0.0
```
And only the 3rd option, IPv4 worked...

**Comment by janoside** [comment]
@HamishMacEwan I wasn't sure about this myself. But I just did some searching and found [this page](https://webcache.googleusercontent.com/search?q=cache:W-3GYNUuXDoJ:code.danyork.com/2011/01/21/how-to-use-node-js-with-ipv6/+&cd=4&hl=en&ct=clnk&gl=us) (had to use google cache). One of the commends indicates that this can be achieved like:

BTCEXP_HOST=::

I tried this myself and it seemed to work. Let me know if this works for your particular needs. Either way, I'll just pass along that the value of `BTCEXP_HOST` is simply passed to the express `app.listen` (on line 12 of `bin/www` in this repository). So if this setting doesn't work for you, you may want to dig deeper into express/node docs.

**Comment by HamishMacEwan** [comment]
Thank you!  That works for both IPv4 & IPv6!
