### ISSUE TITLE
No address API is configured. See the example configuration file for help setting up an address 

### ISSUE THREAD

**Issue by nicebbs** [janoside/btc-rpc-explorer#142]
http://39.98.207.124:3002/address/oareJgxLKoMMRayjmgFqgy8J2DJ8B929uh
TransactionsTrust Note
No address API is configured. See the example configuration file for help setting up an address API if desired.

**Comment by janoside** [comment]
This is referring to the BTCEXP_ADDRESS_API environment variable. You can set this to any of the values indicated in .env-sample. Note that each option has different privacy implications (running your own ElectrumX server will be more private than using any public website/API). Set that environment variable to something and let me know if you need further help.

**Comment by nicebbs** [comment]
thank  ！I run my own fork money.
