### ISSUE TITLE
Raspibolt: put firewall configuration hints in documentation

### ISSUE THREAD

**Issue by haukehess** [janoside/btc-rpc-explorer#144]
**Describe the bug**
btc-rpc-explorer is running on my raspi fullnode/lightningnode ("raspiblitz")

**Environment (please complete the following information):**
 - Bitcoin Core / Node Version 17.01
 - NodeJS Version [e.g. 9.x]
don't know
all nonlocal browsers
 - Code Version / Commit [e.g. ab6cde8]
1.0.3

**To Reproduce**
1. >npm start on raspi
2. start browser on laptop
3. go to "http://raspiblitz:3002
4. "not available" in browser

**Screenshots or Log Output**

admin@raspiblitz:~/btc-rpc-explorer $ npm start

> btc-rpc-explorer@1.0.3 start /home/admin/btc-rpc-explorer
> node ./bin/www

  btcexp:app Running RPC Explorer for Bitcoin +0ms
  btcexp:app Connecting via RPC to node at 127.0.0.1:8332 +6ms
  btcexp:app Connected via RPC to node. Basic info: version=170100, subversion=/Satoshi:0.17.1/, protocolversion=70015, services=000000000000040d +581ms

**Additional context**
RTL ("Ride the Lightning") runs fine on the same raspi, on port 3000 (so http://raspiblitz:3000 runs it without problems from the same laptop that can't connect to 3002)
I tried adding 3002 to the ports of iptables.

admin@raspiblitz:~/btc-rpc-explorer/app $ sudo iptables -L | grep 3000
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:3000
ACCEPT     udp  --  anywhere             anywhere             udp dpt:3000
admin@raspiblitz:~/btc-rpc-explorer/app $ sudo iptables -L | grep 3002
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:3002
ACCEPT     udp  --  anywhere             anywhere             udp dpt:3002

netstat -tnlpu show the followin:

admin@raspiblitz:~/btc-rpc-explorer/app $ netstat -tnlpu | grep 3002
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:3002          0.0.0.0:*               LISTEN      11565/node          
admin@raspiblitz:~/btc-rpc-explorer/app $ netstat -tnlpu | grep 3000
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp6       0      0 :::3000                 :::*                    LISTEN      -                   

I'm sure its "only" a problem with my firewall settings, but I couldn't find any helpful hint on that in your documentation. When I installed RTL as part of raspiblitz, it did reconfigure my firewall accordingly. It would be great if btc-rpc-explorer could do the same in the future, and until then would contain some information on this in the documentation.

**Comment by Stadicus** [comment]
Maybe the `ufw` config in the RaspiBolt bonus guide for the BTC RPC Explorer helps?
https://stadicus.github.io/RaspiBolt/raspibolt_6B_btc_rpc_explorer.html

**Comment by janoside** [comment]
Closing while cleaning up old issues. I think, generally, there's not a lot to do here - the app runs on port 3002 by default, which I think is clear from existing documentation.
