### ISSUE TITLE
How can I access the rpc terminal/console without a password?

### ISSUE THREAD

**Issue by Relaxo143** [janoside/btc-rpc-explorer#146]
on https://btc-explorer.com when I click on rpc terminal I am not prompted to enter username/password. How can I configure my site to do the same? With the rpc blacklists of course.

**Comment by janoside** [comment]
Try, in your `.env` file:

    BTCEXP_DEMO=true

**Comment by Relaxo143** [comment]
Now the rpc terminal/browser works, but there is no blacklist. All commands are available. I haven't uncommented the custom rpc blacklist in the .env Why is that?
