### ISSUE TITLE
Error loading recent blocks: Error: no auth mechanism definded

### ISSUE THREAD

**Issue by 1215316** [janoside/btc-rpc-explorer#150]
**Environment (please complete the following information):**
 - Bitcoin Core / Node Version [e.g. 0.18.1]
 - NodeJS Version [10.16.3]
 - Browser [chrome]
 - Code Version / Commit [f1fa665]

Hi,

I am trying to get the btc-rpc-explorer to work and having no luck, I have follows the steps

1) in node.js: git clone https://github.com/janoside/btc-rpc-explorer (Completed successfully)

2) opened bitcoin.conf file and confirmed that "txindex=1" & "server=1"

3) in node.js npm install -g btc-rpc-explorer (Completed successfully)

4) in node.js: btc-rpc-explorer
as soon as i press enter i get the following message:

btcexp:app Running RPC Explorer for Bitcoin +0ms
btcexp:app Connecting via RPC to node at 127.0.0.1:8332 +1ms
btcexp:error Error 32euofeege: Error: no auth mechanism defined, json: {"cause":{},"isOperational":true}, userData: [object Object] (json: {"cmd":"getnetworkinfo"}) +0ms
btcexp:error Stack: Error: no auth mechanism defined
btcexp:error at Auth.onRequest (C:\Windows\System32\btc-rpc-explorer\node_modules\request\lib\auth.js:132:32)
btcexp:error at Request.auth (C:\Windows\System32\btc-rpc-explorer\node_modules\request\request.js:1347:14)
btcexp:error at Request.init (C:\Windows\System32\btc-rpc-explorer\node_modules\request\request.js:378:10)
btcexp:error at new Request (C:\Windows\System32\btc-rpc-explorer\node_modules\request\request.js:127:8)
btcexp:error at request (C:\Windows\System32\btc-rpc-explorer\node_modules\request\index.js:53:10)
btcexp:error at C:\Windows\System32\btc-rpc-explorer\node_modules\request\index.js:61:12
btcexp:error at Object.apply (C:\Windows\System32\btc-rpc-explorer\node_modules@uphold\request-logger\src\index.js:27:19)
btcexp:error at Function.post (C:\Windows\System32\btc-rpc-explorer\node_modules\request\index.js💯12)
btcexp:error at Function.tryCatcher (C:\Windows\System32\btc-rpc-explorer\node_modules\bluebird\js\release\util.js:16:23)
btcexp:error at Function.ret [as postAsync] (eval at makeNodePromisifiedEval (C:\Windows\System32\btc-rpc-explorer\node_modules\bluebird\js\release\promisify.js:184:12), :14:23)
btcexp:error at _bluebird.default.try (C:\Windows\System32\btc-rpc-explorer\node_modules\bitcoin-core\dist\src\index.js:168:27)
btcexp:error at tryCatcher (C:\Windows\System32\btc-rpc-explorer\node_modules\bluebird\js\release\util.js:16:23)
btcexp:error at Function.Promise.attempt.Promise.try (C:\Windows\System32\btc-rpc-explorer\node_modules\bluebird\js\release\method.js:39:29)
btcexp:error at Client.command (C:\Windows\System32\btc-rpc-explorer\node_modules\bitcoin-core\dist\src\index.js:154:33)
btcexp:error at Object.rpcCall (C:\Windows\System32\btc-rpc-explorer\app\api\rpcApi.js:227:11)
btcexp:error at C:\Windows\System32\btc-rpc-explorer\app\api\rpcApi.js:17:7 +1ms

If anyone can help me it would be much appreciated... I really want to get this explorer working..

**Comment by 1215316** [comment]
![Error](https://user-images.githubusercontent.com/55649677/65859238-10116900-e3ab-11e9-84c9-432a93be2f6c.png)

**Comment by janoside** [comment]
Configuration issues resolved in another thread. To help improve the situation in the future I also added clear denotation of default configuration values in `.env-sample`.

**Comment by henhito** [comment]
i got the same issue what was the resolution?

**Comment by henhito** [comment]
Apr 05 13:11:50 raspberrypi npm[679]:     at Object.process (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/async/dist/async.js:1648:21)
Apr 05 13:11:50 raspberrypi npm[679]: 2022-04-05T12:11:50.296Z btcexp:error Error 32ugegdfsde: Error: no auth mechanism defined, json: {"userData":{"request":"getnetworkinfo"}}, userData: [object Object] (json: {})
Apr 05 13:11:50 raspberrypi npm[679]: 2022-04-05T12:11:50.296Z btcexp:errorVerbose Stack: Error: no auth mechanism defined

**Comment by cioro86** [comment]
I have the same problem.
`Error 32ugegdfsde: Error: no auth mechanism defined, json: {"user  Data":{"request":"getnetworkinfo"}}, userData: [object Object] (json: {}) +1ms`

I have been following the guide. My .env file is all commented out except for the lines reported here https://raspibolt.org/guide/bitcoin/blockchain-explorer.html in "Configuration".

What can be the issue?
![explorer](https://user-images.githubusercontent.com/60658191/170822942-ad9eb492-357b-493a-97ae-f63a05e6fc27.PNG)

**Comment by artizzle** [comment]
I have this same exact issue. Every time I reboot my node, I get this error. But as soon as I do a systemctl restart then it works. What's the fix for this issue?

**Comment by cioro86** [comment]
Hi @artizzle, sincerely I forgot what I did exactly but I am pretty sure I initially missed 1 command from the https://raspibolt.org/guide/bitcoin/blockchain-explorer.html list. Go through it again and you should have it fixed!

**Comment by artizzle** [comment]
> Hi @artizzle, sincerely I forgot what I did exactly but I am pretty sure I initially missed 1 command from the https://raspibolt.org/guide/bitcoin/blockchain-explorer.html list. Go through it again and you should have it fixed!

Thanks for the reply, I tried that just now again and it didn't fix it but it's OK, it's not a big deal. I'll see if anything is fixed with the next upgrade.

**Comment by cioro86** [comment]
Specifically, I think I forgot one of these commands:

$ sudo adduser --disabled-password --gecos "" btcrpcexplorer
$ sudo adduser btcrpcexplorer bitcoin
$ sudo su - btcrpcexplorer

**Comment by alanStocco** [comment]
Not know if can help anyone in raspibolt I forgot this
BTCEXP_BITCOIND_COOKIE=/data/bitcoin/.cookie

in env file. I leave the default  /path/to/bitcoind/.cookie instead
