### ISSUE TITLE
Vulnerability disclosure

### ISSUE THREAD

**Issue by Relaxo143** [janoside/btc-rpc-explorer#151]
On your demo site (as well as on all sites with default settings which use your open source project) exists a vulnerability which can fork your node off the main chain. The RPC call "invalidateblock" is NOT blacklisted. I just pushed you 10 blocks behind and then brought you back to the main chain with "reconsiderblock". You should fix this, unless you want people messing with your node. Have a nice day!

**Comment by janoside** [comment]
Nevermind, after failing to find docs on bitcoincore.org I went to the [source](https://github.com/bitcoin/bitcoin/blob/master/src/rpc/blockchain.cpp#L2280). Added most of the "hidden" commands.

**Comment by Relaxo143** [comment]
I'm not sure where you can find info for all of them, but I'm glad you succeeded. I never noticed that help doesn't print them out. I just knew they existed and decided to try them out since they weren't in the blacklist in config.js.
