### ISSUE TITLE
Where did the peers map go?

### ISSUE THREAD

**Issue by Relaxo143** [janoside/btc-rpc-explorer#152]
After I updated to new newest version with the new blacklisted commands the peers map is gone. How can I get it back?

**Comment by sangaman** [comment]
Confirmed working again for me with the recent fix.

**Comment by chrisjpn** [comment]
I'm running 1.1.2 and the peers map isn't showing for me now. Neither is the geo-location info for each peer in the JSON tab.

**Comment by dgsqrs** [comment]
I had to read the commit to understand that I need an ipstack api key to get the map fully working. Do I miss a manual/readme somewhere ?
