### ISSUE TITLE
Site keeps crashing

### ISSUE THREAD

**Issue by chrisjpn** [janoside/btc-rpc-explorer#153]
Sorry, newbie question.

I can get the explorer up and running fine, but it crashes after some time. (bitcoind keeps running without issue).

I'm not sure how to check why it keeps crashing. How do I check the log file (raspberry pi)?

Thank you.

**Comment by janoside** [comment]
No worries. Can you give me a little more background about your setup? How did you install the tool and how are you running it?

Running on a RPi you are probably running into out-of-memory errors, but it'd be nice to confirm in your logs - if you let me know that background info we can track down your logs.

**Comment by chrisjpn** [comment]
It's a 3b+ running raspbian. I'm running an external hdd for the bitcoin data, and also an extra swap file (2gb) on there. Current memory status with everything running:

`pi@raspberrypi:~ $ free -m
                   total        used        free      shared  buff/cache   available
Mem:            926         561          31          14         332         296
Swap:          2047         340        1707`

I installed nodejs by downloading from the web (v10.16.3) and copying to /usr/local. I think npm (6.9.0) was already installed.

To install the explorer I did "git clone https://github.com/janoside/btc-rpc-explorer.git"
npm install
npm run
npm start

The only thing I changed in the .env file is the binded IP address so I can access it from another computer.

Thanks!

**Comment by janoside** [comment]
Thanks for all that. Running directly via npm in the console I'd expect log output to be printed out right there, into the console. Is that not the case? For example, on startup do you see log output? And when the app crashes, do you see anything then?

Also, thanks for checking the memory usage. It is likely still possible for you to run into out-of-memory errors even though your system has free memory - in such a case it would be node that would be running out of memory and crashing. Not saying that's for-sure what you're encountering, but still possible despite free system memory.

**Comment by chrisjpn** [comment]
Thanks for your help. Yes the log output is usually printed to the console, however I am accessing the pi via ssh and running the process in the background. It can take some time before it crashes, 12 hours or even more. So I have used the following command to direct the log to a separate file I can check later.

npm start &> output.log &

I'll let you know how I go!

**Comment by janoside** [comment]
Perfect. Was going to suggest similar. Might also help to use `nohup` to prevent crashes from hangup signals though: `nohup npm start &> output.log &`.

Look forward to seeing the results.

**Comment by janoside** [comment]
Any update on this? Were you able to get crash log output?

**Comment by chrisjpn** [comment]
I ran it for a few days but it didn't crash again during that time. I will close the ticket for now. Actually recently I have been running the site on my local machine, as I am translating the explorer into another language (Japanese).
