### ISSUE TITLE
Errors1

### ISSUE THREAD

**Issue by jugi1** [janoside/btc-rpc-explorer#154]
Not possible to read any address balance
Always showing Errors1.

Error Details
{
    "error": null,
    "response": {
        "statusCode": 430,
        "body": "{\"data\":null,\"context\":{\"code\":430,\"error\":\"Your IP address is temporary blacklisted due to exceeding usage of API resources. Please apply for an API key by contacting us at info@blockchair.com\",\"cache\":{\"live\":true,\"duration\":30,\"since\":\"2019-11-02 11:06:52\",\"until\":\"2019-11-02 11:07:22\",\"time\":null},\"api\":{\"version\":\"2.0.39\",\"last_major_update\":\"2019-07-19 18:07:19\",\"next_major_update\":null,\"tested_features\":\"omni-v.a1,whc-v.a1,aggregate-v.b5,xpub-v.b5,ripple-v.a1,ethgraph-v.a1,erc_20-v.a1\",\"documentation\":\"https:\\/\\/github.com\\/Blockchair\\/Blockchair.Support\\/blob\\/master\\/API.md\",\"notice\":\"Beginning July 19th, 2019 all applications using Blockchair API on a constant basis should apply for an API key (mailto:info@blockchair.com)\"}}}",
        "headers": {
            "server": "nginx",
            "content-type": "application/json",
            "transfer-encoding": "chunked",
            "connection": "close",
            "cache-control": "no-cache, private",
            "date": "Sat, 02 Nov 2019 11:06:52 GMT",
            "x-xss-protection": "1; mode=block",
            "access-control-allow-origin": "*",
            "access-control-allow-methods": "GET,POST",
            "access-control-allow-credentials": "true",
            "access-control-allow-headers": "Origin, Content-Type, X-Auth-Token",
            "referrer-policy": "strict-origin",
            "feature-policy": "geolocation none; midi none; notifications none; push none; sync-xhr none; microphone none; camera none; magnetometer none; gyroscope none; speaker self; vibrate none; fullscreen self; payment none;"
        },
        "request": {
            "uri": {
                "protocol": "https:",
                "slashes": true,
                "auth": null,
                "host": "api.blockchair.com",
                "port": 443,
                "hostname": "api.blockchair.com",
                "hash": null,
                "search": "?offset=0",
                "query": "offset=0",
                "pathname": "/bitcoin/dashboards/address/16ftSEQ4ctQFDtVZiUBusQUjRrGhM3JYwe/",
                "path": "/bitcoin/dashboards/address/16ftSEQ4ctQFDtVZiUBusQUjRrGhM3JYwe/?offset=0",
                "href": "https://api.blockchair.com/bitcoin/dashboards/address/16ftSEQ4ctQFDtVZiUBusQUjRrGhM3JYwe/?offset=0"
            },
            "method": "GET",
            "headers": {
                "User-Agent": "request"
            }
        }
    },
    "body": "{\"data\":null,\"context\":{\"code\":430,\"error\":\"Your IP address is temporary blacklisted due to exceeding usage of API resources. Please apply for an API key by contacting us at info@blockchair.com\",\"cache\":{\"live\":true,\"duration\":30,\"since\":\"2019-11-02 11:06:52\",\"until\":\"2019-11-02 11:07:22\",\"time\":null},\"api\":{\"version\":\"2.0.39\",\"last_major_update\":\"2019-07-19 18:07:19\",\"next_major_update\":null,\"tested_features\":\"omni-v.a1,whc-v.a1,aggregate-v.b5,xpub-v.b5,ripple-v.a1,ethgraph-v.a1,erc_20-v.a1\",\"documentation\":\"https:\\/\\/github.com\\/Blockchair\\/Blockchair.Support\\/blob\\/master\\/API.md\",\"notice\":\"Beginning July 19th, 2019 all applications using Blockchair API on a constant basis should apply for an API key (mailto:info@blockchair.com)\"}}}"
}

**Comment by janoside** [comment]
Hi, this is not a fixable issue - from the details of the error it's clear that you're using the "blockchair.com" API to access address data and exceeding the limits they enforce on use of their API. Since they're a 3rd party who own/control the API, you must abide by their usage limits. Access to their API via this tool is provided as a convenience but cannot be supported beyond that. I recommend installing/configuring your own instance of ElectrumX and using that data to show address data.
