### ISSUE TITLE
no need electrum server

### ISSUE THREAD

**Issue by SteepHairy** [janoside/btc-rpc-explorer#162]
the node launched with options
txindex=1
addressindex=1
timestampindex=1
spentindex=1
can accept RPC commands:
getaddressbalance
getaddressdeltas
getaddressmempool
getaddresstxids
getaddressutxos
No need electrum server !!!!!

**Comment by ascisco** [comment]
Are you referring to your bitcoin.conf file?

**Comment by janoside** [comment]
@SteepHairy It sounds like you're using non-standard bitcoind. As I understand, `addressindex` is not part of the project by default, despite there being some code-forks out there that might implement an address index. Are you using a code-fork that implements `addressindex`?

**Comment by janoside** [comment]
Happy to discuss if more detail is added.
