### ISSUE TITLE
Mempool visualization enhancement 

### ISSUE THREAD

**Issue by ascisco** [janoside/btc-rpc-explorer#163]
I think it would be very useful to have a mempoolstats.com style visualization in btc-rpc-explorer for the mempool. I use their "Mempool Size in MB" chart often and find it to be the most comprehensive way of displaying the current mempool for fee estimation.

**Comment by janoside** [comment]
Hi @ascisco - I agree that's a great resource and I've enjoyed using it. I'm open to something similar - if you're interested in submitting code that does this I'll be happy to review it and consider including it here. However, that site's functionality requires storage of past mempool states, which is beyond the conceptual scope of this project. So, I'm closing this for now but, as I said, I'm happy to review/consider pull requests that work toward something like mempoolstats.com

**Comment by ascisco** [comment]
How about a current mempool size in mb broken down by fee rate? Much like mempoolstats, "Mempool Size in MB" without showing the history, just the current breakdown.

**Comment by janoside** [comment]
Sounds like a valuable improvement.
