### ISSUE TITLE
Mempool Seems to be broken. 

### ISSUE THREAD

**Issue by codeShark149** [janoside/btc-rpc-explorer#165]
![mempool](https://user-images.githubusercontent.com/36541669/70251304-40a7c180-17a5-11ea-8bb3-13f728d7d23f.png)
Why my mempool is broken??

I have successful connection to my node. 
` btcexp:app Connected via RPC to node. Basic info: version=190001, subversion=/Satoshi:0.19.0.1/, protocolversion=70015, services=0000000000000409 +235ms
`
Node is running in local server.

I tried recompiling the explorer. Issue persists.

Where should i look at??

**Comment by janoside** [comment]
@codeShark149 Please update to the latest version v1.1.4 and you should be good to go. There was a minor incompatibility running with a 0.19 node.

**Comment by pwpwpwpw** [comment]
> @codeShark149 Please update to the latest version v1.1.4 and you should be good to go. There was a minor incompatibility running with a 0.19 node.

About a month ago my node was running perfectly, I took it down and now started it again, it updated everything but the mempool is off, shows 4.5k transactions while the official one is 36k+, everything else is good.

nodejs 10.19.0
btc core 0.19.0.1
explorer 1.1.8

How do I update btc-rpc-explorer? Do I need to do a clean install of it?
