### ISSUE TITLE
'Current node's chain: undefined' in header

### ISSUE THREAD

**Issue by schildbach** [janoside/btc-rpc-explorer#167]
**Describe the bug**

I get '[]' (tooltip: 'Current node's chain: undefined') in the main page's header, despite the fact that when I click on "Node Status" the chain is correctly detected as "main".

**Environment (please complete the following information):**

 - Firefox 71.0 (from Ubuntu 18.04)
 - Bitcoin Core 0.18.1 running in docker
 - electrumx 1.13.0 running in docker
 - btc-rpc-explorer 1.1.4 running in docker
 
**Configuration file content**

bitcoind:

```
        txindex=1
        disablewallet=1
        peerbloomfilters=1
        logtimestamps=0
        rpcuser=user
        rpcpassword=xxx
        [main]
        rpcbind=bitcoind
```

electrumx:

```
      DAEMON_URL=http://user:xxx@bitcoind
      COIN=BitcoinSegwit
      SERVICES=ssl://electrumx:50002
      PEER_DISCOVERY=self
```

btc-rpc-explorer:

```
      BTCEXP_COIN=BTC
      BTCEXP_HOST=btc-rpc-explorer
      BTCEXP_PORT=3002
      BTCEXP_BITCOIND_URI=bitcoin://user:xxx@bitcoind:8332
      BTCEXP_ADDRESS_API=electrumx
      BTCEXP_ELECTRUMX_SERVERS=tls://electrumx:50002
      BTCEXP_PRIVACY_MODE=true
```

**To Reproduce**

Browse to http://localhost:3002, examine the header, examine "Node Status"

**Additional context**

I've got a second setup for testnet – exactly the same problem there.

**Comment by k3tan172** [comment]
I'm seeing this as well. The way I've been able to fix it is to just restart btc-rpc-explorer. I use a service file on my linux machine to start up btc-rpc-explorer on boot. ```sudo systemctl restart btc-rpc-explorer``` fixes it. But on system start up , I also see this '[]' (tooltip: 'Current node's chain: undefined') error. I also find that exploring transactions and blocks doesn't work when error is on the header.

**Comment by k3tan172** [comment]
I've been looking through the logs and I think this can be explained. The error comes up upon btc-rpc-explorer starting when bitcoind is still 'verifying blocks'. If you delay btc-rpc-explorer from starting up by 60 seconds, allowing bitcoind some time to verify the blocks, then start btc-rpc-explorer, this issue will not present itself. I hope this helps.

**Comment by schildbach** [comment]
Yesterday night I implemented something similar. But instead of waiting for a fixed time (won't work, it can take hours until bitcoind and electrumx are fully synced) I use [wait-for](https://github.com/eficode/wait-for).

Make it available inside the container:

```
    volumes:
      - /<local path>/wait-for/wait-for:/wait-for:ro
```

Wrap container start:

```
    command: sh -c '/wait-for electrumx:50001 --timeout=99999 -- npm start'
```

I think we should leave this issue open, because a workaround like this should not be needed. Btc-rpc-explorer should try to reconnect its connections to other containers at regular intervals until it succeeds.

**Comment by janoside** [comment]
Thanks for the report and discussion here. I agree about the fix - at startup, explorer will now attempt connecting every 30s until success.

**Comment by k3tan172** [comment]
Upgraded to v1.1.5. Can confirm this works. Thank you so much.

**Comment by schildbach** [comment]
Thanks! Works for me too.
