### ISSUE TITLE
Instructions for using HTTPS?

### ISSUE THREAD

**Issue by schildbach** [janoside/btc-rpc-explorer#168]
The [Docker section](https://github.com/janoside/btc-rpc-explorer/blob/master/README.md#run-via-docker) of README.md is somewhat lacking instructions for how to set up an HTTPS page. Does the docker image come with the feature and I'm just missing the necessary config? Or are we supposed to use a separate proxy like [fsouza/docker-ssl-proxy](https://hub.docker.com/r/fsouza/docker-ssl-proxy/)?

**Comment by leshacat** [comment]
See my comment here... Just set up a NGINX reverse proxy either on your host or Docker container. It probably is easier to do on the host machine but you need to expose the docker port and figure out the container's IP address.

https://github.com/janoside/btc-rpc-explorer/issues/134#issuecomment-649291624
