### ISSUE TITLE
Fee and minted coin swapped?

### ISSUE THREAD

**Issue by cryply** [janoside/btc-rpc-explorer#174]
**I got very high fee in TX log**

I add coin file for our coin crp. Everything is fine except fee too high.

**Environment (please complete the following information):**

 - Bitcoin Core / Node Version [e.g. 0.16.3]
 - NodeJS Version [e.g. 9.x]
 - Code Version / Commit [e.g. ab6cde8]
 
**Configuration file content**

Please include the content from the following files. **BE SURE TO MODIFY YOUR CREDENTIALS BEFORE SUBMITTING!!!**
 - cranepay.conf - not needed as there no issues connecting to full node.
 - Your btc-rpc-explorer environment configuration (either `$WORKING_DIR/.env` or `~/.config/btc-rpc-explorer.env`)

This is how I start it:
btc-rpc-explorer -p 8080 -i 85.143.220.110 -u user -w password -H 127.0.0.1 -P 48887  -C CRP

**To Reproduce**

1. Go to https://explorer.cranepay.io/

**Screenshots or Log Output**

https://explorer.cranepay.io/block-height/1912583
it looks like values in minted coins and fee swapped...

**Additional context**

I tried this project half year ago and fee was correct.

**Comment by janoside** [comment]
Sorry, I'm unable to support altcoin implementations of this tool.
