### ISSUE TITLE
external storage

### ISSUE THREAD

**Issue by arshiay** [janoside/btc-rpc-explorer#177]
hi
can any one help me to use this on docker on external hdd for blocks
i download all bitcoin blockchain in a hdd i want to use this with docker
and run this explorer

**Comment by arshiay** [comment]
i need default block address on docker container to point it to my hdd

**Comment by arshiay** [comment]
> btc-rpc-explorer@1.1.4 start /workspace
> node ./bin/www

Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
  btcexp:error Error 3fehge9ee: Error: spawn git ENOENT
  btcexp:error     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
  btcexp:error     at onErrorNT (internal/child_process.js:362:16)
  btcexp:error     at _combinedTickCallback (internal/process/next_tick.js:139:11)
  btcexp:error     at process._tickCallback (internal/process/next_tick.js:181:9)
  btcexp:error     at Function.Module.runMain (module.js:696:11)
  btcexp:error     at startup (bootstrap_node.js:204:16)
  btcexp:error     at bootstrap_node.js:625:3, json: "Error: spawn git ENOENT\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)\n    at onErrorNT (internal/child_process.js:362:16)\n    at _combinedTickCallback (internal/process/next_tick.js:139:11)\n    at process._tickCallback (internal/process/next_tick.js:181:9)\n    at Function.Module.runMain (module.js:696:11)\n    at startup (bootstrap_node.js:204:16)\n    at bootstrap_node.js:625:3", userData: [object Object] (json: {"desc":"Error accessing git repo"}) +0ms
  btcexp:app Starting BTC RPC Explorer, v1.1.4 (code: unknown commit) +0ms
  btcexp:app Connecting to RPC node at 127.0.0.1:8332 +1ms
  btcexp:app Trying to verify RPC connection... +12ms
  btcexp:error Error 32euofeege: Error: no auth mechanism defined, json: {"cause":{},"isOperational":true}, userData: [object Object] (json: {"cmd":"getnetworkinfo"}) +86ms
  btcexp:error Stack: Error: no auth mechanism defined
  btcexp:error     at Auth.onRequest (/workspace/node_modules/request/lib/auth.js:132:32)
  btcexp:error     at Request.auth (/workspace/node_modules/request/request.js:1347:14)
  btcexp:error     at Request.init (/workspace/node_modules/request/request.js:378:10)
  btcexp:error     at new Request (/workspace/node_modules/request/request.js:127:8)
  btcexp:error     at request (/workspace/node_modules/request/index.js:53:10)
  btcexp:error     at /workspace/node_modules/request/index.js:61:12
  btcexp:error     at Object.apply (/workspace/node_modules/@uphold/request-logger/src/index.js:27:19)
  btcexp:error     at Function.post (/workspace/node_modules/request/index.js:100:12)
  btcexp:error     at Function.tryCatcher (/workspace/node_modules/bluebird/js/release/util.js:16:23)
  btcexp:error     at Function.ret [as postAsync] (eval at makeNodePromisifiedEval (/workspace/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
  btcexp:error     at _bluebird.default.try (/workspace/node_modules/bitcoin-core/dist/src/index.js:182:27)
  btcexp:error     at tryCatcher (/workspace/node_modules/bluebird/js/release/util.js:16:23)
  btcexp:error     at Function.Promise.attempt.Promise.try (/workspace/node_modules/bluebird/js/release/method.js:39:29)
  btcexp:error     at Client.command (/workspace/node_modules/bitcoin-core/dist/src/index.js:181:33)
  btcexp:error     at Object.rpcCall (/workspace/app/api/rpcApi.js:280:11)
  btcexp:error     at /workspace/app/api/rpcApi.js:17:7 +0ms
  btcexp:error Error 32ugegdfsde: Error: no auth mechanism defined, json: {"cause":{},"isOperational":true} +3ms
  btcexp:error Stack: Error: no auth mechanism defined
  btcexp:error     at Auth.onRequest (/workspace/node_modules/request/lib/auth.js:132:32)
  btcexp:error     at Request.auth (/workspace/node_modules/request/request.js:1347:14)
  btcexp:error     at Request.init (/workspace/node_modules/request/request.js:378:10)
  btcexp:error     at new Request (/workspace/node_modules/request/request.js:127:8)
  btcexp:error     at request (/workspace/node_modules/request/index.js:53:10)
  btcexp:error     at /workspace/node_modules/request/index.js:61:12
  btcexp:error     at Object.apply (/workspace/node_modules/@uphold/request-logger/src/index.js:27:19)
  btcexp:error     at Function.post (/workspace/node_modules/request/index.js:100:12)
  btcexp:error     at Function.tryCatcher (/workspace/node_modules/bluebird/js/release/util.js:16:23)
  btcexp:error     at Function.ret [as postAsync] (eval at makeNodePromisifiedEval (/workspace/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
  btcexp:error     at _bluebird.default.try (/workspace/node_modules/bitcoin-core/dist/src/index.js:182:27)
  btcexp:error     at tryCatcher (/workspace/node_modules/bluebird/js/release/util.js:16:23)
  btcexp:error     at Function.Promise.attempt.Promise.try (/workspace/node_modules/bluebird/js/release/method.js:39:29)
  btcexp:error     at Client.command (/workspace/node_modules/bitcoin-core/dist/src/index.js:181:33)
  btcexp:error     at Object.rpcCall (/workspace/app/api/rpcApi.js:280:11)
  btcexp:error     at /workspace/app/api/rpcApi.js:17:7 +0ms
  btcexp:app Trying to verify RPC connection... +30s
  btcexp:error Error 32euofeege: Error: no auth mechanism defined, json: {"cause":{},"isOperational":true}, userData: [object Object] (json: {"cmd":"getnetworkinfo"}) +30s
  btcexp:error Stack: Error: no auth mechanism defined
  btcexp:error     at Auth.onRequest (/workspace/node_modules/request/lib/auth.js:132:32)
  btcexp:error     at Request.auth (/workspace/node_modules/request/request.js:1347:14)
  btcexp:error     at Request.init (/workspace/node_modules/request/request.js:378:10)
  btcexp:error     at new Request (/workspace/node_modules/request/request.js:127:8)
  btcexp:error     at request (/workspace/node_modules/request/index.js:53:10)
  btcexp:error     at /workspace/node_modules/request/index.js:61:12
  btcexp:error     at Object.apply (/workspace/node_modules/@uphold/request-logger/src/index.js:27:19)
  btcexp:error     at Function.post (/workspace/node_modules/request/index.js:100:12)
  btcexp:error     at Function.tryCatcher (/workspace/node_modules/bluebird/js/release/util.js:16:23)
  btcexp:error     at Function.ret [as postAsync] (eval at makeNodePromisifiedEval (/workspace/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
  btcexp:error     at _bluebird.default.try (/workspace/node_modules/bitcoin-core/dist/src/index.js:182:27)
  btcexp:error     at tryCatcher (/workspace/node_modules/bluebird/js/release/util.js:16:23)
  btcexp:error     at Function.Promise.attempt.Promise.try (/workspace/node_modules/bluebird/js/release/method.js:39:29)
  btcexp:error     at Client.command (/workspace/node_modules/bitcoin-core/dist/src/index.js:181:33)
  btcexp:error     at Object.rpcCall (/workspace/app/api/rpcApi.js:280:11)
  btcexp:error     at /workspace/app/api/rpcApi.js:17:7 +0ms
  btcexp:error Error 32ugegdfsde: Error: no auth mechanism defined, json: {"cause":{},"isOperational":true} +2ms
  btcexp:error Stack: Error: no auth mechanism defined
  btcexp:error     at Auth.onRequest (/workspace/node_modules/request/lib/auth.js:132:32)
  btcexp:error     at Request.auth (/workspace/node_modules/request/request.js:1347:14)
  btcexp:error     at Request.init (/workspace/node_modules/request/request.js:378:10)
  btcexp:error     at new Request (/workspace/node_modules/request/request.js:127:8)
  btcexp:error     at request (/workspace/node_modules/request/index.js:53:10)
  btcexp:error     at /workspace/node_modules/request/index.js:61:12
  btcexp:error     at Object.apply (/workspace/node_modules/@uphold/request-logger/src/index.js:27:19)
  btcexp:error     at Function.post (/workspace/node_modules/request/index.js:100:12)
  btcexp:error     at Function.tryCatcher (/workspace/node_modules/bluebird/js/release/util.js:16:23)
  btcexp:error     at Function.ret [as postAsync] (eval at makeNodePromisifiedEval (/workspace/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
  btcexp:error     at _bluebird.default.try (/workspace/node_modules/bitcoin-core/dist/src/index.js:182:27)
  btcexp:error     at tryCatcher (/workspace/node_modules/bluebird/js/release/util.js:16:23)
  btcexp:error     at Function.Promise.attempt.Promise.try (/workspace/node_modules/bluebird/js/release/method.js:39:29)
  btcexp:error     at Client.command (/workspace/node_modules/bitcoin-core/dist/src/index.js:181:33)
  btcexp:error     at Object.rpcCall (/workspace/app/api/rpcApi.js:280:11)
  btcexp:error     at /workspace/app/api/rpcApi.js:17:7 +0ms
  btcexp:app Trying to verify RPC connection... +30s
  btcexp:error Error 32euofeege: Error: no auth mechanism defined, json: {"cause":{},"isOperational":true}, userData: [object Object] (json: {"cmd":"getnetworkinfo"}) +30s
  btcexp:error Stack: Error: no auth mechanism defined
  btcexp:error     at Auth.onRequest (/workspace/node_modules/request/lib/auth.js:132:32)
  btcexp:error     at Request.auth (/workspace/node_modules/request/request.js:1347:14)
  btcexp:error     at Request.init (/workspace/node_modules/request/request.js:378:10)
  btcexp:error     at new Request (/workspace/node_modules/request/request.js:127:8)
  btcexp:error     at request (/workspace/node_modules/request/index.js:53:10)
  btcexp:error     at /workspace/node_modules/request/index.js:61:12
  btcexp:error     at Object.apply (/workspace/node_modules/@uphold/request-logger/src/index.js:27:19)
  btcexp:error     at Function.post (/workspace/node_modules/request/index.js:100:12)
  btcexp:error     at Function.tryCatcher (/workspace/node_modules/bluebird/js/release/util.js:16:23)
  btcexp:error     at Function.ret [as postAsync] (eval at makeNodePromisifiedEval (/workspace/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
  btcexp:error     at _bluebird.default.try (/workspace/node_modules/bitcoin-core/dist/src/index.js:182:27)
  btcexp:error     at tryCatcher (/workspace/node_modules/bluebird/js/release/util.js:16:23)
  btcexp:error     at Function.Promise.attempt.Promise.try (/workspace/node_modules/bluebird/js/release/method.js:39:29)
  btcexp:error     at Client.command (/workspace/node_modules/bitcoin-core/dist/src/index.js:181:33)
  btcexp:error     at Object.rpcCall (/workspace/app/api/rpcApi.js:280:11)
  btcexp:error     at /workspace/app/api/rpcApi.js:17:7 +0ms
  btcexp:error Error 32ugegdfsde: Error: no auth mechanism defined, json: {"cause":{},"isOperational":true} +1ms
  btcexp:error Stack: Error: no auth mechanism defined
  btcexp:error     at Auth.onRequest (/workspace/node_modules/request/lib/auth.js:132:32)
  btcexp:error     at Request.auth (/workspace/node_modules/request/request.js:1347:14)
  btcexp:error     at Request.init (/workspace/node_modules/request/request.js:378:10)
  btcexp:error     at new Request (/workspace/node_modules/request/request.js:127:8)
  btcexp:error     at request (/workspace/node_modules/request/index.js:53:10)
  btcexp:error     at /workspace/node_modules/request/index.js:61:12
  btcexp:error     at Object.apply (/workspace/node_modules/@uphold/request-logger/src/index.js:27:19)
  btcexp:error     at Function.post (/workspace/node_modules/request/index.js:100:12)
  btcexp:error     at Function.tryCatcher (/workspace/node_modules/bluebird/js/release/util.js:16:23)
  btcexp:error     at Function.ret [as postAsync] (eval at makeNodePromisifiedEval (/workspace/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
  btcexp:error     at _bluebird.default.try (/workspace/node_modules/bitcoin-core/dist/src/index.js:182:27)
  btcexp:error     at tryCatcher (/workspace/node_modules/bluebird/js/release/util.js:16:23)
  btcexp:error     at Function.Promise.attempt.Promise.try (/workspace/node_modules/bluebird/js/release/method.js:39:29)
  btcexp:error     at Client.command (/workspace/node_modules/bitcoin-core/dist/src/index.js:181:33)
  btcexp:error     at Object.rpcCall (/workspace/app/api/rpcApi.js:280:11)
  btcexp:error     at /workspace/app/api/rpcApi.js:17:7 +0ms

**Comment by arshiay** [comment]
and how set rpc authenticate in docker?

**Comment by arshiay** [comment]
hi
someone help me please i download 300 gb for this and no luck to run

**Comment by janoside** [comment]
Sorry I'm struggling to know what problem you're having. It sounds like you were working through some bitcoin node installation troubles. I recommend looking into any number of readymade "node in a box" products, like myNode or umbrel.

If you have more questions about installation of this specific project I'll be happy to try to help.
