### ISSUE TITLE
Testnet site

### ISSUE THREAD

**Issue by FrancisPouliot** [janoside/btc-rpc-explorer#179]
I wonder if it would be possible tor desirable to do a testnet site that removes the RPC blacklists for everything that doesn't involve actually remove coins from the wallet.

**Comment by janoside** [comment]
I recently set up a public demo testnet site: https://testnet.btc21.org

Do you have a specific configuration for the RPC blacklist that you'd like to see used there?

**Comment by janoside** [comment]
Happy to revisit this if you have feedback. Closing for now.
