### ISSUE TITLE
Does btc-rpc-explorer show onion peers?

### ISSUE THREAD

**Issue by ChineseGeek** [janoside/btc-rpc-explorer#184]
Hello, this can be a tricky question, im running a bitcoin node as a tor hidden service, following Jameson Lopp guide, everything seems ok, im getting more than 10 connections, but i don't know if the node is really running on tor, because there are no onion peers when i look at them on the explorer... Does btc-rpc-explorer show onion peers?

**Comment by janoside** [comment]
@ChineseGeek Yes, onion peers will be displayed if you have them. One thing to check is what your node reports for the `getnetworkinfo` RPC result:

    /rpc-browser?method=getnetworkinfo

Run that on your node. In the results below, verify that your `networks` section has an object like this (though your proxy value may be different):

    {
        "name": "onion",
        "limited": false,
        "reachable": true,
        "proxy": "127.0.0.1:9050",
        "proxy_randomize_credentials": true
    }

If your node reports that `"limited"=true` and/or `"reachable"=false` you probably have a configuration issue. If your node reports results like this, it may just be that no onion peers have connected to you yet. For your reference, on one of my nodes, I have 80 peers and only one of them is an onion peer.

Hope this helps.

**Comment by janoside** [comment]
Closing this for now. But happy to continue discussion here any time.
