### ISSUE TITLE
Avoid using third-party CDN

### ISSUE THREAD

**Issue by stevenroose** [janoside/btc-rpc-explorer#185]
I noticed that the hosted example version uses a third party CDN from CloudFlare.

I didn't check if this is default, but I assume it is as the hosted version is an example of the software.

I'd recommend shipping the dependencies with the software directly instead of using a third party CDN for that. The CDN can take the resource offline, rendering this project broken and you also leak information by querying the file.

![screenshot-2020-02-25-11-54-17](https://user-images.githubusercontent.com/853468/75245536-d449c680-57c5-11ea-97b0-55f72ab2dd4f.png)

**Comment by janoside** [comment]
@stevenroose That's a good catch - I definitely agree with the goal. Most of the frontend assets have already been moved into the project to achieve this goal. I'm curious: can you give me any more details about what assets are shown to be coming from cloudflare? I'm not seeing any myself. Thanks.

**Comment by stevenroose** [comment]
I also don't see them anymore. Now I jus see btc-explorer.com and `camo.githubusercontent.com`.

**Comment by janoside** [comment]
Since the github data is only shown if you configure your site to be a "demo site", I'm closing this since I think the default behavior meets the intended goal. Thanks.
