### ISSUE TITLE
Impossible to connect to Electrum Personal Server

### ISSUE THREAD

**Issue by openchann** [janoside/btc-rpc-explorer#187]
When trying to connect to the Electrum P.S., cannot retrieve TX information. ECONNRESET is the error that i get. Tried to modify the configuration (.env) file to point to the server (localhost+port) without success. Is there any turn around that you can see for this?

Thanks, and love the explorer.

**Comment by eyal352** [comment]
@openchann I am currently having the same issue with EPS. Were you able to resolve this?
