### ISSUE TITLE
Searching for a btc address makes btc-rpc-explorer to crash

### ISSUE THREAD

**Issue by ChineseGeek** [janoside/btc-rpc-explorer#191]
Looking at my peers, i saw a peer that has a btc address in the version asking for support, so i decided to search that address in the explorer, after clicking on search, explorer just crashed, so i decided to go to the terminal and restart explorer again, searched that address again, and crashed again, same behavior after 3 restarts... I attached a screenshot so you can see the btc address and try to reproduce the bug... Its pretty weird... 

Environment:

 - Bitcoin Core 0.19.0.1
 - NodeJS Version 13.7.0
 - Browser Firefox 73.0.1
 
The btc address is 36FfJJo9Kye5JNCTkxE9KJx688vQ51LBgF

![Screenshot from 2020-03-09 20-03-57](https://user-images.githubusercontent.com/488773/76268601-ee16ef00-6244-11ea-95c3-503340650411.png)

**Comment by janoside** [comment]
@ChineseGeek - I'm searching for that address with no problem: see [here](https://explorer.btc21.org/address/36FfJJo9Kye5JNCTkxE9KJx688vQ51LBgF).

Can you please give more info? Is there any log output?

**Comment by janoside** [comment]
Happy to discuss further anytime. Closing for now.
