### ISSUE TITLE
how would i add support for another crypto currency

### ISSUE THREAD

**Issue by jack60612** [janoside/btc-rpc-explorer#192]
Im able to connect to the deamon and connect to the site but im not able to view transactions etc.

how could i add support for this pivx based cryptocurrency called xp coin
i expected for some easy changes but this is not as easy as i hoped
thanks for reading,
Jack

**Comment by janoside** [comment]
Sorry, concerning integrations of other coins you're on your own. This is a bitcoin-focused project.
