### ISSUE TITLE
Items missing in v2.0.0

### ISSUE THREAD

**Issue by ChineseGeek** [janoside/btc-rpc-explorer#194]
I updated btc-rpc-explorer to v2.0.0 but comparing it to explorer.btc21.org i have some missing items in Network Summary, like UTXO Set, Total Supply and almost all on Financials... How can i activate them? 
![Screenshot from 2020-03-25 20-33-35](https://user-images.githubusercontent.com/488773/77598547-7d283600-6ed8-11ea-827d-9fdc584c243d.png)

**Comment by janoside** [comment]
@ChineseGeek - Those items are hidden by your `.env` configuration. Check out [.env-sample](https://github.com/janoside/btc-rpc-explorer/blob/master/.env-sample) for descriptions of the various values that you can set in `.env`.

The two that you might want to set to match the demo site are:

    BTCEXP_NO_RATES=false
    BTCEXP_SLOW_DEVICE_MODE=false

**Comment by kalibox** [comment]
Hi, can this be done via the CLI? I've added --no-rates=false --slow-device-mode=false and can see price info but not UTXO information.

Thanks in advance.
