### ISSUE TITLE
install issue 

### ISSUE THREAD

**Issue by scootwise** [janoside/btc-rpc-explorer#200]
I've had a working btc full node for awhile(v.19), running Electrum server successfully and now want to complete the setup with your explorer.  Installed v 2.0, and when attempting startup, connecting to RPC node is successful, but when i try to open 127.0.0.1:3002 the page does not load.  Telnet to localhost 3002 tells me nothing is listening on 3002.  Not sure where to go next.

Below is the start script, console output and farther down is the output from installation.  I did get alot of warnings when installing, not sure if those are problematic or not.

Would really appreciate any advice.  

Running Mac os Mojave and Python 3.8.  If you need additional info, let me know. Many thanks.

**Start script**
btc-rpc-explorer --port 8080  --bitcoind-cookie /Users/scott/Library/Application\ Support/Bitcoin/.cookie&

**Runtime console output**

 Loading RPC cookie file: /Users/scott/Library/Application Support/Bitcoin/.cookie
  btcexp:app Starting BTC RPC Explorer, v2.0.0 (commit: '8cf258182b', date: 2020-03-28) +0ms
  btcexp:app Connecting to RPC node at 127.0.0.1:8332 +0ms
  btcexp:app Verifying RPC connection... +8ms
  btcexp:app Loading mining pools config +1ms
  btcexp:app RPC Connected: version=190100 subversion=/Satoshi:0.19.1/, parsedVersion(used for RPC versioning)=0.19.1, protocolversion=70015, chain=main, services=[NETWORK, WITNESS, NETWORK_LIMITED] +18ms
  btcexp:app Loading historical data for chain=main +0ms
  btcexp:app Skipping performance-intensive task: fetch UTXO set summary. This is skipped due to the flag 'slowDeviceMode' which defaults to 'true' to protect slow nodes. Set this flag to 'false' to enjoy UTXO set summary details. +0ms
  btcexp:app Network volume: {"d1":{"amt":"831435.07677285","blocks":161,"startBlock":626117,"endBlock":625957,"startTime":1586962652,"endTime":1586878388}} +3s

**btc-rpc-explorer Install output/warnings**

npm install -g btc-rpc-explorer
/usr/local/bin/btc-rpc-explorer -> /usr/local/lib/node_modules/btc-rpc-explorer/bin/cli.js

> dtrace-provider@0.8.8 install /usr/local/lib/node_modules/btc-rpc-explorer/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

  ACTION binding_gyp_ndtp_target_build_ndtp .
  TOUCH Release/obj.target/ndtp.stamp

> tiny-secp256k1@1.1.3 install /usr/local/lib/node_modules/btc-rpc-explorer/node_modules/tiny-secp256k1
> npm run build || echo "secp256k1 bindings compilation fail. Pure JS implementation will be used."

> tiny-secp256k1@1.1.3 build /usr/local/lib/node_modules/btc-rpc-explorer/node_modules/tiny-secp256k1
> node-gyp rebuild

  CXX(target) Release/obj.target/secp256k1/native/addon.o
../native/addon.cpp:240:2: warning: ignoring return value of function declared with 'warn_unused_result' attribute
      [-Wunused-result]
        secp256k1_ec_privkey_negate(context, tweak_negated); // returns 1 always
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~
../native/addon.cpp:320:21: warning: 'BooleanValue' is deprecated: BooleanValue can never throw. Use Isolate version.
      [-Wdeprecated-declarations]
                strict = info[3]->BooleanValue(Nan::GetCurrentContext()).FromJust();
                                  ^
/Users/scott/Library/Caches/node-gyp/12.16.2/include/node/v8.h:2701:3: note: 'BooleanValue' has been explicitly marked
      deprecated here
  V8_DEPRECATED("BooleanValue can never throw. Use Isolate version.",
  ^
/Users/scott/Library/Caches/node-gyp/12.16.2/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../native/addon.cpp:82:23: warning: 'BooleanValue' is deprecated: BooleanValue can never throw. Use Isolate version.
      [-Wdeprecated-declarations]
                return info[index]->BooleanValue(Nan::GetCurrentContext()).FromJust() ? SECP256K1_EC_COMPRESSED : SEC...
                                    ^
../native/addon.cpp:142:21: note: in instantiation of function template specialization '(anonymous
      namespace)::assumeCompression<2, Nan::FunctionCallbackInfo<v8::Value>, v8::Local<v8::Object> >' requested here
        const auto flags = assumeCompression<2>(info, pA);
                           ^
/Users/scott/Library/Caches/node-gyp/12.16.2/include/node/v8.h:2701:3: note: 'BooleanValue' has been explicitly marked
      deprecated here
  V8_DEPRECATED("BooleanValue can never throw. Use Isolate version.",
  ^
/Users/scott/Library/Caches/node-gyp/12.16.2/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../native/addon.cpp:80:21: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
                if (info.Length() <= index) return __isPointCompressed(p) ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UN...
                    ~~~~~~~~~~~~~ ^  ~~~~~
../native/addon.cpp:82:23: warning: 'BooleanValue' is deprecated: BooleanValue can never throw. Use Isolate version.
      [-Wdeprecated-declarations]
                return info[index]->BooleanValue(Nan::GetCurrentContext()).FromJust() ? SECP256K1_EC_COMPRESSED : SEC...
                                    ^
../native/addon.cpp:174:21: note: in instantiation of function template specialization '(anonymous
      namespace)::assumeCompression<1, Nan::FunctionCallbackInfo<v8::Value>, v8::Local<v8::Object> >' requested here
        const auto flags = assumeCompression<1>(info, p);
                           ^
/Users/scott/Library/Caches/node-gyp/12.16.2/include/node/v8.h:2701:3: note: 'BooleanValue' has been explicitly marked
      deprecated here
  V8_DEPRECATED("BooleanValue can never throw. Use Isolate version.",
  ^
/Users/scott/Library/Caches/node-gyp/12.16.2/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../native/addon.cpp:80:21: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
                if (info.Length() <= index) return __isPointCompressed(p) ? SECP256K1_EC_COMPRESSED : SECP256K1_EC_UN...
                    ~~~~~~~~~~~~~ ^  ~~~~~
../native/addon.cpp:89:23: warning: 'BooleanValue' is deprecated: BooleanValue can never throw. Use Isolate version.
      [-Wdeprecated-declarations]
                return info[index]->BooleanValue(Nan::GetCurrentContext()).FromJust() ? SECP256K1_EC_COMPRESSED : SEC...
                                    ^
../native/addon.cpp:189:21: note: in instantiation of function template specialization '(anonymous
      namespace)::assumeCompression<1, Nan::FunctionCallbackInfo<v8::Value> >' requested here
        const auto flags = assumeCompression<1>(info);
                           ^
/Users/scott/Library/Caches/node-gyp/12.16.2/include/node/v8.h:2701:3: note: 'BooleanValue' has been explicitly marked
      deprecated here
  V8_DEPRECATED("BooleanValue can never throw. Use Isolate version.",
  ^
/Users/scott/Library/Caches/node-gyp/12.16.2/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../native/addon.cpp:87:21: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
                if (info.Length() <= index) return SECP256K1_EC_COMPRESSED;
                    ~~~~~~~~~~~~~ ^  ~~~~~
../native/addon.cpp:21:32: warning: unused variable 'ZERO' [-Wunused-const-variable]
        const std::array<uint8_t, 32> ZERO = {};
                                      ^
9 warnings generated.
  CC(target) Release/obj.target/secp256k1/native/secp256k1/src/secp256k1.o
In file included from ../native/secp256k1/src/secp256k1.c:13:
../native/secp256k1/src/group_impl.h:686:12: warning: unused function 'secp256k1_gej_has_quad_y_var' [-Wunused-function]
static int secp256k1_gej_has_quad_y_var(const secp256k1_gej *a) {
           ^
../native/secp256k1/src/group_impl.h:113:13: warning: unused function 'secp256k1_ge_set_gej_var' [-Wunused-function]
static void secp256k1_ge_set_gej_var(secp256k1_ge *r, secp256k1_gej *a) {
            ^
../native/secp256k1/src/group_impl.h:267:12: warning: unused function 'secp256k1_gej_is_valid_var' [-Wunused-function]
static int secp256k1_gej_is_valid_var(const secp256k1_gej *a) {
           ^
In file included from ../native/secp256k1/src/secp256k1.c:15:
../native/secp256k1/src/ecmult_const_impl.h:123:13: warning: unused function 'secp256k1_ecmult_const' [-Wunused-function]
static void secp256k1_ecmult_const(secp256k1_gej *r, const secp256k1_ge *a, const secp256k1_scalar *scalar) {
            ^
4 warnings generated.
  SOLINK_MODULE(target) Release/secp256k1.node

> core-js@2.6.10 postinstall /usr/local/lib/node_modules/btc-rpc-explorer/node_modules/core-js
> node postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

+ btc-rpc-explorer@2.0.0
added 408 packages from 413 contributors in 11.749s

**Comment by scootwise** [comment]
any chance you can take a quick look at this issue?  Thanks.

**Comment by eyal352** [comment]
@scootwise I was having the same exact issue and I had everything installed on an Ubuntu 20.04 server. For me, it turned out to be in the configuration. Once I had changed the following parameter in the .env file
`BTCEXP_HOST=0.0.0.0`
I was able to connect from my network. I hope that works!

**Comment by scootwise** [comment]
Thanks alot for your reply.  I tried your suggestion, but unfortunately no love.  I’m curious, is your explorer and full node running on the same host?

**Comment by scootwise** [comment]
I'm closing this issue, it was a port config problem on my side.
