### ISSUE TITLE
Prediction difficulty adjustment seems inaccurate

### ISSUE THREAD

**Issue by CoxxA** [janoside/btc-rpc-explorer#204]
Forecast difficulty adjustment seems inaccurate, other websites are very accurate, for example btc.com

**Comment by janoside** [comment]
The current estimate takes the entire difficulty epoch's data into account. I'll need to do more research to understand the mechanics of the DA algorithm in bitcoind better. I agree with the goal here, but I don't feel any urgency right now. Happy to accept pull requests with improvements, or comments on this issue with details about the DA algorithm that'll help in improving the estimate.

**Comment by janoside** [comment]
I think I'm going to go back on my earlier comment - in the interest of simplicity I'm going to leave this feature as is, but I updated the hover-text for the feature to more clearly describe what it is and its implications.
