### ISSUE TITLE
Url Path

### ISSUE THREAD

**Issue by gustavonalle** [janoside/btc-rpc-explorer#205]
How to serve the app from another url path, e.g. ```http://localhost:3200/explorer/``` instead of ```http://localhost:3200/``` ?

**Comment by michael1011** [comment]
Would love to have such a feature. Couldn't find a way to make it work either.

**Comment by ketominer** [comment]
I quickly assessed the necessary changes, if I'm not wrong there are a few lines in app.js (no big deal) but all the links for pages and static resources are hardcoded with absolute paths (starting with /) in the pugs so all the pugs need to be modified as well. I'm in the process of doing it but it's hard to not miss some.

**Comment by ketominer** [comment]
https://github.com/ketominer/btc-rpc-explorer/tree/baseurl
I think it's not. I probably didn't test 100% of every possible link inside the app but everything I tested works.
