### ISSUE TITLE
Disable --slow-device-mode

### ISSUE THREAD

**Issue by kalibox** [janoside/btc-rpc-explorer#206]
Hi, whats the best way to disable slowDevicemode? I've tried various permutations via the switch "--slow-device-mode" but none of it appears to work. Thoughts?

Thanks

**Comment by zestysoft** [comment]
I ran into this too -- I could only get it to work by using the environment variable instead:

```
BTCEXP_SLOW_DEVICE_MODE=false btc-rpc-explorer
```

**Comment by kalibox** [comment]
> I ran into this too -- I could only get it to work by using the environment variable instead:
> 
> ```
> BTCEXP_SLOW_DEVICE_MODE=false btc-rpc-explorer
> ```

Ah yes, thanks, that seems to work.
