### ISSUE TITLE
Miners not part listed pools not displayed?

### ISSUE THREAD

**Issue by affiliatepayday** [janoside/btc-rpc-explorer#223]
I am trying to learn this projects codebase. 

One thing I don't understand is the Miner field of the blocks. It seems to rely specifically on mining pools.

Is this expected behavior? Although unlikely it is still possible someone not part of the listed pools mines a block (or more likely someone creates a new pool not listed). 

Does that mean they will show as a `?` until the new pool address and details are added?

**Comment by janoside** [comment]
You're right that only mining "entities" that are identified in the miner config files will be labeled. The config files are updated periodically from 2 remote sources ([see here](https://github.com/janoside/btc-rpc-explorer/blob/master/app/coins/btc.js#L69)) and I also maintain another config for more fun/historical miner identification ([see here](https://github.com/janoside/btc-rpc-explorer/blob/master/public/txt/mining-pools-configs/BTC/2.json)). The config files are flexible enough to theoretically flag "individual miners" as opposed to pools (as I did for Satoshi in the 3rd config), and I'm always happy to include other reliable miner flagging via pull request.
