### ISSUE TITLE
RPC Error handling on main page

### ISSUE THREAD

**Issue by leshacat** [janoside/btc-rpc-explorer#224]
**Describe the bug**

Some daemons may not have certain RPC functions such as "getblockstats". PHL is one of them. It gives an error on the main page when calling the getblockstats RPC call.

**To Reproduce**

1. Install & Configure for a coin like PHL / Placeholders
2. Visit broken explorer here: https://phl.easyx.cc/ or working explorer here https://pexa.easyx.cc
2. See error output when it tries to run the "getblockstats" call to get info for the main page

**Screenshots or Log Output**

![img1](https://i.imgur.com/jvu8M6G.png)
![img2](https://i.imgur.com/RfrRY9y.png)

**Additional context**

PHL is not based off of the BTC core client like PEXA is... Therefore it is missing the RPC call.

Please make the main page especially handle RPC errors better so it can still display the rest of the page.

Thanks :)

**Comment by janoside** [comment]
@leshacat I'm unwilling to support any shitcoins and won't accept any pulls to this repository for that purpose. Please feel free to fork and fix if you're so inclined.
