### ISSUE TITLE
Run btc-rpc-explorer on background

### ISSUE THREAD

**Issue by nicholascarballo** [janoside/btc-rpc-explorer#226]
I have my full node running on a vps and I connect my electrum wallet using ssh tunnel. So far its working good and my transactions are all in sync and only listening on localhost via ssh tunnel. Now I want to run btc-rpc-explorer to check my node whenever I want but everytime I close my ssh window, the code stops running.

I already tried using nohup and 2>1& and it just doesn't work.  What is the correct way of running btc-rpc-explorer always?

Thank you!

**Comment by janoside** [comment]
On the demo server I use the `pm2` package to keep the server running. Give that a try.
