### ISSUE TITLE
Page does not load at all if bitcoind still indexing transactions

### ISSUE THREAD

**Issue by firepol** [janoside/btc-rpc-explorer#227]
**Describe the bug**

bitcoind downloaded the entire blockchain, but is still indexing transactions. btc-rpc-explorer can't be accessed at all.
I'd expect at least to see the UI and only if I hit the search with an address that is not indexed yet I should get an error. Or show the UI and disable all buttons and show a message that indexing is still processing. It''ll be more user friendly.

Same problem while downloading the blockchain. I was expecting that if I don't query the blockchain, at least I could see the basic UI of btc-rpc-explorer. The HTML page I mean...

**Environment (please complete the following information):**

 - Bitcoin Core 0.17.1
 - NodeJS Version 10.21.0
 - Browser Chromium
 - Code Version / Commit 4dae273c
 
**Configuration file content**

Please include the content from the following files. **BE SURE TO MODIFY YOUR CREDENTIALS BEFORE SUBMITTING!!!**
 - bitcoin.conf
```
testnet=0
server=1
daemon=1
disablewallet=1
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333
rpcuser=myrpcuser
rpcpassword=myrpcpwd
txindex=1
dbcache=1024
```
 - Your btc-rpc-explorer environment configuration (`$WORKING_DIR/.env`)
```
BTCEXP_HOST=192.my.ip...
BTCEXP_PORT=3002
BTCEXP_BITCOIND_URI=bitcoin://myrpcuser:myrpcpwd@127.0.0.1:8332?timeout=10000
```

**To Reproduce**

1. Run `yarn start`
2. Trying to browse to http://myhost:3002
3. Page loads for a while, but doesn't show anything
4. On the server I see this error on the screen:

btcexp:error Error 283h7ewsede: Error: RpcError: type=errorResponse-03, json: {"userData":{"error":null,"request":{"method":"getrawtransaction","parameters":["06a8ee39a1d84f4b256077f47b3d6373ecf29b9bf859268f6c3ede1e70a183d6",1]},"result":[{"message":"No such mempool transaction. Blockchain transactions are still in the process of being indexed. Use gettransaction for wallet transactions.","code":-5,"name":"RpcError"}]}}, userData: [object Object] (json: {"error":null,"request":{"method":"getrawtransaction","parameters":["06a8ee39a1d84f4b256077f47b3d6373ecf29b9bf859268f6c3ede1e70a183d6",1]},"result":[{"message":"No such mempool transaction. Blockchain transactions are still in the process of being indexed. Use gettransaction for wallet transactions.","code":-5,"name":"RpcError"}]}) +20ms

**Screenshots or Log Output**

![image](https://user-images.githubusercontent.com/1702718/87905434-d7896b80-ca60-11ea-834e-7beb49362342.png)

**Additional context**

**Comment by jaonoctus** [comment]
Same issue here

**Comment by pouyiouk** [comment]
Yes, this is known to happen. If your node hasn't fully synchronised with the entirety of the chain, page/UI does not load and you might have several errors. - RPC connection failed, error response 1 etc. I have the same issue.

Some fix/suggestion would be for the UI to load regardless if the node synced or not and at least show some info such as: "Synchronising please wait" or "The results are not up to date, please wait until the chain is fully synchronised" - but at least to be able to show something to know that the UI works. It took me couple of hours to realise that it wasn't a problem with the code and it was actually still synchronising. [#247](https://github.com/janoside/btc-rpc-explorer/issues/247) @janoside

**Comment by BitSocial-lb** [comment]
I am still having this problem with bitcoin core v0.21.0 @janoside

**Comment by janoside** [comment]
Cleaning up old issues. If you're still having this problem using the latest code (3.4-beta or greater), feel free to reply.
