### ISSUE TITLE
Question: get only JSON response of addressDetails

### ISSUE THREAD

**Issue by firepol** [janoside/btc-rpc-explorer#228]
Hi,

I'm using btc-rpc-explorer in order to query my own node (because my IP got banned using famous online block explorers...). I need to run a lot of queries to get the balance of many (external) addresses I don't control. I searched around and there seem to be no way to get the balance of external addresses using RPC. So I wonder how do you get the JSON response of `addressDetails` as in the screenshot below?

Example: https://explorer.btc21.org/address/397tBP2WJZ7MFkpAKABrsdvGWU2ipCKvbb

![image](https://user-images.githubusercontent.com/1702718/87909334-5afa8b00-ca68-11ea-9bbc-3941b91d7463.png)

Also, is there a way to query a route of btc-rpc-explorer to get just the `addressDetails` response? In the end I really need just the `balanceSat` value, but the `addressDetails` JSON would be more than enough.

Thanks for letting me know and cheers

**Comment by janoside** [comment]
Hi, the `addressDetails` data there is being queried from an [ElectrumX](https://github.com/spesmilo/electrumx) server I'm running, alongside my BTC node. If you set that up, it exposes an API that you can query. Also, for your reference, I (occasionally) maintain a fork of the code that `btc-rpc-explorer` uses to connect to `ElectrumX` and query it: https://github.com/janoside/electrum-client

The main uses of that package by `btc-rpc-explorer` can be seen in [app/api/electrumAddressApi.js](https://github.com/janoside/btc-rpc-explorer/blob/master/app/api/electrumAddressApi.js):

* [Connect to ElectrumX](https://github.com/janoside/btc-rpc-explorer/blob/master/app/api/electrumAddressApi.js#L52)
* [Get TX history for an address](https://github.com/janoside/btc-rpc-explorer/blob/master/app/api/electrumAddressApi.js#L249)
* [Get balance for an address](https://github.com/janoside/btc-rpc-explorer/blob/master/app/api/electrumAddressApi.js#L289)

Hope this helps.
