### ISSUE TITLE
ERR_EMPTY_RESPONSE for huge addresses

### ISSUE THREAD

**Issue by 3ntranced** [janoside/btc-rpc-explorer#232]
what settings can I change to get a response for huge addresses such as this? (I am using electrs)

btcrpc:3002/address/147SwRQdpCfj5p8PnfsXV2SsVVpVcz3aPq

I just get  btcrpc didn’t send any data. ERR_EMPTY_RESPONSE

**Comment by odomdev** [comment]
yes I facing the same issue ? why api get address not working ?

**Comment by janoside** [comment]
A note has been added in the UI indicating that you can modify the electrs variable `--txid-limit` if you wish to support larger responses on your local instance. I continue to look forward to a future electrumX/electrs improvement that will enable proper paging of these responses, but this is the best that can be done today.

**Comment by odomdev** [comment]
janoside  where to set --txid-limit in electrumx ?

**Comment by janoside** [comment]
@odomdev That setting only applies to electrs, not electrumx.

**Comment by odomdev** [comment]
where is That setting only applies to electrs ? can share me the screenshot ? what is electrs ?

**Comment by janoside** [comment]
electrs and electrumx are 2 different electrum servers.

Electrs: https://github.com/romanz/electrs
ElectrumX: https://github.com/spesmilo/electrumx

Best wishes to you, but I'm sorry I can't provide any more technical support for these other projects, only btc-rpc-explorer.

**Comment by odomdev** [comment]
we are using ElectrumX: https://github.com/spesmilo/electrumx ? how to fix issue search address containing many transaction?

**Comment by janoside** [comment]
It is not currently possible.

**Comment by odomdev** [comment]
i think can do otherway, when search address containing many transaction. can list only last 100 transactions ?
