### ISSUE TITLE
Forking an altcoin block generates error

### ISSUE THREAD

**Issue by gmorchio** [janoside/btc-rpc-explorer#234]
Hi all!
Nice blockexplorer. I'm using it for a personal proyect, i'm creating an altcoin litecoin based for education purposes. A created a json based on ltc.json, just replaced the hashes, weight and all the need stuff, deleted some others as well.
But when a start the app, I got an error:
btcexp:error Error nds9fc2eg621tf3: TypeError: Cannot read property 'main' of undefined, json: {}, userData: [object Object] (json: {"cacheKey":"getBlockStatsByHeight-0"}) +0ms
  btcexp:app Unhandled Rejection at: Promise Promise {
  <rejected> TypeError: Cannot read property 'main' of undefined
    at Object.getBlockStatsByHeight (/home/user/btc-rpc-explorer/app/api/rpcApi.js:91:59)
    at /home/user/btc-rpc-explorer/app/api/coreApi.js:264:17
    at finallyFunc (/home/user/btc-rpc-explorer/app/api/coreApi.js:171:5)
    at /home/user/btc-rpc-explorer/app/api/coreApi.js:192:4
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) } reason: TypeError: Cannot read property 'main' of undefined
    at Object.getBlockStatsByHeight (/home/user/btc-rpc-explorer/app/api/rpcApi.js:91:59)
    at /home/user/btc-rpc-explorer/app/api/coreApi.js:264:17
    at finallyFunc (/home/user/btc-rpc-explorer/app/api/coreApi.js:171:5)
    at /home/user/btc-rpc-explorer/app/api/coreApi.js:192:4
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) stack: TypeError: Cannot read property 'main' of undefined
    at Object.getBlockStatsByHeight (/home/user/btc-rpc-explorer/app/api/rpcApi.js:91:59)
    at /home/user/btc-rpc-explorer/app/api/coreApi.js:264:17
    at finallyFunc (/home/user/btc-rpc-explorer/app/api/coreApi.js:171:5)
    at /home/user/btc-rpc-explorer/app/api/coreApi.js:192:4
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) +24ms

No idea what could be.
Here is the wlc.json, maybe I destroyed the structure:
var Decimal = require("decimal.js");
Decimal8 = Decimal.clone({ precision:8, rounding:8 });

var currencyUnits = [
        {
                type:"native",
                name:"WLC",
                multiplier:1,
                default:true,
                values:["", "wlc", "WLC"],
                decimalPlaces:8
        },
        {
                type:"native",
                name:"walos",
                multiplier:1000,
                values:["walos"],
                decimalPlaces:5
        },
        {
                type:"native",
                name:"washitos",
                multiplier:1000000,
                values:["washitos"],
                decimalPlaces:2
        },
        {
                type:"native",
                name:"waloshi",
                multiplier:100000000,
                values:["waloshi", "wls"],
                decimalPlaces:0
        },
        {
                type:"exchanged",
                name:"USD",
                multiplier:"usd",
                values:["usd"],
                decimalPlaces:2,
                symbol:"$"
        },
];

module.exports = {
        name:"WaloCoin",
        ticker:"WLC",
        logoUrl:"/img/logo/ltc.svg",
        siteTitle:"Walocoin Explorer",
        nodeTitle:"Walocoin Full Node",
        nodeUrl:"https://wlc./",
        demoSiteUrl: "https://ltc.chaintools.io",
        miningPoolsConfigUrls:[
                "https://raw.githubusercontent.com/hashstream/pools/master/pools.json",
        ],
        maxBlockWeight: 4000000,
        targetBlockTimeSeconds: 150,
        currencyUnits:currencyUnits,
        currencyUnitsByName:{"WLC":currencyUnits[0], "walos":currencyUnits[1], "washitos":currencyUnits[2], "waloshi":currencyUnits[3]},
        baseCurrencyUnit:currencyUnits[3],
        defaultCurrencyUnit:currencyUnits[0],
        feeSatoshiPerByteBucketMaxima: [5, 10, 25, 50, 100, 150, 200, 250],
        genesisBlockHash: "6e296fdd3a49bf0beab52bf38ce2cb9bfdc56d5bb35d58787a7cbe9144f373e3",
        genesisCoinbaseTransactionId: "2103f0c284c24806be1a917bed80c599a440b37940b993d625683b05f9ebb9dc",
        genesisCoinbaseTransaction: {
                "txid":"2103f0c284c24806be1a917bed80c599a440b37940b993d625683b05f9ebb9dc",
                "hash":"2103f0c284c24806be1a917bed80c599a440b37940b993d625683b05f9ebb9dc",
                "blockhash":"6e296fdd3a49bf0beab52bf38ce2cb9bfdc56d5bb35d58787a7cbe9144f373e3",
                "version":1,
                "locktime":0,
                "size":206,
                "vsize":206,
                "time":1597639885,
                "blocktime":1597639885,
                "vin":[
                        {
                                "prev_out":{
                                        "hash":"0000000000000000000000000000000000000000000000000000000000000000",
                                        "n":4294967295
                                },
                                "coinbase":"04ffff001d01044733312041676f73746f2032303139207c2053434c207c204e616365205134533452204834434b314e47205333535331304e53202d2051347b4354465f523376306c757431306e7d"
                        }
                ],
                "vout":[
                        {
                                "value":"50.00000000",
                                "n":0,
                                "scriptPubKey":{
                                        "hex": "4104768dcdff46f1c2a9d62366d45de8eb7c9a71a412c2c48c7fd151466f58853363bd2550f72af307989f2932bdc01cca424831b451a44b917b40aab906fd3b5cffac",
                                        "type":"pubkey",
                                        "reqSigs":1,
                                        "addresses":[
                                                "WbMXCiFf5GiD4E1xBYm6W1vbvmGXLYcaY7"
                                        ]
                                }
                        }
                ]
        },
        historicalData: [
                {
                        type: "blockheight",
                        date: "2020-08-17",
                        blockHeight: 0,
                        blockHash: "6e296fdd3a49bf0beab52bf38ce2cb9bfdc56d5bb35d58787a7cbe9144f373e3",
                        summary: "El Bloque Genesis de Walocoin by n3v1l",
                        alertBodyHtml: "Este es el primer bloque en la blockchain de Walocoin. Tomó cerca de 5 horas en crearse.",
                        referenceUrl: "https://wlc./genesis.html"
                }
        ],
        exchangeRateData:{
                jsonUrl:"https://api.coinmarketcap.com/v1/ticker/Litecoin/",
                exchangedCurrencyName:"usd",
                responseBodySelectorFunction:function(responseBody) {
                        if (responseBody[0] && responseBody[0].price_usd) {
                                return {"usd":responseBody[0].price_usd};
                        }

                        return null;
                }
        },
        blockRewardFunction:function(blockHeight) {
                var eras = [ new Decimal8(50) ];
                for (var i = 1; i < 34; i++) {
                        var previous = eras[i - 1];
                        eras.push(new Decimal8(previous).dividedBy(2));
                }

                var index = Math.floor(blockHeight / 840000);

                return eras[index];
        }
};

any advice would be marvelous.

Regards!

**Comment by janoside** [comment]
Sorry, I don't support LTC anymore (or any other altcoins for that matter) and I don't run an LTC node myself so I can't test/debug. My guess is that your LTC node doesn't support the RPCs that a BTC node does. I recommend sticking with BTC.
