### ISSUE TITLE
Configuration file does not load

### ISSUE THREAD

**Issue by Gehldorf** [janoside/btc-rpc-explorer#240]
This block explorer is on my pc (windows) and I connected it to a full node on a local server. If I manually type in the configuration options in the command line when starting btc-rpc-explorer, it all works fine. However, I cannot get the program to just load the configuration options directly from the .env file when it starts up.

The file is not saved as a text file or anything like that. I did have Windows attempting to automatically associate the configuration file with notepad at first, but removed all the links in the registry. So the .env file is now just an unknown file. 

Anyone know what might be the problem?

**Comment by janoside** [comment]
I'm not sure, but it's likely that the file just isn't being found. There are 2 options for ENV files. For clarity's sake (and to try to avoid any OS-specific confusion...I don't ever test on windows) I'll show the actual code that locates the 2 file-location options:

    path.join(os.homedir(), '.config', 'btc-rpc-explorer.env')

and

    path.join(process.cwd(), '.env')

With these 2 file-location options in mind, you might try renaming your ENV file to `btc-rpc-explorer.env` and placing it at `$HOME\.config\btc-rpc-explorer.env`. Or, you might not have your `.env` in the "current working directory for the app process".

Let me know if any of this helps.

**Comment by janoside** [comment]
Closing for now. Feel free to update with further questions.
