### ISSUE TITLE
ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by pouyiouk** [janoside/btc-rpc-explorer#247]
I have a fully syncronised node as of the time of posting my issue. I am able to connect to the bitcoind node. But after a few seconds I get a socket time out error, then it tries to verify again the RPC connection and keeps doing it until I close the session. Does this has to do with the configuration .env file?

Below is the error I do get:
`Loading env file: /home/testbed/Downloads/block_explorer/btc-rpc-explorer/.env
  btcexp:app Starting BTC RPC Explorer, v2.0.2 (commit: '8e2dc45182', date: 2020-10-23) +0ms
  btcexp:app Connecting to RPC node at 127.0.0.1:8332 +1ms
  btcexp:app Verifying RPC connection... +17ms
  btcexp:app Loading mining pools config +3ms
  btcexp:error Error 9u4278t5h7rfhgf: Error: RpcError: type=failure-01, json: {"userData":{"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":"getnetworkinfo"}}, userData: [object Object] (json: {"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":"getnetworkinfo"}) +0ms
  btcexp:error Error 32ugegdfsde: Error: RpcError: type=failure-01, json: {"userData":{"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":"getnetworkinfo"}} +2ms
btcexp:app Verifying RPC connection... +30s
`
**Environment :**

 - Bitcoin Core: 0.20,  npm Version: 6.14.6 
 - Code Version / Commit:latest - 8e2dc45
 
**Configuration file content**

 - bitcoin.conf - not using one, I directly pass the arguments over terminal:
`./bitcoind -datadir=/home/testbed/Downloads/bitcoin-0.20.0/Bitcoind_data_dir/ -server -rpcuser={myusrname} -rpcpassword={mypswrd} -rpcserialversion=0 -txindex=1
`

**Comment by pouyiouk** [comment]
After observing the client for bitcoind I received the following error:
WARNING: request rejected because http work queue depth exceeded, it can be increased with the -rpcworkqueue= setting

After setting the -rpcworkqueue=maximum, I still get the same error as above. Currently I am out of ideas to try and solve the issue. Can anyone suggest anything?

**Comment by pouyiouk** [comment]
Problem solved after the node was launched via bitcoin-qt client. That is weird though. Maybe using the bitcoind I was never finally synced with the network.

**Comment by olwe1** [comment]
I have the same issue with bitcoincore 0.18.1 and btc-rpc-explorer 2.2.0
