### ISSUE TITLE
Peers map doesn't show any connected nodes despite working ipstack requess

### ISSUE THREAD

**Issue by sangaman** [janoside/btc-rpc-explorer#251]
**Describe the bug**

**Environment (please complete the following information):**

 - Bitcoin Core 0.20.0
 - NodeJS Version 14.15.1
 - Browser Chrome or Firefox
 - Commit 8e2dc45182cb0af6dc10bd979faa99de8c953581
 
**Configuration file content**

btc-rpc-explorer.env

```
BTCEXP_IPSTACK_APIKEY=[my key]
```

**To Reproduce**

Go to peers page, the map loads but nodes are not displayed. Nodes in the list don't have a Location value.

**Screenshots or Log Output**

```
  btcexp:utils Requesting IP-geo: http://api.ipstack.com/95.179.234.5?access_key=[my key] +0ms
[many more lines like above for each node]
  express:view lookup "peers.pug" +775ms
  express:view stat "/home/bitcoin/btc-rpc-explorer/views/peers.pug" +1ms
  express:view render "/home/bitcoin/btc-rpc-explorer/views/peers.pug" +0ms
  express-session saving CHx_Pq7K-QbhKD0x6uhdxvLlgLAQ6gil +3s
  express-session split response +1ms
  express-session set-cookie connect.sid=s%3ACHx_Pq7K-QbhKD0x6uhdxvLlgLAQ6gil.A%2FEQXBTZdho3W15vdExSu640noZdKzQtdoqyGetzlCg; Path=/; HttpOnly +3ms
  express:router <anonymous>  : /peers +2s
  btcexp:actionPerformace Finished action '/peers' in 2675 ms +0ms
```

**Additional context**

This used to work for me, but when I went to check it today it stopped working. I'm not sure when exactly it stopped as I hadn't checked it in a while. The url to api.ipstack.com works fine and shows me a json object with location information if I paste it into my browser, so it's retrieving the data but not displaying it.

**Comment by janoside** [comment]
@sangaman Also looking at this issue. I see the app log in this case, but is there any error output in the browser console/dev tools when you see this issue?

**Comment by sangaman** [comment]
In Firefox I get `This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.`.

In Chromium I get nothing at first and then `DevTools failed to load SourceMap: Could not load content for http://thundroid/js/bootstrap.min.js.map: Load canceled due to load timeout` after a minute or so.

The behavior is still consistent, I can link you to my explorer if you think it would help debug this.

**Comment by janoside** [comment]
@sangaman I'm curious if you're able to update and see if the recent commit `496c175` (update the mapping library js/css to the latest version) fixes this issue for you. In my testing it at least fixes the firefox error you referenced above. If that change doesn't fix the problem for you, it'd be great to be able to debug on your explorer. Depending on your communication preferences, you can DM me on twitter (@janoside) or keybase (@danjanosik) about testing on your explorer if you're still open to that.

**Comment by janoside** [comment]
@sangaman Any update here?

**Comment by sangaman** [comment]
Sorry I missed your earlier post - I'm still having issues (and in fact now the map looks messed up). I'll reach out to you on twitter to see about debugging. Thanks.

**Comment by janoside** [comment]
No worries. It seems there was an issue with that commit anyway that I wasn't hitting in my local testing. Commit `261c7836` includes a fix for the `integrity` attributes of the new css/js files - they were failing to load before resulting in a broken map. Let me know if you're able to test that fix.

**Comment by janoside** [comment]
After testing, it looks like commit `9f956d6` did the trick. Closing.
