### ISSUE TITLE
Electrs v0.8.6 and btc-rpc-explorer

### ISSUE THREAD

**Issue by k3tan172** [janoside/btc-rpc-explorer#258]
I can no longer explorer addresses since the upgrade to electrs v0.8.6.
Is anyone else having issues with btc-rpc-explorer and electrs v0..8.6 and getting them to communicate?

**Comment by sta387** [comment]
I can't How  can you help me ارسال شده از دستگاه Galaxy من
-------- پیام اصلی --------از: k3tan172 <notifications@github.com> تاریخ: ۲۰۲۰/۱۲/۶  ۱۴:۴۴  (GMT+03:30) گیرنده: janoside/btc-rpc-explorer <btc-rpc-explorer@noreply.github.com> گیرنده کپی: Subscribed <subscribed@noreply.github.com> موضوع [janoside/btc-rpc-explorer] Electrs v0.8.6 and btc-rpc-explorer (#258) 
I can no longer explorer addresses since the upgrade to electrs v0.8.6.
Is anyone else having issues with btc-rpc-explorer and electrs v0..8.6 and getting them to communicate?

**Comment by Kixunil** [comment]
@k3tan172 what exactly doesn't work for you? I just tried it with btc-rpc-explorer from #207 and it works without any problem. There could be something changed of course. Since this could affect users of [my project](https://deb.ln-ask.me) as well, I'd like to help you investigate, I just need more information.

**Comment by k3tan172** [comment]
Yeah disregard, it works on my original build.

I'm starting a new build from scratch but for the life of me I can't figure out why I'm getting an error every time I explore an address on btc-rpc-explorer. The error message is under the Trust Note section.

"Error: No ElectrumX connection available. This could mean that the connection was lost or that ElectrumX is processing transactions and therefore not accepting requests. This tool will try to reconnect. If you manage your own ElectrumX server you may want to check your ElectrumX logs."

Here are my settings for electrs and btc-rpc-explorer
ELECTRS
cookie = "user:password"
daemon_rpc_addr = "127.0.0.1:8332"
db_dir = "/home/ketan/electrs/db"
network = "bitcoin"
electrum_rpc_addr = "0.0.0.0:50001"
verbosity = 3

BTC-RPC-EXPLORER
BTCEXP_HOST=0.0.0.0
BTCEXP_BITCOIND_USER=user
BTCEXP_BITCOIND_PASS=password
BTCEXP_ADDRESS_API=electrumx
BTCEXP_ELECTRUMX_SERVERS=tcp://localhost:50001 (I've also tried tcp://127.0.0.1:50001)


The strange thing is that when I start btc-rpc-explorer, it connects to electrs and creates a log of the connection and disconnection. Just not sure what I'm doing wrong here. Electrum Wallet 4.0.6 seems to work fine.

**Comment by Kixunil** [comment]
I wonder, did you try it very soon after starting `electrs`? It takes some time for `electrs` to accept connections after start because it processes new blocks first.

**Comment by k3tan172** [comment]
I've waited a while, but still no connection able to be made. Not sure what it could be.

**Comment by shesek** [comment]
> Electrum Wallet 4.0.6 seems to work fine

Do you happen to have Electrum connected to EPS at the same time that you're using btc-rpc-explorer?

If so, note that EPS is single threaded and can only handle a single client at a time. Try closing Electrum and see if that fixes the issue.

**Comment by k3tan172** [comment]
Electrum is closed when I receive this error. The error ID is:
"errorId": "23t07ug2wghefud"

I can't seem to find in the repo what this could correspond to.

**Comment by k3tan172** [comment]
Ok I seem to have figured this out. It appears to be an npm dependency issue.
These instructions do not seem to work:
``npm install -g btc-rpc-explorer``
``btc-rpc-explorer``
It builds a binary that is potentially without updated dependencies.

These instructions work:
https://github.com/janoside/btc-rpc-explorer/issues/249#issuecomment-722526769
You need to ``npm up`` for this feature to work ``git clone`` the repo, ``npm install`` then ``npm start``

Would much prefer the first set to work.

**Comment by k3tan172** [comment]
Could be that you have older dependencies that work. Mine still works on my debian machine without ``npm up``. But when you install fresh version of nodejs it might have different dependencies that won't work unless you ``npm up``. I installed node.js v15 from here: https://github.com/nodesource/distributions/blob/master/README.md#debinstall

**Comment by Kixunil** [comment]
Ah, that makes sense, I use Debian 10 and npm from packages. Thanks for explaining!

**Comment by lukechilds** [comment]
I'm having the same issue. What's even more strange is that I can see the connection in the electrs logs but btc-rpc-explorer still gives me the error.

electrs:
```
INFO - [10.0.0.6:34798] connected peer
TRACE - RPC Request("{\"jsonrpc\":\"2.0\",\"method\":\"server.version\",\"params\":[\"btc-rpc-explorer-v2\",\"1.4\"],\"id\":1}\n")
```
btc-rpc-explorer:
```
2020-12-13T11:41:10.748Z btcexp:error Error 23t07ug2wghefud: [object Object], json: {"error":"No ElectrumX Connection","userText":"No ElectrumX connection available. This could mean that the connection was lost or that ElectrumX is processing transactions and therefore not accepting requests. This tool will try to reconnect. If you manage your own ElectrumX server you may want to check your ElectrumX logs."}
```

**Comment by lukechilds** [comment]
Can confirm `npm up` resolves the issue for me.

It would be good to get this fixed upstream so official installs work with Electrum servers.

@janoside if you just update the deps and tag a new release that should do the job.
