### ISSUE TITLE
Search by address

### ISSUE THREAD

**Issue by ChristianGrieger** [janoside/btc-rpc-explorer#26]
Hey janoside,

thank you for the nice explorer! I modified it to support another coin and search by block id, block hash, and transaction hash works well. Also, block 0 gets displayed without problems.

I only run into problems when I search by address. Do I need to modify any other value to get this working?

Invalid query: ihgcntcbzgkvfuwfkvq7ghzpzmp26uyscs

Greetings,
Chris

**Comment by janoside** [comment]
Hi @ChristianGrieger - One of the implications of this project being database-free is that it doesn't (currently) support searching by address. The reason for this is that the bitcoind RPC API doesn't support it. I hope to implement address searching in the future, but don't know how yet.

**Comment by ChristianGrieger** [comment]
oh no, thanks for the info.
