### ISSUE TITLE
Feature Request: Locate given transaction in mempool

### ISSUE THREAD

**Issue by 941design** [janoside/btc-rpc-explorer#273]
It would be neat to anticipate where a given transaction is in the mempool, and what the chances are that it will be included in the next (or nth) block.

(Would you be open to merge requests for this feature?)

**Comment by janoside** [comment]
Agree this is a nice feature. Definitely open to merging it if PR available.

**Comment by 941design** [comment]
Where would you prefer the sorting to take place, frontend or backend?
I would lean towards a new backend query for mempool txs sorted by fee per vbyte descending. However locating the sought tx should happen in frontend, in my opinion.
What are your thoughts?
Also, are you aware of any existing js library for transaction sorting?

**Comment by pointbiz** [comment]
This view has the necessary Javascript object with all the transactions with sats per vbyte for each transaction. 
https://github.com/janoside/btc-rpc-explorer/blob/master/views/mempool-summary.pug

It's sorted into groupings by sat/vb and displayed in charts.

I don't know if it's the right place from a UX perspective. But from a practical standpoint the mempool transactions are not cached and they all exist in front end memory on that page.

So, maybe a search box labeled “locate transaction” on that page that would take txid as input then output how many blocks deep in the mempool your transaction is would be VERY useful.

**Comment by pointbiz** [comment]
After more thought maybe the mempool summary page could have 2 tabs for its navigation menu that's displayed after the progress update UI switches to the summary results. 

The first and active tab would be “mempool summary” and the second tab would be “locate transaction”.

The second tab would have an input box with search icon button. The results JS object just needs to be given global scope and then it can be searched when the search icon button is clicked.

The results of searching for your transaction could be visualized like mempool.space but vertically. 

The next thought is how to make the page live and get deltas of mempool transactions?

**Comment by janoside** [comment]
@pointbiz Take a look at the live demo site: https://explorer.btc21.org/mempool-summary. It's live with a working version. Thanks again for the inspiration! I'm closing this, but I'm happy to hear any feedback/thoughts.

**Comment by pointbiz** [comment]
I tried it. The UX is much better than I could have imagined. I like the ability to select a fee rate and get an estimate, that's good for before you send a tx. Custom rate box also great. I think it's great to be embedded in the summary page and the tool tip sections are great for guiding the user. 

One small thing... if the tx is not found there's no visual feedback. Maybe the output field could reset to a dash.

**Comment by pointbiz** [comment]
Small suggestion, I think it might be cleaner to round the block depth estimate. As it is now the range includes 1 decimal place. Doesn't feel right to read in 9.1 blocks.

**Comment by janoside** [comment]
@pointbiz Good feedback! Changes have been made and are live on the demo site.

**Comment by pointbiz** [comment]
Another minor suggestion. Under blocks in the mempool summary section at the top of the page the number of blocks could be rounded. Right now I see 83.8 when I'm expecting to see 84.

**Comment by 941design** [comment]
@janoside @pointbiz Thanks a lot!!!
