### ISSUE TITLE
Support project button doesn't work on local running instance (mynode)

### ISSUE THREAD

**Issue by Transisto** [janoside/btc-rpc-explorer#280]
![image](https://user-images.githubusercontent.com/388716/107110530-8c755100-6816-11eb-87de-57ab132bd5bb.png)
Was expecting a way to donate bitcoin.

**Comment by janoside** [comment]
@Transisto Hmm, can you give any more info about this? Does the button do anything? I don't personally run `myNode` so don't know what configuration changes they may have made.

**Comment by janoside** [comment]
I believe I now know what the issue was. All donation links have been updated in the v3 branch which will be merged soon, so I'm closing this. Thanks for reporting.
