### ISSUE TITLE
Argumentos

### ISSUE THREAD

**Issue by mikyR** [janoside/btc-rpc-explorer#284]
**Describe the bug**

Mikyr
**Environment (please complete the following information):**

 - Bitcoin Core / Node Version [e.g. 0.16.3]
 - NodeJS Version [e.g. 9.x]
 - Code Version / Commit [e.g. ab6cde8]
 
**Configuration file content**

Please include the content from the following files. **BE SURE TO MODIFY YOUR CREDENTIALS BEFORE SUBMITTING!!!**
 - bitcoin.conf
 - Your btc-rpc-explorer environment configuration (either `$WORKING_DIR/.env` or `~/.config/btc-rpc-explorer.env`)

**To Reproduce**

**Screenshots or Log Output**

If applicable, add screenshots or log output to help explain your problem.

**Additional context**

**Comment by janoside** [comment]
Sorry not seeing anything to act on here. Closing, but happy to help if you have more info.
