### ISSUE TITLE
RPC errors 

### ISSUE THREAD

**Issue by falcon-j1** [janoside/btc-rpc-explorer#285]
I run a fully synchronized node. But after a few seconds of running etc-rpc-explorer I am getting a rpcerror (see below) that keeps going until I close the session. I tried to run the node and btc-rpc-explorer on my on my Mac and another one on my Synology NAS (in docker) , but I am getting same error in both environment. I tried also to set a user name and password via BTCEXP_BITCOIND_USER and BTCEXP_BITCOIND_PASS on my env file and node configuration file and also tried to leave both configurations without setting the user name and password - no impact, still getting the error. 

Any idea what is causing the error?

Environment:
Bitcoin core: v0.21.0
nom version: npm@6.14.11
NodeJS: 15.8.0
Browser: Safari 14.0.3, Chrome 88.0.4324.150 

Node configuration file:
rest=1                    
txindex=1                 
printtoconsole=1          
server=1	
rpcport=8332
rpcworkqueue=maximum

Environment (.env) file in the working directory for btc-rpc-explorer:
BTCEXP_DEMO=true 					
BTCEXP_NO_RATES=false				
BTCEXP_SLOW_DEVICE_MODE=false	

The error I get:
  btcexp:app Starting BTC RPC Explorer, v2.2.0 (commit: '10046dc879', date: 2021-02-12) at http://127.0.0.1:3002/ +0ms
  btcexp:app Connecting to RPC node at 127.0.0.1:8332 +1ms
  btcexp:app Verifying RPC connection... +8ms
  btcexp:app Loading mining pools config +1ms
  btcexp:error Error 9u4278t5h7rfhgf: Error: RpcError: type=failure-01, json: {"userData":{"error":{"cause":{},"isOperational":true},"request":"getnetworkinfo"}}, userData: [object Object] (json: {"error":{"cause":{},"isOperational":true},"request":"getnetworkinfo"}) +0ms
  btcexp:error Error 32ugegdfsde: Error: RpcError: type=failure-01, json: {"userData":{"error":{"cause":{},"isOperational":true},"request":"getnetworkinfo"}} +1ms
  btcexp:error Error 9u4278t5h7rfhgf: Error: RpcError: type=failure-01, json: {"userData":{"error":{"cause":{},"isOperational":true},"request":"getmempoolinfo"}}, userData: [object Object] (json: {"error":{"cause":{},"isOperational":true},"request":"getmempoolinfo"}) +9s
  btcexp:error Error 9u4278t5h7rfhgf: Error: RpcError: type=failure-01, json: {"userData":{"error":{"cause":{},"isOperational":true},"request":"getmininginfo"}}, userData: [object Object] (json: {"error":{"cause":{},"isOperational":true},"request":"getmininginfo"}) +0ms
  btcexp:error Error 283h7ewsede: Error: RpcError: type=failure-02, json: {"userData":{"error":{"cause":{},"isOperational":true},"request":{"method":"estimatesmartfee","parameters":[1,"CONSERVATIVE"]}}}, userData: [object Object] (json: {"error":{"cause":{},"isOperational":true},"request":{"method":"estimatesmartfee","parameters":[1,"CONSERVATIVE"]}}) +1ms
  btcexp:error Error 283h7ewsede: Error: RpcError: type=failure-02, json: {"userData":{"error":{"cause":{},"isOperational":true},"request":{"method":"estimatesmartfee","parameters":[6,"CONSERVATIVE"]}}}, userData: [object Object] (json: {"error":{"cause":{},"isOperational":true},"request":{"method":"estimatesmartfee","parameters":[6,"CONSERVATIVE"]}}) +0ms
  btcexp:error Error 283h7ewsede: Error: RpcError: type=failure-02, json: {"userData":{"error":{"cause":{},"isOperational":true},"request":{"method":"estimatesmartfee","parameters":[144,"CONSERVATIVE"]}}}, userData: [object Object] (json: {"error":{"cause":{},"isOperational":true},"request":{"method":"estimatesmartfee","parameters":[144,"CONSERVATIVE"]}}) +0ms
  btcexp:error Error 283h7ewsede: Error: RpcError: type=failure-02, json: {"userData":{"error":{"cause":{},"isOperational":true},"request":{"method":"estimatesmartfee","parameters":[1008,"CONSERVATIVE"]}}}, userData: [object Object] (json: {"error":{"cause":{},"isOperational":true},"request":{"method":"estimatesmartfee","parameters":[1008,"CONSERVATIVE"]}}) +0ms
  btcexp:error Error 283h7ewsede: Error: RpcError: type=failure-02, json: {"userData":{"error":{"cause":{},"isOperational":true},"request":{"method":"getnetworkhashps","parameters":[144]}}}, userData: [object Object] (json: {"error":{"cause":{},"isOperational":true},"request":{"method":"getnetworkhashps","parameters":[144]}}) +0ms
  btcexp:error Error 283h7ewsede: Error: RpcError: type=failure-02, json: {"userData":{"error":{"cause":{},"isOperational":true},"request":{"method":"getnetworkhashps","parameters":[1008]}}}, userData: [object Object] (json: {"error":{"cause":{},"isOperational":true},"request":{"method":"getnetworkhashps","parameters":[1008]}}) +1ms
  btcexp:error Error 9u4278t5h7rfhgf: Error: RpcError: type=failure-01, json: {"userData":{"error":{"cause":{},"isOperational":true},"request":"getblockchaininfo"}}, userData: [object Object] (json: {"error":{"cause":{},"isOperational":true},"request":"getblockchaininfo"}) +0ms

**Comment by pointbiz** [comment]
Have you tried using slow device mode?

Or setting a longer rpc timeout? 

Also, you can reduce the rpc concurrency variable.

**Comment by janoside** [comment]
@falcon-j1 This looks like a connection issue. In the logs I see that it's trying to verify the RPC connection, but it doesn't finish. Please check your connection details (host / port for Bitcoin Core) as well as your authentication params (username, password, etc).

There are also some recent changes (not yet included in an official release) that improve the UX around connection failures. So, if you're running from source, you could update and verify that my suspicion is correct.

I'm closing this for now, but please report back about what you find.

**Comment by falcon-j1** [comment]
I am not running it anymore but when I still did, I tried to play with the rpc timeout parameter and it didn't help. I didn't try slow device mode. I checked connection details few times and it looked OK to me.
Then I tried to use btc-rpc-explorer as part of the mynode bundle and it worked well.
Thank you.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
