### ISSUE TITLE
getblockstats RPC call causes issues in slow device mode

### ISSUE THREAD

**Issue by pointbiz** [janoside/btc-rpc-explorer#286]
I suggest when in slow device mode that 
getblockstats is not called more than once at a time. On my slow Bitseed v3 the explorer will crash if 
getblockstats is called too many times rapidly. 
I have my timeouts set to 180 seconds in the explorer config.

/
Loading the default page causes the explorer to crash. However, on a slow device we don't want that behavior because there's many other useful things to do with the explorer. 

/block-stats
The page will load but the automatic calling of getblockstats for 144 blocks will crash the explorer. I suggest this page is hidden when in slow device mode. 

/blocks
The automatic calling of getblockstats for the latest 10 blocks causes the explorer to crash because bitcoind gives error responses or timeouts. I suggest in slow device mode that only one block is automatically called on this URL.

**Comment by pointbiz** [comment]
I locally solved this issue by modifying the app/config.js

I changed
site.homepage.recentBlocksCount = 1
I changed
site.browseBlocksPageSize = 1

I propose two new environment variables so this can be configured for slow devices. 

BTCEXP_CONFIG_HOME_RECENT_BLOCK_COUNT
BTCEXP_CONFIG_BLOCKS_PAGE_SIZE

The defaults would stay the same and be used if the environment variables are not defined.

I could prepare a pull request if this approach is ok with you.

**Comment by janoside** [comment]
I agree with the overall idea here and the issue you're raising. Another idea that comes to mind is to clamp down the "rpc concurrency" value when in slow device mode. I'll consider the env variables you recommended too.

This isn't the top priority at the moment, but will try to address for the next release because I know lots of users on on "slow" devices.

**Comment by pointbiz** [comment]
V3 fixes this issue. So, I'm closing the issue.
