### ISSUE TITLE
node-bitcoin-script is missing from package.json

### ISSUE THREAD

**Issue by shesek** [janoside/btc-rpc-explorer#287]
Used here:

https://github.com/janoside/btc-rpc-explorer/blob/53080df7cd9fc3dc2da0eb74f7217138cca9d0e4/routes/baseRouter.js#L1414-L1415

(ran into this code by accident, not sure if it actually ever gets run or not)

**Comment by janoside** [comment]
This can only be run via the "command" tool. It's part of an update I was playing with but has been de-prioritized for the moment. Closing, but thanks for the heads up.
