### ISSUE TITLE
Cache static files

### ISSUE THREAD

**Issue by BitPopCoin** [janoside/btc-rpc-explorer#289]
Not a bug and I didn't want to create a tiny pull request so I thought I'd leave this here. Currently static files from /public are not being cached properly and sent with max-age=0

I spent hours trying to figure out why Cloudflare was refusing to cache anything and was blaming Nginx for a while. The following will fix it on line 97 in app.js

`app.use(config.baseUrl, express.static(path.join(__dirname, 'public'), {
  setHeaders: (res, path) => {
    if (path.endsWith('.css') || path.endsWith('.js') || path.endsWith('.woff2') || path.endsWith('.ttf') || path.endsWith('.eot') || path.endsWith('.svg') || path.endsWith('.png') || path.endsWith('.jpg') || path.endsWith('.gif') || path.endsWith('.ico') || path.endsWith('.txt') || path.endsWith('.json')) {
      res.setHeader('Cache-Control', 'public, max-age=2592000');
    }
  },
}));`

**Comment by janoside** [comment]
@BitPopCoin Thanks for this...good catch and sorry for the time spent hunting this down.

I'm curious why the filtering by filetype? Given that this change will just apply to what's in `/public`, do you see a specific downside to something like below (which just uses the `maxAge` option of [serve-static](http://expressjs.com/en/resources/middleware/serve-static.html))?

    expressApp.use(config.baseUrl, express.static(path.join(__dirname, 'public'), {
        maxAge: 60 * 60 * 1000
    }));

**Comment by janoside** [comment]
@BitPopCoin My change described above was just pushed. I'm closing this, but I'm still happy to hear if you think there are any problems with my solution compared to yours. Thanks.

**Comment by BitPopCoin** [comment]
Awesome, I just didn't look into maybe how .well-known would behave so I was cautious. But I don't see any problems.
