### ISSUE TITLE
Bitcoin Core <0.21 compatibility

### ISSUE THREAD

**Issue by shesek** [janoside/btc-rpc-explorer#300]
The recently added [support for txindex-less nodes](#279) uses `getindexinfo` to determine if `txindex` is enabled or not, which did not exists prior to Bitcoin Core v0.21.

Is this acceptable, or would you like to find a way to support older Bitcoin Core releases too?

**Comment by shesek** [comment]
(I accidentally tagged this as a bug and can't seem to remove it now. Whether its a bug or not is up to interpretation)

**Comment by janoside** [comment]
@shesek Ideally yes, I'd like to try to support older releases. I first started trying to manage old-release support when `getblockstats` calls were introduced (you can see some of what I did in `rpcApi.js` by looking at the  "minRpcVersions" const and the "getBlockStats" function).

In all honesty, maintaining compatibility is an aspirational goal, but I don't currently run old versions myself for testing and don't spend tons of thought/effort on managing this.

If you can just give a quick review to the code that depends on `getindexinfo` and see if the requirement can be easily downgraded, that'd be enough for this issue.

In the meantime I'll take a TODO item myself to set up an old release for testing...

**Comment by janoside** [comment]
@shesek I thought about this some more and did some testing with a 0.18.0 node and decided it's pretty important to handle this situation to keep older nodes functioning.

Not sure if you're aware, but I've been working on a major version update and just merged it in today. I was hoping to tag and release v3.0.0 tomorrow morning EST.

With that tentative deadline in mind, I made a change to address this particular `getindexinfo` issue (which is prominent since it prevents proper startup) and I'd be happy to get your thoughts on it since you worked on a lot of the related changes.

**Comment by pointbiz** [comment]
I have a 0.18.0 node on my Bitseed (slow device). I also have a server with 0.19.1. I would generally upgrade and test my typical happy paths after each tagged release. 

I can test in advance of a release if needed and time permitting.

**Comment by shesek** [comment]
This could theoretically try to lookup a txid that is known to exists to determine if `txindex` is available or not. But I think that only supporting pruned nodes in v0.21+ is a reasonable choice.

I did notice you were working on v3 -- congrats for getting it merged, looks like you did some great work there! :tada: :rocket:

**Comment by pointbiz** [comment]
I tested v3 with Bitcoin Core 0.19.1
All my happy paths are working. I was also able to look up transactions older than 3 blocks. I have txindex=1 however on the node details page it believes txindex is not set.

I like the suggestion of looking up a known transaction to determine if txindex=1

**Comment by janoside** [comment]
@pointbiz Awesome, thanks for testing on 0.19.1! I agree - I like the known-tx-lookup concept and will plan that for the next update (keeping this open to track that).

**Comment by janoside** [comment]
I believe 76c4087 addresses this issue fully. Closing this, but I'd be happy to hear any feedback about the change.

**Comment by shesek** [comment]
@janoside LGTM
