### ISSUE TITLE
txindex: unavailable

### ISSUE THREAD

**Issue by BitSocial-lb** [janoside/btc-rpc-explorer#302]
bticoincore v0.21.0

getindexinfo
{
}

Status: Synchronized with network
txindex: unavailable

bitcoin.conf

server=1
txindex=1

shall I change bitcoin.conf ? 

Thank you

**Comment by BitSocial-lb** [comment]
it's not a bug, just a question

**Comment by shesek** [comment]
`txindex` is not required as of the latest v3.0.0 release, but [some functionality will be limited](https://github.com/janoside/btc-rpc-explorer#note-about-pruning-and-indexing-configurations) without it.
