### ISSUE TITLE
Pulling prices

### ISSUE THREAD

**Issue by Covalent5** [janoside/btc-rpc-explorer#305]
![image](https://user-images.githubusercontent.com/29493544/114313829-d9202580-9b00-11eb-88fa-6c547ce7877a.jpeg)

Any idea how to fix?

**Comment by janoside** [comment]
@Covalent5 Thanks for reporting this. I appreciate the screenshot, but could you also includes a copy-paste of the full error output pictured here? Thanks.

**Comment by janoside** [comment]
@Covalent5 I was able to reproduce the issue and have put in a fix. If you're running from source, you can update now. This fix will be included in an official release soon.

**Comment by Covalent5** [comment]
> @Covalent5 I was able to reproduce the issue and have put in a fix. If you're running from source, you can update now. This fix will be included in an official release soon.

Awesome! Thank you very much! Keep up the amazing work. Really appreciated!
