### ISSUE TITLE
Version 3.0.0 signed with unexpected/unverifiable key

### ISSUE THREAD

**Issue by Kixunil** [janoside/btc-rpc-explorer#307]
**Describe the bug**

The release appears to be signed with key `1EE29744D09C9DF5AC0737F7846311D3D259BFF1`.
However the key `F8C4D8BFB1F02CAE3A8F9057C6F8CE9FFDB2CED2` was used before.
Keybase contains `F579929B39B119CC7B0BB71FB326ACF51F317B69`

The key `1EE29744D09C9DF5AC0737F7846311D3D259BFF1` is not signed by the keybase key nor published on keybase and can not be cross-checked in any other way. Thus I'm unable to verify the authenticity of the new release.

Am I under attack?

**To Reproduce**

1. `git clone https://github.com/janoside/btc-rpc-explorer`
2. `gpg --recv-keys F8C4D8BFB1F02CAE3A8F9057C6F8CE9FFDB2CED2`
3. `git verify-commit "\`git rev-list -n 1 "v3.0.0"\`"`
4. See error complaining about missing key
5. `gpg --recv-keys 1EE29744D09C9DF5AC0737F7846311D3D259BFF1`
6. `git verify-commit "\`git rev-list -n 1 "v3.0.0"\`"` succeeds, however
7. `gpg --list-sigs 1EE29744D09C9DF5AC0737F7846311D3D259BFF1` doesn't contain any signature from previously trusted key
8. Go to keybase - `1EE29744D09C9DF5AC0737F7846311D3D259BFF1` not present/proven.

**Comment by janoside** [comment]
No attack! Just a maintainer (me) with too little gpg knowledge/experience. Sorry about that.

I just attempted (via the `GPG Keychain` tool on macOS) to sign `1EE29744D09C9DF5AC0737F7846311D3D259BFF1` with `F579929B39B119CC7B0BB71FB326ACF51F317B69` and publish the signature. It indicated success. I'd like to add `1EE2` to my keybase profile, but not finding how to do that at the moment.

Does the signature I published get you what you need at a minimum?

I'm happy to keep working on my key setup (and happy to take any recommendations you have), but want to get you this update ASAP to avoid any worry!

**Comment by Kixunil** [comment]
I don't see the signature after syncing the key. Which keyserver did you use? They should sync between each-other but it may be that they didn't yet.

Anyway, yes signing `1EE29744D09C9DF5AC0737F7846311D3D259BFF1` with `F579929B39B119CC7B0BB71FB326ACF51F317B69` will be fine when I see the signature.

**Comment by janoside** [comment]
@Kixunil Did that signature propagate?

Regardless, v3.1.0 is out now, signed with the same key as previous releases. Closing this, but please let me know if you got the signature for future reference.

**Comment by Kixunil** [comment]
Thanks! Forgot to tell you that the signature didn't propagate.
