### ISSUE TITLE
Bitcoin Fun update - Block 679187

### ISSUE THREAD

**Issue by Full-node** [janoside/btc-rpc-explorer#312]
Not sure how to include this into the code but I've typed it out as best I could. 

	{
			type: "blockheight",
			date: "2021-04-14",
			chain: "main",
			blockHeight: 679187,
                        blockHash:"000000000000000000003b1e8108e0d85ad0f698ded94360b27e0ca766682b4f",
			summary: "NYTimes 10/Mar/2021 House Gives Final Approval to Biden's $1.9T Pandemic Relief Bill`",
			alertBodyHtml: "Congress gave final approval on Wednesday to President Biden’s $1.9 trillion stimulus package. This brings us to a total of 9 trillion dollars printed in the last 12 months",
			referenceUrl: "https://www.nytimes.com/live/2021/03/10/us/joe-biden-news"
		},

**Comment by pointbiz** [comment]
This was added to the newest release v3.1.0

**Comment by janoside** [comment]
@Full-node - We were on the same page. Thanks for the suggestion.

https://bitcoinexplorer.org/block/000000000000000000003b1e8108e0d85ad0f698ded94360b27e0ca766682b4f
