### ISSUE TITLE
Mempool summary is not working

### ISSUE THREAD

**Issue by odomdev** [janoside/btc-rpc-explorer#314]
When click run mempool summary it show error as below:

  btcexp:error Error 23947ryfuedge: TypeError: Cannot read property 'txidKey' of undefined, json: {} +0ms
  btcexp:errorVerbose Stack: TypeError: Cannot read property 'txidKey' of undefined
  btcexp:errorVerbose     at /root/explorer/app/api/coreApi.js:1361:36
  btcexp:errorVerbose     at processTicksAndRejections (internal/process/task_queues.js:93:5) +0ms

**Comment by janoside** [comment]
@odomdev I believe this issue should be resolved with the latest update, v3.1.1.

Please reply if you continue to see the problem after updating.
