### ISSUE TITLE
Transaction states is not working

### ISSUE THREAD

**Issue by odomdev** [janoside/btc-rpc-explorer#315]
```
  btcexp:errorVerbose Stack: Error: RpcError: type=errorResponse-03
  btcexp:errorVerbose     at Client.<anonymous> (/root/explorer/app/api/rpcApi.js:505:14)
  btcexp:errorVerbose     at Client.tryCatcher (/root/explorer/node_modules/bluebird/js/release/util.js:16:23)
  btcexp:errorVerbose     at Promise.successAdapter (/root/explorer/node_modules/bluebird/js/release/nodeify.js:23:30)
  btcexp:errorVerbose     at Promise._settlePromise (/root/explorer/node_modules/bluebird/js/release/promise.js:601:21)
  btcexp:errorVerbose     at Promise._settlePromise0 (/root/explorer/node_modules/bluebird/js/release/promise.js:649:10)
```

**Comment by janoside** [comment]
@odomdev I'll need some more information here. Please use the "Bug Report" template for future bug reports. For this report, please let me know what page you're trying to view (the URL), your environment: version of node and Bitcoin Core version.

**Comment by odomdev** [comment]
please help support this issue first https://github.com/janoside/btc-rpc-explorer/issues/313
I cannot search by address. why ? please help to advise.

**Comment by odomdev** [comment]
bitcoin last version.

 btcexp:error Error 283h7ewsede: Error: RpcError: type=errorResponse-03, json: {"userData":{"error":null,"request":{"method":"getchaintxstats","parameters":[3856]},"result":[{"message":"Invalid block count: should be between 0 and the block's height - 1","code":-8,"name":"RpcError"}]}}, userData: [object Object] (json: {"error":null,"request":{"method":"getchaintxstats","parameters":[3856]},"result":[{"message":"Invalid block count: should be between 0 and the block's height - 1","code":-8,"name":"RpcError"}]}) +3ms
  btcexp:errorVerbose Stack: Error: RpcError: type=errorResponse-03
  btcexp:errorVerbose     at Client.<anonymous> (/root/explorer/app/api/rpcApi.js:505:14)
  btcexp:errorVerbose     at Client.tryCatcher (/root/explorer/node_modules/bluebird/js/release/util.js:16:23)
  btcexp:errorVerbose     at Promise.successAdapter (/root/explorer/node_modules/bluebird/js/release/nodeify.js:23:30)
  btcexp:errorVerbose     at Promise._settlePromise (/root/explorer/node_modules/bluebird/js/release/promise.js:601:21)
  btcexp:errorVerbose     at Promise._settlePromise0 (/root/explorer/node_modules/bluebird/js/release/promise.js:649:10)
  btcexp:errorVerbose     at Promise._settlePromises (/root/explorer/node_modules/bluebird/js/release/promise.js:729:18)
  btcexp:errorVerbose     at Promise._fulfill (/root/explorer/node_modules/bluebird/js/release/promise.js:673:18)
  btcexp:errorVerbose     at Promise._resolveCallback (/root/explorer/node_modules/bluebird/js/release/promise.js:466:57)
  btcexp:errorVerbose     at Promise._settlePromiseFromHandler (/root/explorer/node_modules/bluebird/js/release/promise.js:559:17)
  btcexp:errorVerbose     at Promise._settlePromise (/root/explorer/node_modules/bluebird/js/release/promise.js:604:18)
  btcexp:errorVerbose     at Promise._settlePromise0 (/root/explorer/node_modules/bluebird/js/release/promise.js:649:10)
  btcexp:errorVerbose     at Promise._settlePromises (/root/explorer/node_modules/bluebird/js/release/promise.js:729:18)
  btcexp:errorVerbose     at Promise._fulfill (/root/explorer/node_modules/bluebird/js/release/promise.js:673:18)
  btcexp:errorVerbose     at Request._callback (/root/explorer/node_modules/bluebird/js/release/nodeback.js:45:21)
  btcexp:errorVerbose     at Request.self.callback (/root/explorer/node_modules/request/request.js:185:22)
  btcexp:errorVerbose     at Request.emit (events.js:215:7) +3ms

**Comment by janoside** [comment]
@odomdev What network are you running against? mainnet, testnet, regtest, etc?

**Comment by widecoin-project** [comment]
regtest

**Comment by odomdev** [comment]
main net

**Comment by janoside** [comment]
Is your node still downloading blocks?

**Comment by odomdev** [comment]
no full node

**Comment by janoside** [comment]
Sorry, I'm closing this because I just don't have enough information. The error you're referencing indicates that there's an error trying to load transaction stats for the last 3856 blocks but that you don't have that many blocks worth of data to load. Since this conflicts with your reported context (mainnet, fully synced), there's nothing I can do without a lot more contextual data.

I'm sorry for any language barrier that may exist between us, but I'm only able to act on clear bug reports.
