### ISSUE TITLE
Cannot Search block hash last version

### ISSUE THREAD

**Issue by odomdev** [janoside/btc-rpc-explorer#323]
Error when search block hash:

: Error: RpcError: type=errorResponse-03, json: {"userData":{"error":null,"request":{"method":"getrawtransaction","parameters":["xxxxxxxxxx",1]},"result":[{"message":"No such mempool or blockchain transaction. Use gettransaction for wallet transactions.","code":-5,"name":"RpcError"}]}}, userData: [object Object] (json: {"error":null,"request":{"method":"getrawtransaction","parameters":["xxxxxxxxx",1]},"result":[{"message":"No such mempool or blockchain transaction. Use gettransaction for wallet transactions.","code":-5,"name":"RpcError"}]}) +0ms

**Comment by janoside** [comment]
Sorry, but I need you to use the Bug Report template and give more information in the future.

The error shown here relates to looking up a transaction, not a block hash. Please be very specific for future issues.
