### ISSUE TITLE
[Feature] Feature request to add favourite calls in RPC-browser

### ISSUE THREAD

**Issue by mojoX911** [janoside/btc-rpc-explorer#328]
Hi. First of all thank you so much for writing this tool. It made a life of a bitcoin dev easy and fun. I have been using rpc-explorer for a year now and I find this tool very helpful for talking and managing bitcoind in regtest dev mode.

Specially the RPC browser is a killer app.

Just a small feature request, if there can be a separate favourite ( or frequently used) call space in side the rpc-broswer page, where I can add rpc callls I make often that would have been super awesome. :)

Would have done this myself if I was any good in javascript.

Thanks for this wonderful tool again.

**Comment by mojoX911** [comment]
I dont know why it automatically took the `bug` label. Its not a bug and very fine if feature requests are not entertained atm.

**Comment by janoside** [comment]
Great feature idea! This has been implemented in commit 7ecea7d420 and is live on the demo site https://bitcoinexplorer.org. An official release that includes this change will be coming in the near future.
