### ISSUE TITLE
Feature: Taproot signaling diagram 

### ISSUE THREAD

**Issue by pointbiz** [janoside/btc-rpc-explorer#332]
A new type of fun would be to make a Taproot signaling diagram. 

There's logic here
https://gist.github.com/mutatrum/264cfa84af5fc3dc0b107bcb3ba10893

This could be linked from the node details page under soft forks. But also potentially from the home page or fun page.

**Comment by janoside** [comment]
I liked the idea but just didn't have the bandwidth to make it happen and https://taproot.watch did a great job filling this need for the community.

**Comment by pointbiz** [comment]
I also didn't have the bandwidth. I was considering to close this in recent days since taproot signaling is so high now.
