### ISSUE TITLE
1 vulnerability - json-bigint  

### ISSUE THREAD

**Issue by 2pac1** [janoside/btc-rpc-explorer#338]
Hey guys,

 I was upgrading rpc-explorer following https://stadicus.github.io/RaspiBolt/raspibolt_55_explorer.html#upgrade
 
 Once done, I was left with:
 
  === npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Uncontrolled Resource Consumption in json-bigint             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ json-bigint                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.0.0                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ bitcoin-core                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ bitcoin-core > json-bigint                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1690                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 1 high severity vulnerability in 507 scanned packages
  1 vulnerability requires manual review. See the full report for details.
  
  No matter what I did, (audit fix) or npm i json-bigint I couldn't get rid of that msg.
  At the end, I did 
npm view json-bigint veresion

and I saw that I was at 1.0.0 so I wasn't sure why the message in the first place.

Is it possible to mess things up in this process that I tried to update this json-bigint ?
And why is the msg still present if the json-bigint   is at 1.0.0?

Tnx

**Comment by janoside** [comment]
Thanks for reporting this. The issue should be resolved now. A dependency 2 layers down had a vulnerability. The resolution was to fork the dependency and update the 2-layers-down vulnerable dependency. This was done in commit 1503361326.
