### ISSUE TITLE
Show duplicate for mining summary in safari

### ISSUE THREAD

**Issue by odomdev** [janoside/btc-rpc-explorer#339]
Show duplicate miner name in mining summary in safari but chrome and Firefox is ok.

**Comment by janoside** [comment]
There have been some changes to the mining summary please re-test and let me know if you still see the bug. If you do, please include a screenshot. I'm closing this for now, but happy to address if you're still seeing the bug. Thanks.

**Comment by odomdev** [comment]
It is the same issue.Show duplicate miner name in mining summary in safari but chrome and Firefox is ok. ( Data Section)
