### ISSUE TITLE
In Node details: "lack of transaction index" "minRpcVersionNeeded": 0.21.0

### ISSUE THREAD

**Issue by JessieRaspi** [janoside/btc-rpc-explorer#348]
Hi!
This is my first github post. I am not familiar with code. Trying to learn....

I am running the explorer on a Raspiblitz version 1.7.0 and installed Bitcoin Core version 0.21.1 (manually through the update menu of the Raspiblitz).
The explorer is very nice, thanks!.

But there is a red cross at the txindex. I have read the readme, but it seems, that the problem is not with the index on my Raspiblitz.  In my bitcoind the txindex=1. 
After searching, I found this:
"getindexinfo" on the JSON tab in "Node details" gives:
"succes": false
"error": unsupported
"minRpcVersionNeeded": 0.21.0 

Does this mean, that Bitcoincore version 0.21.1 not yet is supported and could that be the reason of missing the transactionindex?

**Comment by janoside** [comment]
Hmmm, I'm trying to figure out what's going on here. I can say that Bitcoin Core v0.21.1 is definitely supported (in fact, that's the version I use for the demo site, which you can see [here](https://bitcoinexplorer.org/node-details)). Regardless, it seems that there was some error with the explorer trying to execute the "getindexinfo" RPC.

Can you try this for me:

* In your local explorer, navigate to "/rpc-browser?method=getindexinfo"
* Click the "Execute" button to run that RPC again
* Let me know what it says and we'll keep looking into this.

Thanks.

**Comment by JessieRaspi** [comment]
Thanks for your reply.
This morning I re- installed the explorer again (last week I uninstalled it) and I get this as a result:
[
    {}
]

In the Jason tab in Node details the same as before:
{
    "success": false,
    "error": "Unsupported",
    "minRpcVersionNeeded": "0.21.0"
}

Somewhere during installation it says, that it could last 7 hours, however I don't see any activity anywhere. Or should I wait?

**Comment by janoside** [comment]
@JessieRaspi Thanks for doing that testing. I think there's good news... seeing that `getindexinfo` is now showing the results we want, I think you'll just need the latest code. I think what's happening is that the first attempt to call `getindexinfo` is failing and the app is saving that result forever. I recently added a code change that, in the event of a failure like this, retries the `getindexinfo` call. As I said, the improved code was added a little while ago, but it hasn't yet been included in an official release. So, depending on your installation method, you can either update to the latest code now, or wait for the next official release (which I hope will be very soon... early next week at the latest).

I'm closing this for now, but if, after updating, you continue to encounter the bug, please let me know here.

Thanks.
