### ISSUE TITLE
Show duplicate miner name ( Data Section) in mining summary

### ISSUE THREAD

**Issue by odomdev** [janoside/btc-rpc-explorer#350]
It is the same issue.Show duplicate miner name ( Data Section) in mining summary in safari but chrome and Firefox is ok.

Please give commit url that you fixed in GitHub to for verification.

**Comment by haykoreis** [comment]
Duplicate of # yes

**Comment by odomdev** [comment]
Hi @janoside any update?

**Comment by janoside** [comment]
Please, when submitting bug reports, include more information...

What version are you running? And, for an issue like this, please include a screenshot to help with diagnosis.

**Comment by janoside** [comment]
Closing this for lack of details. Feel free to add more information if you wish.
