### ISSUE TITLE
F2Pool and binancepool not recognized

### ISSUE THREAD

**Issue by BlackBeltBob** [janoside/btc-rpc-explorer#351]
The mining summary incorrectly attributes blocks that belong to F2Pool and Binancepool among others to "unknown".

**Comment by janoside** [comment]
Please when submitting bug reports, include details about what version you're running. Are you running the latest code (from source)? Or the latest official release?

**Comment by janoside** [comment]
Closing this for lack of info and because I believe, with the latest miner-identification updates, it's likely resolved.
