### ISSUE TITLE
Currency formatting should be fixed

### ISSUE THREAD

**Issue by getsnoopy** [janoside/btc-rpc-explorer#354]
**Describe the bug**

The interface shows the "BTC" currency code after the amount, but [in English](https://www.govinfo.gov/content/pkg/GPO-STYLEMANUAL-2016/pdf/GPO-STYLEMANUAL-2016.pdf#page=252), currency symbols and codes [precede the amount](https://en.wikipedia.org/wiki/ISO_4217#Position_of_ISO_4217_code_in_amounts) (e.g., **USD 5**, **$5**). Bitcoin is a currency, so it should follow the same format (e.g., **BTC 0.01**).

Also, the interface shows the dollar symbol with a space in between, but there should not be one (e.g., **$5** and *not* "$ 5").

**Environment (please complete the following information):**

 - Bitcoin Core / Node Version: 0.16.3
 - NodeJS Version: 10.x
 - Browser: Chrome
 - Code Version / Commit: latest
 
**Configuration file content**

N/A

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to any page that shows an amount in bitcoins.
2. Notice it reads in the format "x BTC".
3. Go to any page that shows an amount in dollars.
4. Notice it reads in the format "$ x".

**Screenshots or Log Output**

![Screenshot 2021-07-22 124700](https://user-images.githubusercontent.com/2997884/126685042-61751119-dfa4-4fbe-b546-f6122af6f70e.png)

**Comment by janoside** [comment]
I'll keep this in mind when making future changes, but most likely won't be implementing exactly as requested here.

**Comment by getsnoopy** [comment]
I'd be happy to create a PR if that helps.
