### ISSUE TITLE
ADD docker BTCEXP_BASE_URL variable to make it work in subfolder

### ISSUE THREAD

**Issue by nforced** [janoside/btc-rpc-explorer#361]
Please consider adding BTCEXP_BASE_URL or similar so the project can work in subfolder. I my case I use proxy to route to /btc.explorer and while it opens the home page but non of the links are working leading to /block instead /btc.explorer/block of  for example
Media files are 404 as well.

**Comment by shesek** [comment]
This already exists, the environment variable is called `BTCEXP_BASEURL`.
