### ISSUE TITLE
Copy icon doesn't work

### ISSUE THREAD

**Issue by wchancao** [janoside/btc-rpc-explorer#373]
When clicking on the Copy icon of a transaction or address, it does not copy anything.
btc-rpc-explorer v3.2.0

**Comment by janoside** [comment]
@wchancao Please also let me know which browser you're using, and if possible, any console output from the browser (in case there are any javascript errors). Thanks!

**Comment by wchancao** [comment]
Kubuntu 20.04
Chromium Version 95.0.4638.69 (Official Build) snap (64-bit)
Firefox 93.0 (64-bit)
Doesnt work in both browsers...
Im not sure what can I show you with console output... if you let me know how to get that info, or useful info i can search it for you!

**Comment by janoside** [comment]
@wchancao The latest code has some changes that may improve this problem. If you can try again with the newest code and let me know what you see that'd be great.

**Comment by wchancao** [comment]
Should i upgrade? Which version it is?

**Comment by janoside** [comment]
Sorry for the confusion - it's not included in an official release yet. Rather it's in the latest code, in the master branch. If you're not accustomed to running from source, no worries - the update (v3.3.0) should be released soon.

**Comment by wchancao** [comment]
Let me test it in another machine, im tired of beta testing apps in my stable mainnet node xD

**Comment by jsarenik** [comment]
I am still experiencing the same issue with latest code on `master`. And for inspiration I found the [copy mechanism in blt-wallet](https://github.com/sereneblue/blt-wallet/blob/master/src/js/script.js#L80) working very well also on an ancient Opera browser on Android 4.2.2 (but working well also on recent browsers like current stable Google Chrome, where also the BitcoinExplorer copy works).
