### ISSUE TITLE
Check balances

### ISSUE THREAD

**Issue by dmitrymaslov99** [janoside/btc-rpc-explorer#375]
Hello. We want to install your browser to receive balances by addresses. Will we be able to do this with the help of your repository, what will be the restrictions and requirements for the server?

**Comment by janoside** [comment]
@dmitrymaslov99 This tool already makes address balances available depending on your configuration. For example, on the demo site, you can see the balance for this address: [bc1qy7ejhj57sgkpecpuxde6lf2j77mpnc3zs0acyh](https://bitcoinexplorer.org/address/bc1qy7ejhj57sgkpecpuxde6lf2j77mpnc3zs0acyh). The demo site has an Electrum Server ([electrs](https://github.com/romanz/electrs)) configured which is required to see address balances.

A future improvement that I hope to add soon will be an API endpoint for seeing address details, but again, this will require you to configure an Electrum Server to see address balances.

Hope this helps.
