### ISSUE TITLE
Change btc-rpc-explorer to local time

### ISSUE THREAD

**Issue by wchancao** [janoside/btc-rpc-explorer#379]
Hello, is there a way to display blocks time on btc-rpc-explorer other than UTC? I would like btc-rpc-explorer to show the time of mined blocks in my local time, i was looking for an option to change in the .env file but didn't find anything.

**Comment by janoside** [comment]
This feature should be coming soon!

**Comment by janoside** [comment]
@wchancao The latest code has timezone display support.
