### ISSUE TITLE
API for mining summary?

### ISSUE THREAD

**Issue by janoside** [janoside/btc-rpc-explorer#383]
### Discussed in https://github.com/janoside/btc-rpc-explorer/discussions/374

<div type='discussions-op-text'>

<sup>Originally posted by **secondl1ght** October 12, 2021</sup>
Is there an API for the mining summary section? Where does it pull that data from? I have an idea for a website that I want to build that would rely on using an API to see which mining pool mined each block in real time.</div>

**Comment by Chalo0** [comment]
`do it `

**Comment by janoside** [comment]
It has been [done](https://bitcoinexplorer.org/api/mining/miner-summary?since=1d).
