### ISSUE TITLE
Bitcoin Core "txindex=1" still needed with BTCEXP_ELECTRUM_TXINDEX?

### ISSUE THREAD

**Issue by Stadicus** [janoside/btc-rpc-explorer#385]
I'm about to update the setup instructions for your great project in my RaspiBolt guide:   
https://github.com/raspibolt/raspibolt/pull/786

I'm still recommending to use Bitcoin Core with `txindex=1`, as I couldn't find information whether the new `BTCEXP_ELECTRUM_TXINDEX` option is a full replacement.

Questions: 

* Can `txindex` be disabled in Bitcoin Core when `BTCEXP_ELECTRUM_TXINDEX` is enabled with Electrs?
* Are there tradeoffs between the two methods, e.g. in regards to speed or information available in the block explorer?

**Comment by janoside** [comment]
@Stadicus Good questions... I use `bitcoind`'s txindex and haven't experimented with using `electrs`' version, so the default you're advocating seems like a good one. But...

@shesek @Kixunil can either of you weigh in on these questions?

**Comment by janoside** [comment]
Added some documentation with this explanation in `.env-sample` for future reference. Closing since I think the key questions have been answered.
