### ISSUE TITLE
How to display the address of p2pk?

### ISSUE THREAD

**Issue by happyqian** [janoside/btc-rpc-explorer#389]
blockchain.info can be displayed. I want to display the p2pk address as a normal address

**Comment by janoside** [comment]
It's actually not strictly correct to encode `p2pk` scripts as addresses. For further explanation, see [here](https://github.com/janoside/btc-rpc-explorer/issues/129#issuecomment-816928337).

I can see some value in displaying as addresses anyway for simplicity's sake, but given the educational philosophy of this project I'm going to opt to not do anything that's not strictly correct. Thanks for bringing this up though.

**Comment by happyqian** [comment]
thank you
