### ISSUE TITLE
this is an electrumx problem related:

### ISSUE THREAD

**Issue by gabbieianatangan05** [janoside/btc-rpc-explorer#391]
this is an electrumx problem related:
electrumx doesn't respond  when response is too large (when there're too many txs, for example).
Look at this:
[https://github.com/kyuupichan/electrumx/issues/348](https://github.com/kyuupichan/electrumx/issues/348)
I hope they will solve this issue, sooner or later

_Originally posted by @buttha in https://github.com/janoside/btc-rpc-explorer/issues/67#issuecomment-429263463_

**Comment by janoside** [comment]
Sorry, nothing to act on here.
