### ISSUE TITLE
Generalize RPC API to support other coins

### ISSUE THREAD

**Issue by janoside** [janoside/btc-rpc-explorer#4]
In doing so, try to isolate BTC-specific code to more easily support other currencies in the future.

**Comment by dutchakdev** [comment]
I try change bitcoin adapter to litecoin, but have many errors with commands like getblockchaininfo, getnetworkinfo etc.

**Comment by janoside** [comment]
@dutchakdev After commit 70b28ff please try again. You can modify env.js to set "coin=LTC" (instead of the default "coin=BTC") and connect to your Litecoin node via RPC. Please let me know if you have problems.

**Comment by nicebbs** [comment]
TransactionsTrust Note
No address API is configured. See the example configuration file for help setting up an address API if desired.

**Comment by janoside** [comment]
@nicebbs This is referring to the `BTCEXP_ADDRESS_API` environment variable. You can set this to any of the values indicated in `.env-sample`. Note that each option has different privacy implications (running your own ElectrumX server will be more private than using any public website/API).
