### ISSUE TITLE
DnS probe 
 404 error 

### ISSUE THREAD

**Issue by erc20pixel** [janoside/btc-rpc-explorer#405]
**Describe the bug**

**Environment (please complete the following information):**

 - Bitcoin Core / Node Version [e.g. 0.16.3]
 - NodeJS Version [e.g. 9.x]
 - Code Version / Commit [e.g. ab6cde8]
 - Installation Method [e.g. "npm" or "source code"]
 
**Configuration file content**

Please include the content from the following files. **BE SURE TO MODIFY YOUR CREDENTIALS BEFORE SUBMITTING!!!**
 - bitcoin.conf
 - Your btc-rpc-explorer environment configuration (either `$WORKING_DIR/.env` or `~/.config/btc-rpc-explorer.env`)

**To Reproduce**

**Screenshots or Log Output**

If applicable, add screenshots or log output to help explain your problem.

**Additional context**

**Comment by janoside** [comment]
Please only submit bug reports with detailed, specific information.
