### ISSUE TITLE
Slows down over time.

### ISSUE THREAD

**Issue by SebastianD20** [janoside/btc-rpc-explorer#418]
Not necessarily a bug, but might be. I have it setup and working correctly. Over time it seems that it slows down a lot. I have a custom python script that monitors the blockchain and requests pages from the site. In the first minute it can do about 300, then slowly goes down from there. Every time I restart it its at about 10-20 per second then slowly slows down. I'm trying to learn about this stuff, so not entirely sure what the issue may be. I have slow mode turned off and using 127.0.0.1 as the ip addresses, using btcd tindex. On ubuntu 20.

**Comment by SebastianD20** [comment]
Running a test, its limited to almost 1 second per search

**Comment by blackdimund** [comment]
if we were to implement Fulcrum instead of electrumx/electrum it would by faster by multitude because it stores more data and uses c++ as opposed to python https://sparrowwallet.com/docs/server-performance.html

**Comment by janoside** [comment]
Cleaning up old issues. If you're still having this problem using the latest code (3.4-beta or greater), feel free to reply.
