### ISSUE TITLE
plotting the chart

### ISSUE THREAD

**Issue by cyberpay** [janoside/btc-rpc-explorer#42]
good work and keep it coming wondering if there is a way to plot chart with RPC and php array data, would be an amazing addon to yours explorer

**Comment by janoside** [comment]
Hi @cyberpay - Please explain in more detail what you're requesting. I'm not understanding yet.

**Comment by cyberpay** [comment]
Chart for block difficulty, price, network hash etc. Network nodes over a map and other cosmetic stuff.

**Comment by janoside** [comment]
I see. Thanks for the details. I like the ideas though they'll be lower priority than some other things, mostly because several of them are "external" to the node's data (the blockchain).

**Comment by zooooooooo** [comment]
@janoside not sure if you were looking to put a price chart in this, but if so check out the following API

https://api.coindesk.com/v1/bpi/historical/close.json?start=2010-07-17&end=2019-05-17

**Comment by pointbiz** [comment]
The block difficulty chart already exists. And hash rate is basically the same thing. 

I feel a price chart is not necessary for a block explorer. 

Does this issue still have an open task?
