### ISSUE TITLE
tx inventory: Accomodate RPC change for Bitcoin Core 24

### ISSUE THREAD

**Issue by jsarenik** [janoside/btc-rpc-explorer#431]
**Describe the new feature or enhancement**

According to bitcoin/bitcoin#21160, btc-rpc-explorer will need some changes. Just making a note for now.

**Additional context**

Bictoin Core 23.0rc2 works fine even though one related part was merged already  (bitcoin/bitcoin@e057e01b7, bitcoin/bitcoin#21162).

**Comment by jsarenik** [comment]
This will be needed for next Bitcoin Core release (24) and is already present on 23.99 (`master`).

**Comment by janoside** [comment]
@jsarenik We're past v24 release. Are we good on this?
