### ISSUE TITLE
explorer needs restart to correct the current difficulty percentage

### ISSUE THREAD

**Issue by jsarenik** [janoside/btc-rpc-explorer#444]
**Describe the bug**

Just describing what I noticed, no ideas for a fix yet (other than restarting the `btc-rpc-explorer`).

After the difficulty change to period 365, I see `The current difficulty is --4.89% lower than the All-Time High.`, a double dash (minus) sign there. And it is exactly the percentage by which the current difficulty was raised compared to previous (which was also ATH).

On my Bitcoin Explorer, it was enough to restart it. No change in code. After the restart it shows everything correctly: https://be.anyone.eu.org/

![difficulty-bad](https://user-images.githubusercontent.com/244565/167807137-3588ff53-4143-4212-8146-4d62da89a50e.png)

**Comment by jsarenik** [comment]
After restart (on https://be.anyone.eu.org/) it looks like this:

![difficulty-good](https://user-images.githubusercontent.com/244565/167809453-d40c0418-3334-4db1-acf4-d9191c4adb48.png)

**Comment by janoside** [comment]
Thanks for reporting. Fixed in 48df5b5a925006ca60e5231a7d08a2ece80226d5
