### ISSUE TITLE
Bitcoin Quotes page repeats two times two quotes from Satoshi

### ISSUE THREAD

**Issue by tadeubas** [janoside/btc-rpc-explorer#455]
**Describe the bug**

Bitcoin Quotes show two times the quotes from Satoshi (I know they are awesome, but it has to appear only one time like all other quotes 😝):

```
"I'm sure that in 20 years there will either be very large transaction volume or no volume."

"Lost coins only make everyone else's coins worth slightly more. Think of it as a donation to everyone."
```

**Environment (please complete the following information):**

https://bitcoinexplorer.org/quotes

**Screenshots or Log Output**

![image](https://user-images.githubusercontent.com/5518496/176886207-3f33decc-57d2-4db7-9b74-71a720edaba9.png)

![image](https://user-images.githubusercontent.com/5518496/176886295-a3d2ef1c-a1cc-4264-bdf3-f685b6d4ff23.png)

**Comment by janoside** [comment]
Closing. See comment on #459
