### ISSUE TITLE
Peers page don't show map from mapbox.com

### ISSUE THREAD

**Issue by tadeubas** [janoside/btc-rpc-explorer#456]
**Describe the bug**

Peers page don't show map from `api.mapbox.com` because an **access_token value is missing**!

**Environment (please complete the following information):**

https://bitcoinexplorer.org/peers

**Screenshots or Log Output**

![image](https://user-images.githubusercontent.com/5518496/176938547-69ed36cc-679f-457d-a780-b4809584ae4a.png)

**Comment by jsarenik** [comment]
This is intentional. Everyone should rather use their own `access_token` for the mapbox API.

**Comment by tadeubas** [comment]
Even on bitcoinexplorer.org demo? If so, you can close this issue, thx!

**Comment by jsarenik** [comment]
@tadeubas I see your point, and even think it should work there because `BTCEXP_MAPBOX_APIKEY` is listed in [Demo site settings](https://github.com/janoside/btc-rpc-explorer#demo-site-settings).

@janoside Is mapbox supposed to work on bitcoinexplorer.org instance?

**Comment by janoside** [comment]
@jsarenik Yes, I had previously configured the demo site to enable the peers map and during a server transition I didn't copy over my API key. Thanks all for catching this. It also turned out there was another bug associated with the peers map, which was fixed in commit 6bfc0876f3.

Thanks.
