### ISSUE TITLE
error loading Browse Mempool page

### ISSUE THREAD

**Issue by tone-control** [janoside/btc-rpc-explorer#457]
**Describe the bug**

The Browse Mempool page loads with an error message, "[DecimalError] Invalid argument: undefined."  The error message points to "var feeRate = New."

**Environment (please complete the following information):**

 - Operating system:  Ubuntu server 20.04.4 LTS
 - Bitcoin Core Version: v23.0.0
 - electrs v0.9.7
 - NodeJS Version: v16.15.1
 - Browser Firefox: 102.0 snap for Ubuntu
 - Code Version: v3.3.0
 - Installation Method: "npm"
 
**Configuration file content**

Please include the content from the following files. **BE SURE TO MODIFY YOUR CREDENTIALS BEFORE SUBMITTING!!!**

bitcoin.conf start

# Bitcoin daemon
server=1
txindex=1

# Network
listen=1
listenonion=1
proxy=127.0.0.1:[port]
bind=127.0.0.1

# Connections
rpcauth= [removed for this bug report]
zmqpubrawblock=tcp://127.0.0.1:[port]
zmqpubrawtx=tcp://127.0.0.1:[port]
whitelist=download@127.0.0.1          # for Electrs

bitcoin.conf end

btc-rpc-explorer environment configuration:  see attached 
[btcrpcexplorer_env_fileforbugreport.txt](https://github.com/janoside/btc-rpc-explorer/files/9065757/btcrpcexplorer_env_fileforbugreport.txt)

**To Reproduce**

1. Go to https://[ipaddress]:[port]
2. Click on Tools drop-down menu
3. Select Browse Mempool
4. See screenshot

**Screenshots or Log Output**

![image](https://user-images.githubusercontent.com/108843644/177825406-edcb14bb-14d0-4ac5-801e-a1a0cad2ede4.png)

If applicable, add screenshots or log output to help explain your problem.

**Additional context**

**Comment by ketominer** [comment]
Up - same here, affecting all our users

**Comment by janoside** [comment]
This is fixed in master. Working toward a v3.4.0 release soon.
