### ISSUE TITLE
Unconfirmed transaction incorrectly displayed

### ISSUE THREAD

**Issue by Dehumanizer77** [janoside/btc-rpc-explorer#466]
**Describe the bug**

When there is an unconfirmed transaction in the address view, the lock icon shows the estimated block height for confirmation as the number of confirmations instead of "unconfirmed". See the attached screenshot. 

**Environment (please complete the following information):**

 - Bitcoin Core 23.0
 - NodeJS Version 16.14.2
 - Browser Firefox 104.0.1
 - Code Version / Commit 3.3.0 / 3c46e97434
 - Installation Method - not really sure, installed in RaspiBlitz by their installation script
 
**Configuration file content**

Please include the content from the following files. **BE SURE TO MODIFY YOUR CREDENTIALS BEFORE SUBMITTING!!!**

**To Reproduce**

1. Go to an address containing unconfirmed transaction
2. See the lock icon which should say "unconfirmed"

**Screenshots or Log Output**

If applicable, add screenshots or log output to help explain your problem.
![unconfirmed](https://user-images.githubusercontent.com/1876451/188123655-2d910a2f-9258-46f4-a0a1-67f7ed0b9dff.png)

**Additional context**

**Comment by Dehumanizer77** [comment]
Here are the config files
[bitcoin.conf.txt](https://github.com/janoside/btc-rpc-explorer/files/9477271/bitcoin.conf.txt)
[btc-rpc-explorer.env.txt](https://github.com/janoside/btc-rpc-explorer/files/9477272/btc-rpc-explorer.env.txt)

**Comment by jsarenik** [comment]
I am unable to reproduce this on current master btc-rpc-explorer also with an ElectrumX server. There were many commits on master branch since 3c46e97 so I guess one of them might have fixed this.

**Comment by Dehumanizer77** [comment]
Ok, I guess I'll have to wait for the next raspiblitz release or upgrade it manually.
