### ISSUE TITLE
new fun transaction

### ISSUE THREAD

**Issue by a5an0** [janoside/btc-rpc-explorer#477]
transaction 7393096d97bfee8660f4100ffd61874d62f9a65de9fb6acf740c4c386990ef73 was a 998-out-of-999 multisig taproot transaction that broke LND. 

context: 
https://twitter.com/brqgoo/status/1579216353780957185
https://github.com/lightningnetwork/lnd/issues/7002

**Comment by VajraOfIndra** [comment]
💯
