### ISSUE TITLE
[Feature] Expose mempool size and total fees in api

### ISSUE THREAD

**Issue by ExperiBass** [janoside/btc-rpc-explorer#488]
**Describe the new feature or enhancement**

It would be nice to have the total tx fees and size exposed alongside the count in the api.

**Additional context**

I've been messing around with displaying chain stats on my devices, and I want to display the current mempool size and the total fees. I've settled with mempool.space to get those stats, but i prefer this api.

**Comment by pointbiz** [comment]
Does this pull request satisfy your feature request?

**Comment by ExperiBass** [comment]
yep, thanks!

**Comment by janoside** [comment]
Merged.
