### ISSUE TITLE
Error ExpressUncaughtError (shared-mixins.pug)

### ISSUE THREAD

**Issue by Francisco-DAnconia** [janoside/btc-rpc-explorer#489]
Error text displayed in browser when selecting "Browse Mempool"

 - Bitcoin Core  v23.0.0
 - NodeJS Version 18.11.0
 - Browser Firefox
 - Code Version / Commit Version 3.3.0 2021-12-07
 - Installation Method NPM
 - Electrum server is Fulcrum
 
export BTCEXP_BITCOIND_HOST=127.0.0.1
export BTCEXP_BITCOIND_PORT=#####
export BTCEXP_PORT=#####
export BTCEXP_UI_THEME=dark
export BTCEXP_SLOW_DEVICE_MODE=false
export BTCEXP_BITCOIND_PORT=#####
export BTCEXP_ADDRESS_API=electrum
export BTCEXP_ELECTRUM_SERVERS=tcp:127.0.0.1:#####

1. Go to 'Browse Mempool'
2. See error

![Screen Shot 2022-11-18 at 10 11 29 AM](https://user-images.githubusercontent.com/33098368/202774737-30de1b11-d701-461b-bf70-fe83683c4ac4.png)
[RPC error Mempool.pdf](https://github.com/janoside/btc-rpc-explorer/files/10043849/RPC.error.Mempool.pdf)

**Comment by janoside** [comment]
Cleaning up old issues. If you're still having this problem using the latest code (3.4-beta or greater), feel free to reply.

**Comment by Francisco-DAnconia** [comment]
> Cleaning up old issues. If you're still having this problem using the latest code (3.4-beta or greater), feel free to reply.

I just checked. This problem does NOT occur in 3.4.0 Beta 1. However, any type of search I attempt (e.g. block, transaction, address) results in an error.

invalid csrf token.

Please advise (known, new bug, more info, etc).

**Comment by janoside** [comment]
@Francisco-DAnconia That's an existing issue: https://github.com/janoside/btc-rpc-explorer/issues/524 I'm struggling to figure it out. I'm not hitting the error locally (on my dev instance), but I do get it on the public demo site. Still investigating. Watch that issue for updates.
