### ISSUE TITLE
Socket Hangups for RPC calls

### ISSUE THREAD

**Issue by agustinkassis** [janoside/btc-rpc-explorer#51]
While trying to access http://localhost:8332
I get the following error and unable to access the website through browser.

> Error for RPC command 'getchaintxstats': Error: socket hang up
> Error for RPC command 'getchaintxstats': Error: socket hang up
> Error for RPC command 'getblockchaininfo': Error: socket hang up
> Unhandled Rejection at: Promise Promise {
>   <rejected> { Error: socket hang up
>     at createHangUpError (_http_client.js:322:15)
>     at Socket.socketOnEnd (_http_client.js:425:23)
>     at Socket.emit (events.js:187:15)
>     at endReadableNT (_stream_readable.js:1085:12)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
>   cause:
>    { Error: socket hang up

**Comment by janoside** [comment]
@agustinkassis This is likely a RPC API version issue. This tool does not identify what version of node it's connected to and therefore doesn't tailor itself to RPC API differences between versions. May I ask: what version of Bitcoin Core are you running?

**Comment by agustinkassis** [comment]
It was verison 1.6.2, recently updated to 1.6.3. Those API commands are available.

**Comment by ConanDW** [comment]
Having this problem as well.

**Comment by janoside** [comment]
@agustinkassis @ConanDW It's been a long time, so not sure if you're still interested or working on getting this tool configured, but if so, I have another question: is your node configured to accept RPC requests from the host running btc-rpc-explorer? This would be done via "rpcallowip" configurations for your node.

Also, I'm assuming that your node version was 0.16.2 and upgraded to 0.16.3?

**Comment by janoside** [comment]
Happy to reopen if I hear back.

**Comment by cypcz** [comment]
Hello @janoside, I see it's been a few years since this issue was reported but I was "lucky" enough to run into it, too.  I'm using Node v18.16.0 LTS with BTC Core 24.0.1. Not really sure what to do, I'll try to downgrade to Node 16 but other than that I'm out of ideas. Wanted to mention it here if anyone else ran into it on those versions.
