### ISSUE TITLE
[Error 32ugegdfsde: no auth mechanism defined] Please help me figure this error out 

### ISSUE THREAD

**Issue by 11100010** [janoside/btc-rpc-explorer#513]
**Describe the bug**
[Error RpcError-001: no auth mechanism defined]
[Error 32ugegdfsde: no auth mechanism defined]

**Environment (please complete the following information):**

 - Bitcoin Core / Node Version [v22.0.0]
 - NodeJS Version [v18.11.0]
 - Browser [Version 110.0.5481.177 (Official Build) (arm64)]
 - Code Version / Commit [v3.3.0]
 - Installation Method [npm]
 
**Configuration file content**

**Screenshots or Log Output**
**ERROR**
![Screen Shot 2023-02-24 at 03 06 55](https://user-images.githubusercontent.com/87060114/221018609-87d3354b-5a8a-4e39-a030-7fb7382b49a0.png)

**bitcoin.conf**
![Screen Shot 2023-02-24 at 03 11 45](https://user-images.githubusercontent.com/87060114/221019531-04df5be1-3737-40f0-9257-0241c50193b7.png)

**btc-rpc-explorer.env**
![Screen Shot 2023-02-24 at 03 11 01](https://user-images.githubusercontent.com/87060114/221019664-ac6fad88-5b1a-4f13-9c1e-ccbc15311a08.png)

**http://127.0.0.1:3002/**
![Screen Shot 2023-02-24 at 03 14 18](https://user-images.githubusercontent.com/87060114/221019900-4ca3b9a2-040e-41d6-b39b-552f4b131687.png)

**Comment by ExperiBass** [comment]
looks like you forgot to uncomment the auth lines. remove the `#` at the beginning of the cookie line.

**Comment by 11100010** [comment]
> looks like you forgot to uncomment the auth lines. remove the `#` at the beginning of the cookie line.

Yep, my silly mistake, thank you^^
