### ISSUE TITLE
Add RPC API version management

### ISSUE THREAD

**Issue by janoside** [janoside/btc-rpc-explorer#53]
App currently does not identify what version of node software it's connected to and therefore doesn't tailor itself to different versions of the RPC API. This should be changed or at least noted somehow.

**Comment by daygle** [comment]
Just wondering if there was an update for this enhancement? I have been patiently waiting :)

**Comment by janoside** [comment]
This has been addressed in v2.0.0 (and is in active use for features that use `getblockstats`, which required bitcoind v0.17.0+).

@daygle It's been a while but is there a specific reason you were waiting for this enhancement?

I'm closing this issue, but please feel free to respond here.
