### ISSUE TITLE
Add detailed address info

### ISSUE THREAD

**Issue by Overtorment** [janoside/btc-rpc-explorer#54]
Since bitcoind cant provide info on arbitrary address, you can rely on electrumx indexes (also works off bitcoind).
Here's an example: https://github.com/Overtorment/nodejs-electrum-http

**Comment by janoside** [comment]
@Overtorment Thanks for this. There's another issue, #8, that is seeking the same goal you're mentioning here. I'm liking the ElectrumX solution and will be working to implement that idea soon. I've starred the repository you linked and will use it for reference. I'm closing this but feel free to add any additional thoughts to #8. Thanks for the suggestion.
