### ISSUE TITLE
Add http rest API

### ISSUE THREAD

**Issue by Overtorment** [janoside/btc-rpc-explorer#55]
So this explorer can turn into pluggable backend for light wallet clients (once additional indexing by address is added)

**Comment by cyborg0922** [comment]
Do these explorers have the ability to request e.g. balance / transaction data with http requests yet?
e.g. https://bsvexplorer.io/api/addr/...address goes here... ?

Or to more importantly broadcast transactions via an http rest api?

**Comment by got3nks** [comment]
REST API would be great, +1

**Comment by mortalys** [comment]
Was the feature implemented ? Would be great to access JSON requests on page without need to go on the tabs

**Comment by fellowworldcitizen** [comment]
+1! JSON is already there! Could be as simple as adding  json/1 to URL. Then show json as: [{"tabname1":json1},{"tabname2":json2}].

**Comment by pointbiz** [comment]
There's already an API that's not documented.
See the routes/ApiRouter.js
Here's an example. 
https://explorer.btc21.org/api/blocks-by-height/1

So, I presume the task would be to add more routes to that ApiRouter that reuse some logic from the routes that return HTML but instead return JSON.

And a task to make the ApI documentation.

**Comment by pointbiz** [comment]
Here's an API for a raw transaction:
https://explorer.btc21.org/api/raw-tx-with-inputs/b780b77040647f7a8196a72249ce70d04fb0964fa11dec2e53564d251d0ed5ab

**Comment by janoside** [comment]
We have an API, finally! See it on the demo site at https://bitcoinexplorer.org/api/docs

This is available now for source installations and will be included in the next release coming soon.
