### ISSUE TITLE
And I missed this warning:

### ISSUE THREAD

**Issue by Dezzj** [janoside/btc-rpc-explorer#560]
And I missed this warning:

`Failed to load address 16oZp3C27SWKb7wrqKPXTtRtxCW86sUVao (TypeError: Promise.all(...).catch(...).finally is not a function)`

_Originally posted by @HamishMacEwan in https://github.com/janoside/btc-rpc-explorer/issues/68#issuecomment-431543576_

**Comment by janoside** [comment]
Sorry, need more clear information to act on this.
