### ISSUE TITLE
Add CHF as local currency

### ISSUE THREAD

**Issue by Deekee62** [janoside/btc-rpc-explorer#563]
Add CHF (Swiss franc) 

A clear description of the new feature or enhancement. Perhaps a description of how it functions, how it looks, where it "lives", etc.

Add  to local currencies so it can be selected via BTCEXP_LOCAL_CURRENCY in .env 

**Additional context**

Add any other context about the value of the new feature.

**Comment by janoside** [comment]
I'm happy to accept PRs that accomplish this, but not going to keep an open issue for it. The fiat currencies supported are simply those that are made available via the price API used. No special attention was given to supporting what's currently here.
