### ISSUE TITLE
How do I improve performance?

### ISSUE THREAD

**Issue by 3ntranced** [janoside/btc-rpc-explorer#577]
**Describe the new feature or enhancement**

https://bitcoinexplorer.org/ returns bc1qxhmdufsvnuaaaer4ynz88fspdsxq2h9e9cetdj within seconds. But my instance doesnt times out after about 8 minutes. Are you using electrs for addresses? What do I need to do to get improvement in performance?

**Comment by 3ntranced** [comment]
which electrs, electrumx does the public website use?

**Comment by Thierry61** [comment]
> which electrs, electrumx does https://bitcoinexplorer.org/ use?

I guess the explorer is [NBXplorer](https://github.com/dgarage/NBXplorer) because when displaying the [list of peers]( https://bitcoinexplorer.org/peers) there is a node with this unusual node subversion string: NBXplorer--2085976709189660429

**Comment by pointbiz** [comment]
I'm also interested in any advice here. I'm seeing similar issues with my btc-rpc-explorer instances. One is using ElectrumX the other uses ElectRS. Both take minutes to return an address that returns in seconds with bitcoinexplorer.org 

I've tried to turn on all the caching. In memory and disk. Didn't improve the situation.

**Comment by pabpas** [comment]
You want a fast electrumx replacement and fulcrum is the fastest: https://github.com/cculianu/Fulcrum

I just tried the OP address on a low end machine and took seconds.

**Comment by 3ntranced** [comment]
i think blockstream electrs esplora has the best performance

**Comment by janoside** [comment]
BitcoinExplorer.org currently uses fulcrum.
