### ISSUE TITLE
Load cookie auth from daemon data dir

### ISSUE THREAD

**Issue by Kukks** [janoside/btc-rpc-explorer#59]
Allow us to specify the data dir of the coin so that you can retrieve the cookie auth. This complements docker support through a simple volume share. :)

FYI, trying to integrate this as an optional service in [btcpayserver](https://github.com/btcpayserver/btcpayserver-docker).  :)

**Comment by janoside** [comment]
@Kukks It's been a long time, but this issue should be resolved now. A flurry of recent changes to the method of configuring this app have dealt with cookie auth. I see that the related btcpayserver issue was closed, but I thought I'd let you know anyway, in case you'd like to pursue this any more.

Using the current configuration method either a `.env` file with the `BTCEXP_BITCOIND_COOKIE` value set to the filepath of the cookie, or an environment variable of the same format would get you there.

I'm happy to offer any more help on this. Either way, I'm loving the BTCPayServer project and what it represents. Thanks for all your work there!
