### ISSUE TITLE
It is possible to become the RPC for unisat wallet service?

### ISSUE THREAD

**Issue by 9cat** [janoside/btc-rpc-explorer#603]
It is possible to become the RPC for unisat wallet service?

for the wallet part:

export const OPENAPI_URL_MAINNET = 'https://api.unisat.io/wallet-v4';
export const OPENAPI_URL_TESTNET = 'https://api-testnet.unisat.io/wallet-v4';

is it possible to using this project to establish its selfhost api service?

**Comment by janoside** [comment]
Sorry, don't know anything about the OpenSat.io project. But, this explorer *can* serve as a self-hosted API for Bitcoin Core-based node software. Beyond that, you'll need to just try and see.
