### ISSUE TITLE
tiny-secp256k1 | RangeError: Source is too large

### ISSUE THREAD

**Issue by zachchan105** [janoside/btc-rpc-explorer#604]
When running npm start, I encounter a fatal error that seems to revolve around tiny-secp256k1

![image](https://github.com/janoside/btc-rpc-explorer/assets/37559274/4696644b-8d76-4bce-a958-932a4400752b)

 - Master [2e3797e](https://github.com/janoside/btc-rpc-explorer/commit/2e3797ef86da1012fb4ced53e27d0dc1e43db585)
 - Source code

**To Reproduce**

1. Clone repo
2. npm install
3. npm start

Ubuntu 20.04

**Comment by janoside** [comment]
@zachchan105 I'm not sure on this one, but it seems to be an issue with this dependency. I'd search for that error online relating to the dependency and see if there are any workarounds. Sorry I don't have more on this.
