### ISSUE TITLE
btc-rpc-explorer now ships with zHIVErbox distribution by default

### ISSUE THREAD

**Issue by zciendor** [janoside/btc-rpc-explorer#63]
We added a custom `installer script` which helps not-so-tech-savvy users installing `btc-rpc-explorer` on their [zHIVErbox](https://github.com/zhiverbox/armbian-userpatches):

- https://github.com/zhiverbox/armbian-userpatches/blob/master/overlay/opt/zhiverbox/scripts/install/51_install-btc-rpc-explorer.sh

- https://github.com/zhiverbox/armbian-userpatches/blob/master/overlay/opt/zhiverbox/scripts/btc-rpc-explorer/btc-rpc-explorer

Feel free to get inspired and reuse/adopt for other systems as well!

Design choices:
- Cookie-based RPC authentication with `bitcoind`
- Easily switch between `mainnet` / `testnet` with just one argument
- The currently lacking user-authentication in `btc-rpc-explorer` is compensated with `SSH TCP Port Forwarding` instead
- `btc-rpc-explorer` is not running all the time, but only started together with the establishment of the SSH-port-forwarding tunnel

**Comment by janoside** [comment]
@zciendor Thanks for this
