### ISSUE TITLE
RPC blacklist - longer by default?

### ISSUE THREAD

**Issue by sangaman** [janoside/btc-rpc-explorer#65]
I was surprised to see that the rpc terminal allows all sorts of sensitive calls to execute by default, such as `getbalance`, `sendtoaddress`, etc... I would expect that by default the permitted rpc calls would be limited to strictly those of a general informational nature. As is it seems like a security vulnerability - anybody who gets to the explorer could theoretically empty all funds from the wallet unless the user deliberately added the sending rpc calls to the blacklist.

I'd be happy to open a PR for this if you agree with the premise, thanks.

**Comment by janoside** [comment]
Sure, I'm happy for a longer default blacklist and agree with the principle behind it. Thanks.

**Comment by buttha** [comment]
just another question: is it possibile to disable (optionally) rpc completely?
I don't like to expose them on internet, so actually my virtual host is password protected

**Comment by janoside** [comment]
@buttha Yes, sorta. If you run with "demoSite" set to false (in app/config.js), then the regex "ipWhitelistForRpcCommands" (also in app/config.js) will be used to limit access to RPC browser/terminal. Hope this answers your question.

**Comment by buttha** [comment]
yes, thank you!
