### ISSUE TITLE
QR Code Image Broken in Address Display

### ISSUE THREAD

**Issue by HamishMacEwan** [janoside/btc-rpc-explorer#68]
In the Summary panel, in the Details tab, the "QR Code" image is absent, and what appears to be an alt-text is visible.

HTML source
`<div class="summary-split-table-label">QR Code</div><div class="summary-split-table-content monospace"><img alt="16oZp3C27SWKb7wrqKPXTtRtxCW86sUVao" style="border: solid 1px #ccc;"></div>`

**Comment by HamishMacEwan** [comment]
And I missed this warning:

`Failed to load address 16oZp3C27SWKb7wrqKPXTtRtxCW86sUVao (TypeError: Promise.all(...).catch(...).finally is not a function)`

**Comment by HamishMacEwan** [comment]
Thanks for the response.

Which log specifically would that be?

**Comment by HamishMacEwan** [comment]
This is what I see on the terminal:

```
GET /address/1BmP5ahdSEXyf8Uqso9uVJtZwn6LSpZGSy 200 388.906 ms - 16723
GET /css/radial-progress.css 304 0.694 ms - -
GET /css/styling.css 304 0.435 ms - -
GET /img/logo/btc.svg 304 0.560 ms - -
GET /img/logo/ltc.svg 304 0.478 ms - -
GET /img/logo/lightning.svg 304 0.594 ms - -
GET /address/17KNVynHreYDUgMp55dQTUrAFVDU2LQi31 200 518.367 ms - 16723
GET /css/radial-progress.css 304 1.075 ms - -
GET /css/styling.css 304 0.636 ms - -
GET /img/logo/btc.svg 304 0.841 ms - -
GET /img/logo/ltc.svg 304 0.686 ms - -
GET /img/logo/lightning.svg 304 0.795 ms - -
```

**Comment by janoside** [comment]
Hmmm, thanks for checking that. Ok, I'm seeing the issue a bit more clearly now. The error in your second comment is a nice bit of evidence of the cause (I should have paid more attention to that previously). I believe Promise.all().catch().finally might require a newer version of node than you're running. Any chance you can update your node version and check this issue again?

**Comment by HamishMacEwan** [comment]
My node version is:

```
$ node --version
v9.11.2
```
Which looks pretty current.  I tried upgrading it with this result:
```
# apt-get upgrade nodejs
Reading package lists... Done
Building dependency tree
Reading state information... Done
nodejs is already the newest version (9.11.2-1nodesource1).
```

**Comment by janoside** [comment]
@HamishMacEwan Thanks for trying that. I tried a workaround to go at this another way. If you can try it out and let me know what happens I'd appreciate it.

**Comment by HamishMacEwan** [comment]
![1hk4dhtyfs9tfbju9na3w9wx4vfjdfywzm capture](https://user-images.githubusercontent.com/388061/48648442-327ceb00-ea54-11e8-92c9-792b766a45c3.JPG)

Thank you!
