### ISSUE TITLE
Separate local config from source control

### ISSUE THREAD

**Issue by sangaman** [janoside/btc-rpc-explorer#72]
It would be nice for the config options to be in a separate file that's not checked into git. It would make updating easier so that edits to `config.js` don't conflict or get overwritten when pulling the latest commits.

**Comment by janoside** [comment]
Completely agree - been annoyed by this lately too. I'm planning to integrate the npm "config" package: https://www.npmjs.com/package/config

My lack of experience in the node space is probably showing through my weak solution for configs, so if you have any opinion against my idea to integrate "config" I'd be happy to hear them. Otherwise, stay tuned!

**Comment by sangaman** [comment]
I can possibly work on making a PR for this in the next week or two... I think that package is probably overkill. I'm a fan of [toml](https://github.com/toml-lang/toml) config files but I think probably the simplest approach would be just to rename config.js and credentials.js to config-sample.js and credentials-sample.js (and add the original file names to .gitignore). Then in the README you can instruct users to copy and rename those files to config.js and credentials.js, then edit freely. And the code can try to read from config.js and credentials.js first, then if the files don't exist fall back to the sample files.

That way you should maintain backwards compatibility for people who've already edited these files.

If this sounds good to you I can open a PR, now that I talked through it doesn't sound like it should be too hard.

**Comment by janoside** [comment]
I value your opinion about the approach I had in mind. I like the simplicity of your idea and would love a PR implementing it. Thanks!

**Comment by janoside** [comment]
The basic idea here was committed with 8e02736222. More improvements are likely with some upcoming PRs, but closing this issue.
