### ISSUE TITLE
No balance/tx history for certain addresses

### ISSUE THREAD

**Issue by sangaman** [janoside/btc-rpc-explorer#76]
With a properly configured electrum server, some (but not all) addresses incorrectly show no balance and no transaction history despite having some. I confirmed that the electrum server is returning the right data. The explorer logs show this error message whenever I load the address page:

```
Error 32197rgh327g2: [object Object], error json: {"server":"localhost"}
Error 23t07ug2wghefud: [object Object], error json: {"server":"localhost"}
```

Where `localhost` is the configured host for the electrum server.

The donation address `3NPGpNyLLmVKCEcuipBs7G4KpQJoJXjDGe` is one such address where I don't get any balance/transactions.

I tried debugging this, and unfortunately on my development machine I'm not getting this error with the same addresses and using the same bitcoind and electrum server instances, and it's hard to tell from looking at the code and the logs what is going wrong. I'll probably try again to figure it out but I thought I'd open the issue in case you had any ideas or others have seen the same.

**Comment by catmahia** [comment]
want to send to the address informed without delay because it has been requested and sent for some time
client expects the requested value or returned to the sender address

**Comment by janoside** [comment]
@sangaman There are some recent updates to the interface with ElectrumX. I also have finally set up my own ElectrumX for more reliable testing. I'm not seeing this myself (though my testing is admittedly light) - if you get a chance to update let me know what your status is. Also please note that after updating you'll need to set the new environment variable: BTCEXP_ADDRESS_API=electrumx

**Comment by sangaman** [comment]
Loading addresses/transactions seems to be fine now. I'll close this and reopen should I see similar issues. Thanks for fixing!

And fwiw, I'm using this with electrs instead of electrumx, although the interface they provide should be the same.
