### ISSUE TITLE
Unable connect with Electrs (Rust Electrum) properly

### ISSUE THREAD

**Issue by badabingbadaboom2** [janoside/btc-rpc-explorer#82]
**Describe the bug**
I'm trying to run this great block explorer project with Rust electrum (electrs), but I'm running into some issues. The app seems to find the electrum server, but it for instance shows no transactions, and the log shows errors.

**Environment (please complete the following information):**
 - Bitcoin Core / Node Version [0.17.0]
 - NodeJS Version [11.6.0]
 - Browser [firefox]
 - Code Version / Commit [7a880784eec7b7ffbed324d961a6b550cc5e6340]

**To Reproduce**
Start and sync electrs
Configure with electrum server in btc-rpc-explorer
localhost, 50001, tcp

**Screenshots or Log Output**

**Startup log:**
Connecting via RPC to node at localhost:8332
Connecting to ElectrumX Server: localhost:50001
Connected via RPC to node. Basic info: version=170000, subversion=/Satoshi:0.17.0/, protocolversion=70015, services=000000000000040d
Connected to ElectrumX Server: localhost:50001, versions: RustElectrum 0.1.0,1.4
Live with ElectrumX API.
Error:
{ Error: connect ECONNREFUSED 127.0.0.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1082:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 443 }
Response:
undefined

**Log when trying to show satoshi brainwallet:**
    Error 32197rgh327g2: [object Object], error json: {"server":"localhost"}
    GET /address/1JryTePceSiWVpoNBU8SbwiT7J4ghzijzW 200 12415.548 ms - 19492
    Error 23t07ug2wghefud: [object Object], error json: {"server":"localhost"}
    GET /css/radial-progress.css 304 2.345 ms - -
    GET /css/styling.css 304 1.540 ms - -
    GET /img/logo/btc.svg 304 2.038 ms - -
    GET /img/logo/ltc.svg 304 1.904 ms - -
    GET /img/logo/lightning.svg 304 4.489 ms

**Comment by agaga69** [comment]
You need a secure connection on port 50002 (SSL endpoint) .

On btc-rpc-explorer, change the config.js:
electrumXServers:[
{host: "localhost", port:50002, protocol: "ssl"}
]

on electrs server, you have to use NGINX (recommended) 
https://github.com/romanz/electrs/blob/master/doc/usage.md

or Hitch 
https://github.com/romanz/electrs/issues/32

I use Hitch & it seems to work (Sometimes you have to stop/restart the explorer)

**Comment by janoside** [comment]
I don't run Electrs myself. @badabingbadaboom2 Does @agaga69's suggestion do anything for you?

**Comment by janoside** [comment]
Happy to re-open if more info comes in.

**Comment by sangaman** [comment]
Fwiw, I use btc-rpc-explorer with electrs on port 50001 with plain tcp and it seems to work fine. If someone has problems with this, ping me and maybe I can help.

**Comment by k3tan172** [comment]
@sangaman @janoside does connecting to your own electrs/electrum server do away with having ```txindex=1``` in bitcoin.conf? Is that the point of it?
