### ISSUE TITLE
Add support for RegTest

### ISSUE THREAD

**Issue by yuhlau** [janoside/btc-rpc-explorer#84]
When the Bitcoin server is running in RegTest mode, home page throws an error of
`Invalid block count: should be between 0 and the block\'s height - 1`
when being accessed.

The cause is that on the home page it assumes Bitcoin server is running on mainnet and tries to call `getchaintxstats` RPC call with the last year of blocks. I have done a dirty fix to disable this feature at 
https://github.com/yuhlau/btc-rpc-explorer/commit/44f1ea558b6aec167997c2c193f1c4f47ea1e2ec
However, there can be a better way of handling it.

If wanted, I can help to make the changes and do a PR.

**Comment by janoside** [comment]
@yuhlau Thanks for the offer. I'll be happy to merge a PR with this fix if you do one.

**Comment by yuhlau** [comment]
@janoside No worries. Really appreciate your great work, it is very useful in my current work. Thanks for creating this project.

Right now, my fix is really dirty by just disabling it when the chain is RegTest. Do you have any idea in mind for the behaviour when running a RegTest node?

**Comment by janoside** [comment]
Honestly, no - I don't have any particular opinions about RegTest, other than hoping that running against a RegTest node doesn't break the app! If your changes stop the app from breaking I consider that a valid fix - gracefully degrading functionality is fine in my book.

And I'm very glad you're finding value in this project!
