### ISSUE TITLE
Error for RPC command 'getnetworkinfo': RpcError: -32601 Method not found

### ISSUE THREAD

**Issue by NaveenkumarSubramaniyam** [janoside/btc-rpc-explorer#85]
*I SetUp the Project as per the Instructions and targeted to the Node but still getting error 

Running RPC Explorer for Bitcoin
Connecting via RPC to node at 127.0.0.1:9999
Error for RPC command 'getnetworkinfo': RpcError: -32601 Method not found
Unhandled Rejection at: Promise Promise {
  <rejected> { RpcError: Method not found
      at getRpcResult (/sites/RPCExplorer/btc-rpc-explorer/node_modules/bitcoin-core/dist/src/parser.js:39:11)
      at Client.rpc (/sites/RPCExplorer/btc-rpc-explorer/node_modules/bitcoin-core/dist/src/parser.js:82:14)
      at Client.tryCatcher (/sites/RPCExplorer/btc-rpc-explorer/node_modules/bluebird/js/release/util.js:16:23)

**Comment by janoside** [comment]
@NaveenkumarSubramaniyam  Please add more info to this bug report. Specifically, version information for your node is needed. From what I see here this looks like a straightforward error being returned from your node: it seems that whatever version of node you're running doesn't include the "getnetworkinfo" RPC method. Unfortunately, this app doesn't currently have good version management for handling different RPC API versions, but that's something that I hope to improve eventually (though I don't have any immediate plans to implement it). That hopeful future improvement is documented as issue #53.
