### ISSUE TITLE
explorer not working with RPC

### ISSUE THREAD

**Issue by mariajohnfranklin** [janoside/btc-rpc-explorer#87]
Error for RPC command 'getmempoolinfo': RpcError: -32601 Method not found
Error for RPC command 'getchaintxstats': RpcError: -32601 Method not found
Error for RPC command 'getchaintxstats': RpcError: -32601 Method not found
Error for RPC command 'getchaintxstats': RpcError: -32601 Method not found

**Comment by janoside** [comment]
@mariajohnfranklin Please add more info to this bug report. Specifically, version information for your node is needed. From what I see here this looks like a straightforward error being returned from your node: it seems that whatever version of node you're running doesn't include the "getmempoolinfo" or "getchaintxstats" RPC methods. Unfortunately, this app doesn't currently have good version management for handling different RPC API versions, but that's something that I hope to improve eventually (though I don't have any immediate plans to implement it). That hopeful future improvement is documented as issue #53.
