### ISSUE TITLE
Packaging radial-progress.css for npm

### ISSUE THREAD

**Issue by shesek** [janoside/btc-rpc-explorer#93]
Right now, installing the package from github (`npm install -g janoside/btc-rpc-explorer`) *almost* works: you get everything but the `radial-progress.css` file, which isn't checked into git and has to be built from the `.less` file after installing the `devDependencies`.

To make installation easier, it would be nicer if the css file already came pre-compiled with the package, rather than the user having to do this manually. There are two ways to do this:

1. Create a new `.npmignore` file with all the lines in `.gitignore` except for `public/css/radial-progress.css`. Then, when publishing the package to the npm registry, this file will be added in, while still being kept out of git. This means that users will have to install the package from npm and not from github.

2. Remove `public/css/radial-progress.css` from `.gitignore` and so that it'll get checked into git. This way, users could also install the package directly from githhub (using `npm install -g janoside/btc-rpc-explorer`, which also allows installing from a specific commit/tag with `npm install -g janoside/btc-rpc-explorer#COMMIT-OR-TAG`, which is pretty useful). 

In either case, I would also suggest adding a `"prepublish": "npm run build"` hook to the `package.json`'s `scripts` section, to automatically compile the css whenever the package is published.

If this seems acceptable, let me know whether you prefer (1) or (2) and I'll send a PR.

**Comment by janoside** [comment]
From your descriptions, item 2 here seems the most versatile/helpful, which I like. Checking that giant, generated css into git feels a little dirty but the benefits seem to outweigh the costs, so let's go for it.

**Comment by shesek** [comment]
Yeah, agreed, it is dirty, but maybe acceptable because its just a single file. I probably wouldn't do it if there was a more complex build process that produced many files. I think its okay for now, it can be revisited in the future if btc-rpc-explorer gets extra build steps. I'll make a PR.

**Comment by janoside** [comment]
Closed by PR#93.
